// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CalendarKind.
const (
	Caldav CalendarKind = "caldav"
	Ics    CalendarKind = "ics"
	Local  CalendarKind = "local"
)

// Valid indicates whether the value is a known member of the CalendarKind enum.
func (e CalendarKind) Valid() bool {
	switch e {
	case Caldav:
		return true
	case Ics:
		return true
	case Local:
		return true
	default:
		return false
	}
}

// Calendar defines model for Calendar.
type Calendar struct {
	// Color #rrggbb，空表示默认色
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"createdAt"`
	Enabled   bool      `json:"enabled"`

	// EventCount 同步下来的事件条数（重复事件算一条）
	EventCount  int   `json:"eventCount"`
	HasPassword bool  `json:"hasPassword"`
	Id          int64 `json:"id"`

	// Kind ics 订阅链接，只读；caldav 可以读写（iCloud 等）；local 存在自己服务器上的日历
	Kind CalendarKind `json:"kind"`

	// LastError 上次同步的错误，成功时为空
	LastError    string     `json:"lastError"`
	LastSyncedAt *time.Time `json:"lastSyncedAt,omitempty"`
	Name         string     `json:"name"`
	Url          string     `json:"url"`
	Username     string     `json:"username"`

	// Writable 能不能在这个日历里新建和修改事件。local 和 caldav 为 true，ics 为 false
	Writable *bool `json:"writable,omitempty"`
}

// CalendarEvent defines model for CalendarEvent.
type CalendarEvent struct {
	AllDay bool `json:"allDay"`

	// Calendar 日历名
	Calendar    string    `json:"calendar"`
	CalendarId  int64     `json:"calendarId"`
	Color       string    `json:"color"`
	Description string    `json:"description"`
	End         time.Time `json:"end"`

	// EndDate 全天事件的结束日期 YYYY-MM-DD（不含）
	EndDate *string `json:"endDate,omitempty"`
	EventId int64   `json:"eventId"`

	// Id 每次发生唯一，事件 id 加开始时间
	Id        string    `json:"id"`
	Location  string    `json:"location"`
	Recurring bool      `json:"recurring"`
	Start     time.Time `json:"start"`

	// StartDate 全天事件的开始日期 YYYY-MM-DD
	StartDate *string `json:"startDate,omitempty"`
	Title     string  `json:"title"`

	// Writable 能不能改。日历可写且不是重复事件时为 true
	Writable *bool `json:"writable,omitempty"`
}

// CalendarInput defines model for CalendarInput.
type CalendarInput struct {
	Color   *string `json:"color,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`

	// Kind ics 订阅链接，只读；caldav 可以读写（iCloud 等）；local 存在自己服务器上的日历
	Kind CalendarKind `json:"kind"`
	Name string       `json:"name"`

	// Password 加密保存，不会再返回
	Password *string `json:"password,omitempty"`

	// Url ICS 订阅地址（webcal:// 也可以），或 CalDAV 日历集合、日历主目录的地址
	Url      string  `json:"url"`
	Username *string `json:"username,omitempty"`
}

// CalendarKind ics 订阅链接，只读；caldav 可以读写（iCloud 等）；local 存在自己服务器上的日历
type CalendarKind string

// CalendarPatch defines model for CalendarPatch.
type CalendarPatch struct {
	Color    *string `json:"color,omitempty"`
	Enabled  *bool   `json:"enabled,omitempty"`
	Name     *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
	Url      *string `json:"url,omitempty"`
	Username *string `json:"username,omitempty"`
}

// EventInput defines model for EventInput.
type EventInput struct {
	AllDay      bool    `json:"allDay"`
	CalendarId  int64   `json:"calendarId"`
	Description *string `json:"description,omitempty"`

	// End 不是全天事件时必填
	End *time.Time `json:"end,omitempty"`

	// EndDate 全天事件的结束日期 YYYY-MM-DD（不含）
	EndDate  *string `json:"endDate,omitempty"`
	Location *string `json:"location,omitempty"`

	// Start 不是全天事件时必填
	Start *time.Time `json:"start,omitempty"`

	// StartDate 全天事件的开始日期 YYYY-MM-DD
	StartDate *string `json:"startDate,omitempty"`
	Title     string  `json:"title"`
}

// EventPatch defines model for EventPatch.
type EventPatch struct {
	AllDay *bool `json:"allDay,omitempty"`

	// CalendarId 移到另一个可写的日历
	CalendarId  *int64     `json:"calendarId,omitempty"`
	Description *string    `json:"description,omitempty"`
	End         *time.Time `json:"end,omitempty"`
	EndDate     *string    `json:"endDate,omitempty"`
	Location    *string    `json:"location,omitempty"`
	Start       *time.Time `json:"start,omitempty"`
	StartDate   *string    `json:"startDate,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// CalendarId defines model for CalendarId.
type CalendarId = int64

// ListCalendarEventsParams defines parameters for ListCalendarEvents.
type ListCalendarEventsParams struct {
	From time.Time `form:"from" json:"from"`
	To   time.Time `form:"to" json:"to"`
}

// CreateCalendarEventJSONRequestBody defines body for CreateCalendarEvent for application/json ContentType.
type CreateCalendarEventJSONRequestBody = EventInput

// UpdateCalendarEventJSONRequestBody defines body for UpdateCalendarEvent for application/json ContentType.
type UpdateCalendarEventJSONRequestBody = EventPatch

// CreateCalendarJSONRequestBody defines body for CreateCalendar for application/json ContentType.
type CreateCalendarJSONRequestBody = CalendarInput

// UpdateCalendarJSONRequestBody defines body for UpdateCalendar for application/json ContentType.
type UpdateCalendarJSONRequestBody = CalendarPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /calendar/events)
	ListCalendarEvents(w http.ResponseWriter, r *http.Request, params ListCalendarEventsParams)

	// (POST /calendar/events)
	CreateCalendarEvent(w http.ResponseWriter, r *http.Request)

	// (DELETE /calendar/events/{eventId})
	DeleteCalendarEvent(w http.ResponseWriter, r *http.Request, eventId int64)

	// (PATCH /calendar/events/{eventId})
	UpdateCalendarEvent(w http.ResponseWriter, r *http.Request, eventId int64)

	// (GET /calendars)
	ListCalendars(w http.ResponseWriter, r *http.Request)

	// (POST /calendars)
	CreateCalendar(w http.ResponseWriter, r *http.Request)

	// (DELETE /calendars/{calendarId})
	DeleteCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)

	// (GET /calendars/{calendarId})
	GetCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)

	// (PATCH /calendars/{calendarId})
	UpdateCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)

	// (POST /calendars/{calendarId}/sync)
	SyncCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /calendar/events)
func (_ Unimplemented) ListCalendarEvents(w http.ResponseWriter, r *http.Request, params ListCalendarEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /calendar/events)
func (_ Unimplemented) CreateCalendarEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /calendar/events/{eventId})
func (_ Unimplemented) DeleteCalendarEvent(w http.ResponseWriter, r *http.Request, eventId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /calendar/events/{eventId})
func (_ Unimplemented) UpdateCalendarEvent(w http.ResponseWriter, r *http.Request, eventId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /calendars)
func (_ Unimplemented) ListCalendars(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /calendars)
func (_ Unimplemented) CreateCalendar(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /calendars/{calendarId})
func (_ Unimplemented) DeleteCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /calendars/{calendarId})
func (_ Unimplemented) GetCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /calendars/{calendarId})
func (_ Unimplemented) UpdateCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /calendars/{calendarId}/sync)
func (_ Unimplemented) SyncCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCalendarEvents operation middleware
func (siw *ServerInterfaceWrapper) ListCalendarEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCalendarEventsParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCalendarEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCalendarEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateCalendarEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCalendarEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCalendarEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteCalendarEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId int64

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCalendarEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCalendarEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateCalendarEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId int64

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCalendarEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCalendars operation middleware
func (siw *ServerInterfaceWrapper) ListCalendars(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCalendars(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCalendar operation middleware
func (siw *ServerInterfaceWrapper) CreateCalendar(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCalendar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCalendar operation middleware
func (siw *ServerInterfaceWrapper) DeleteCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCalendar operation middleware
func (siw *ServerInterfaceWrapper) UpdateCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncCalendar operation middleware
func (siw *ServerInterfaceWrapper) SyncCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendars", wrapper.ListCalendars)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/calendars", wrapper.CreateCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/calendars/{calendarId}", wrapper.DeleteCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendars/{calendarId}", wrapper.GetCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/calendars/{calendarId}", wrapper.UpdateCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/calendars/{calendarId}/sync", wrapper.SyncCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendar/events", wrapper.ListCalendarEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/calendar/events", wrapper.CreateCalendarEvent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/calendar/events/{eventId}", wrapper.DeleteCalendarEvent)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/calendar/events/{eventId}", wrapper.UpdateCalendarEvent)
	})

	return r
}
