// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ContactEventKind.
const (
	ContactEventKindAnniversary ContactEventKind = "anniversary"
	ContactEventKindBirthday    ContactEventKind = "birthday"
	ContactEventKindOther       ContactEventKind = "other"
)

// Valid indicates whether the value is a known member of the ContactEventKind enum.
func (e ContactEventKind) Valid() bool {
	switch e {
	case ContactEventKindAnniversary:
		return true
	case ContactEventKindBirthday:
		return true
	case ContactEventKindOther:
		return true
	default:
		return false
	}
}

// Defines values for ContactGroup.
const (
	ContactGroupColleague ContactGroup = "colleague"
	ContactGroupFamily    ContactGroup = "family"
	ContactGroupFriend    ContactGroup = "friend"
	ContactGroupOther     ContactGroup = "other"
)

// Valid indicates whether the value is a known member of the ContactGroup enum.
func (e ContactGroup) Valid() bool {
	switch e {
	case ContactGroupColleague:
		return true
	case ContactGroupFamily:
		return true
	case ContactGroupFriend:
		return true
	case ContactGroupOther:
		return true
	default:
		return false
	}
}

// Defines values for ContactStatus.
const (
	None    ContactStatus = "none"
	Ok      ContactStatus = "ok"
	Overdue ContactStatus = "overdue"
	Soon    ContactStatus = "soon"
)

// Valid indicates whether the value is a known member of the ContactStatus enum.
func (e ContactStatus) Valid() bool {
	switch e {
	case None:
		return true
	case Ok:
		return true
	case Overdue:
		return true
	case Soon:
		return true
	default:
		return false
	}
}

// Contact defines model for Contact.
type Contact struct {
	Archived bool `json:"archived"`

	// ContactDueIn 离该联系的日子还有几天，已过的是负数
	ContactDueIn     *int           `json:"contactDueIn,omitempty"`
	ContactEveryDays int            `json:"contactEveryDays"`
	CreatedAt        time.Time      `json:"createdAt"`
	Events           []ContactEvent `json:"events"`
	Group            ContactGroup   `json:"group"`
	Id               int64          `json:"id"`

	// LastContactOn YYYY-MM-DD，空表示没记过
	LastContactOn  string        `json:"lastContactOn"`
	Name           string        `json:"name"`
	NextEventIn    *int          `json:"nextEventIn,omitempty"`
	NextEventLabel *string       `json:"nextEventLabel,omitempty"`
	Notes          string        `json:"notes"`
	RemindDays     []int         `json:"remindDays"`
	SinceContact   *int          `json:"sinceContact,omitempty"`
	Status         ContactStatus `json:"status"`
	UpdatedAt      time.Time     `json:"updatedAt"`
}

// ContactEvent defines model for ContactEvent.
type ContactEvent struct {
	Date  string           `json:"date"`
	Id    string           `json:"id"`
	Kind  ContactEventKind `json:"kind"`
	Label string           `json:"label"`

	// NextIn 离下一次还有几天，今天是 0
	NextIn int `json:"nextIn"`

	// NextOn 下一次的日期 YYYY-MM-DD
	NextOn string `json:"nextOn"`

	// Years 下一次是几岁或几周年，没写年份就没有
	Years *int `json:"years,omitempty"`
}

// ContactEventInput defines model for ContactEventInput.
type ContactEventInput struct {
	// Date MM-DD 或 YYYY-MM-DD
	Date string `json:"date"`

	// Id 已有的日期带上它，新的不填
	Id   *string          `json:"id,omitempty"`
	Kind ContactEventKind `json:"kind"`

	// Label 不填就用类型的名字
	Label *string `json:"label,omitempty"`
}

// ContactEventKind defines model for ContactEventKind.
type ContactEventKind string

// ContactGroup defines model for ContactGroup.
type ContactGroup string

// ContactInput defines model for ContactInput.
type ContactInput struct {
	ContactEveryDays *int                 `json:"contactEveryDays,omitempty"`
	Events           *[]ContactEventInput `json:"events,omitempty"`
	Group            *ContactGroup        `json:"group,omitempty"`
	LastContactOn    *string              `json:"lastContactOn,omitempty"`
	Name             string               `json:"name"`
	Notes            *string              `json:"notes,omitempty"`
	RemindDays       *[]int               `json:"remindDays,omitempty"`
}

// ContactPatch defines model for ContactPatch.
type ContactPatch struct {
	Archived         *bool                `json:"archived,omitempty"`
	ContactEveryDays *int                 `json:"contactEveryDays,omitempty"`
	Events           *[]ContactEventInput `json:"events,omitempty"`
	Group            *ContactGroup        `json:"group,omitempty"`
	LastContactOn    *string              `json:"lastContactOn,omitempty"`
	Name             *string              `json:"name,omitempty"`
	Notes            *string              `json:"notes,omitempty"`
	RemindDays       *[]int               `json:"remindDays,omitempty"`
}

// ContactStatus defines model for ContactStatus.
type ContactStatus string

// ContactSummary defines model for ContactSummary.
type ContactSummary struct {
	Overdue int `json:"overdue"`
	Soon    int `json:"soon"`
	Total   int `json:"total"`
}

// ContactTouch defines model for ContactTouch.
type ContactTouch struct {
	// Date 不填就是今天
	Date *string `json:"date,omitempty"`
}

// ContactId defines model for ContactId.
type ContactId = int64

// ListContactsParams defines parameters for ListContacts.
type ListContactsParams struct {
	Group *ContactGroup `form:"group,omitempty" json:"group,omitempty"`

	// Q 在名称和备注里找
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Archived true 时包含已归档的，默认不含
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`
}

// CreateContactJSONRequestBody defines body for CreateContact for application/json ContentType.
type CreateContactJSONRequestBody = ContactInput

// UpdateContactJSONRequestBody defines body for UpdateContact for application/json ContentType.
type UpdateContactJSONRequestBody = ContactPatch

// TouchContactJSONRequestBody defines body for TouchContact for application/json ContentType.
type TouchContactJSONRequestBody = ContactTouch

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /contacts)
	ListContacts(w http.ResponseWriter, r *http.Request, params ListContactsParams)

	// (POST /contacts)
	CreateContact(w http.ResponseWriter, r *http.Request)

	// (DELETE /contacts/{contactId})
	DeleteContact(w http.ResponseWriter, r *http.Request, contactId ContactId)

	// (GET /contacts/{contactId})
	GetContact(w http.ResponseWriter, r *http.Request, contactId ContactId)

	// (PATCH /contacts/{contactId})
	UpdateContact(w http.ResponseWriter, r *http.Request, contactId ContactId)

	// (POST /contacts/{contactId}/touch)
	TouchContact(w http.ResponseWriter, r *http.Request, contactId ContactId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /contacts)
func (_ Unimplemented) ListContacts(w http.ResponseWriter, r *http.Request, params ListContactsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /contacts)
func (_ Unimplemented) CreateContact(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /contacts/{contactId})
func (_ Unimplemented) DeleteContact(w http.ResponseWriter, r *http.Request, contactId ContactId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /contacts/{contactId})
func (_ Unimplemented) GetContact(w http.ResponseWriter, r *http.Request, contactId ContactId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /contacts/{contactId})
func (_ Unimplemented) UpdateContact(w http.ResponseWriter, r *http.Request, contactId ContactId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /contacts/{contactId}/touch)
func (_ Unimplemented) TouchContact(w http.ResponseWriter, r *http.Request, contactId ContactId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListContacts operation middleware
func (siw *ServerInterfaceWrapper) ListContacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListContactsParams

	// ------------- Optional query parameter "group" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group", r.URL.Query(), &params.Group, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "group"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContacts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateContact operation middleware
func (siw *ServerInterfaceWrapper) CreateContact(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateContact(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteContact operation middleware
func (siw *ServerInterfaceWrapper) DeleteContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "contactId" -------------
	var contactId ContactId

	err = runtime.BindStyledParameterWithOptions("simple", "contactId", chi.URLParam(r, "contactId"), &contactId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contactId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteContact(w, r, contactId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetContact operation middleware
func (siw *ServerInterfaceWrapper) GetContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "contactId" -------------
	var contactId ContactId

	err = runtime.BindStyledParameterWithOptions("simple", "contactId", chi.URLParam(r, "contactId"), &contactId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contactId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContact(w, r, contactId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateContact operation middleware
func (siw *ServerInterfaceWrapper) UpdateContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "contactId" -------------
	var contactId ContactId

	err = runtime.BindStyledParameterWithOptions("simple", "contactId", chi.URLParam(r, "contactId"), &contactId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contactId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateContact(w, r, contactId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TouchContact operation middleware
func (siw *ServerInterfaceWrapper) TouchContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "contactId" -------------
	var contactId ContactId

	err = runtime.BindStyledParameterWithOptions("simple", "contactId", chi.URLParam(r, "contactId"), &contactId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contactId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TouchContact(w, r, contactId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/contacts", wrapper.ListContacts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/contacts", wrapper.CreateContact)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/contacts/{contactId}", wrapper.DeleteContact)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/contacts/{contactId}", wrapper.GetContact)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/contacts/{contactId}", wrapper.UpdateContact)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/contacts/{contactId}/touch", wrapper.TouchContact)
	})

	return r
}
