// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	externalRef0 "github.com/j0x3n/x-console/backend/internal/server/apigen/common"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AiAgentAccess.
const (
	Read        AiAgentAccess = "read"
	Write       AiAgentAccess = "write"
	WriteDelete AiAgentAccess = "write_delete"
)

// Valid indicates whether the value is a known member of the AiAgentAccess enum.
func (e AiAgentAccess) Valid() bool {
	switch e {
	case Read:
		return true
	case Write:
		return true
	case WriteDelete:
		return true
	default:
		return false
	}
}

// Defines values for AiAgentDecisionKind.
const (
	Permission AiAgentDecisionKind = "permission"
	Question   AiAgentDecisionKind = "question"
)

// Valid indicates whether the value is a known member of the AiAgentDecisionKind enum.
func (e AiAgentDecisionKind) Valid() bool {
	switch e {
	case Permission:
		return true
	case Question:
		return true
	default:
		return false
	}
}

// Defines values for AiAgentKind.
const (
	Builtin    AiAgentKind = "builtin"
	ClaudeCode AiAgentKind = "claude_code"
	Codex      AiAgentKind = "codex"
)

// Valid indicates whether the value is a known member of the AiAgentKind enum.
func (e AiAgentKind) Valid() bool {
	switch e {
	case Builtin:
		return true
	case ClaudeCode:
		return true
	case Codex:
		return true
	default:
		return false
	}
}

// Defines values for AiAgentRunEventKind.
const (
	Decision AiAgentRunEventKind = "decision"
	Error    AiAgentRunEventKind = "error"
	Status   AiAgentRunEventKind = "status"
	Text     AiAgentRunEventKind = "text"
	Tool     AiAgentRunEventKind = "tool"
)

// Valid indicates whether the value is a known member of the AiAgentRunEventKind enum.
func (e AiAgentRunEventKind) Valid() bool {
	switch e {
	case Decision:
		return true
	case Error:
		return true
	case Status:
		return true
	case Text:
		return true
	case Tool:
		return true
	default:
		return false
	}
}

// Defines values for AiAgentRunStatus.
const (
	Canceled AiAgentRunStatus = "canceled"
	Done     AiAgentRunStatus = "done"
	Failed   AiAgentRunStatus = "failed"
	PrOpened AiAgentRunStatus = "pr_opened"
	Queued   AiAgentRunStatus = "queued"
	Running  AiAgentRunStatus = "running"
	Waiting  AiAgentRunStatus = "waiting"
)

// Valid indicates whether the value is a known member of the AiAgentRunStatus enum.
func (e AiAgentRunStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Done:
		return true
	case Failed:
		return true
	case PrOpened:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for CliPermission.
const (
	Full      CliPermission = "full"
	Workspace CliPermission = "workspace"
)

// Valid indicates whether the value is a known member of the CliPermission enum.
func (e CliPermission) Valid() bool {
	switch e {
	case Full:
		return true
	case Workspace:
		return true
	default:
		return false
	}
}

// Defines values for GitConnectionKind.
const (
	Forgejo GitConnectionKind = "forgejo"
	Github  GitConnectionKind = "github"
)

// Valid indicates whether the value is a known member of the GitConnectionKind enum.
func (e GitConnectionKind) Valid() bool {
	switch e {
	case Forgejo:
		return true
	case Github:
		return true
	default:
		return false
	}
}

// AiAgent defines model for AiAgent.
type AiAgent struct {
	Access        AiAgentAccess `json:"access"`
	AutoBuild     bool          `json:"autoBuild"`
	Avatar        string        `json:"avatar"`
	BuildRetries  int           `json:"buildRetries"`
	CliPermission CliPermission `json:"cliPermission"`
	Color         string        `json:"color"`
	CreatedAt     time.Time     `json:"createdAt"`
	Enabled       bool          `json:"enabled"`

	// HostIds B60。这个 Agent 能操作的机器（代理 id）。面板 AI 只能通过勾选了这台机器的 Agent 操作它
	HostIds []string `json:"hostIds"`

	// HostNames hostIds 对应的机器名，顺序一样
	HostNames    []string    `json:"hostNames"`
	Id           int64       `json:"id"`
	Instructions string      `json:"instructions"`
	Kind         AiAgentKind `json:"kind"`
	MaxParallel  int         `json:"maxParallel"`
	Model        string      `json:"model"`

	// MonthCostUsd 本月费用，按 AI 用量记录算
	MonthCostUsd     float64  `json:"monthCostUsd"`
	MonthlyBudgetUsd *float64 `json:"monthlyBudgetUsd,omitempty"`
	Name             string   `json:"name"`
	OverBudget       *bool    `json:"overBudget,omitempty"`
	QueuedTasks      int      `json:"queuedTasks"`
	RepoIds          []int64  `json:"repoIds"`
	RunnerAgentId    *string  `json:"runnerAgentId,omitempty"`

	// RunnerName 默认机器的名字
	RunnerName   *string   `json:"runnerName,omitempty"`
	RunningTasks int       `json:"runningTasks"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// AiAgentAccess defines model for AiAgentAccess.
type AiAgentAccess string

// AiAgentDecision defines model for AiAgentDecision.
type AiAgentDecision struct {
	// AgentId AI 助手会话里的动作没有
	AgentId   *int64  `json:"agentId,omitempty"`
	AgentName *string `json:"agentName,omitempty"`

	// ConversationId AI 助手会话里的动作才有
	ConversationId *int64    `json:"conversationId,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`

	// Detail Markdown，命令、参数或问题的背景
	Detail *string `json:"detail,omitempty"`

	// Id 例如 run:12:3、action:45
	Id       string              `json:"id"`
	IssueKey *string             `json:"issueKey,omitempty"`
	Kind     AiAgentDecisionKind `json:"kind"`

	// Options kind=question 时可以直接点的选项，可以为空（只能自己写）
	Options *[]string `json:"options,omitempty"`
	RunId   *int64    `json:"runId,omitempty"`

	// Title 一句话，比如“要删除卡片 XC-12”“用哪个数据库？”
	Title string `json:"title"`
}

// AiAgentDecisionKind defines model for AiAgentDecision.Kind.
type AiAgentDecisionKind string

// AiAgentInput defines model for AiAgentInput.
type AiAgentInput struct {
	Access        *AiAgentAccess `json:"access,omitempty"`
	AutoBuild     *bool          `json:"autoBuild,omitempty"`
	Avatar        *string        `json:"avatar,omitempty"`
	BuildRetries  *int           `json:"buildRetries,omitempty"`
	CliPermission *CliPermission `json:"cliPermission,omitempty"`
	Color         *string        `json:"color,omitempty"`
	Enabled       *bool          `json:"enabled,omitempty"`

	// HostIds B60。能操作的机器。增加机器要提升权限
	HostIds          *[]string    `json:"hostIds,omitempty"`
	Instructions     *string      `json:"instructions,omitempty"`
	Kind             *AiAgentKind `json:"kind,omitempty"`
	MaxParallel      *int         `json:"maxParallel,omitempty"`
	Model            *string      `json:"model,omitempty"`
	MonthlyBudgetUsd *float64     `json:"monthlyBudgetUsd,omitempty"`
	Name             *string      `json:"name,omitempty"`
	RepoIds          *[]int64     `json:"repoIds,omitempty"`
	RunnerAgentId    *string      `json:"runnerAgentId,omitempty"`
}

// AiAgentKind defines model for AiAgentKind.
type AiAgentKind string

// AiAgentNotify B87。每类 Agent 通知的开关，默认 received、started 关，其他开
type AiAgentNotify struct {
	// Decision 需要你决定（权限请求、问题、编码任务做完等你审查）
	Decision bool `json:"decision"`

	// Done 完成任务
	Done bool `json:"done"`

	// Failed 失败或中断
	Failed bool `json:"failed"`

	// PrOpened 已提 PR
	PrOpened bool `json:"prOpened"`

	// Received 收到任务（分配了卡片，排上队）
	Received bool `json:"received"`

	// Started 开始任务
	Started bool `json:"started"`
}

// AiAgentRun defines model for AiAgentRun.
type AiAgentRun struct {
	AgentId    int64      `json:"agentId"`
	AgentName  string     `json:"agentName"`
	CreatedAt  time.Time  `json:"createdAt"`
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	Id         int64      `json:"id"`

	// IssueKey 卡片编号，可能为空
	IssueKey   string      `json:"issueKey"`
	IssueTitle string      `json:"issueTitle"`
	Kind       AiAgentKind `json:"kind"`
	PrUrl      *string     `json:"prUrl,omitempty"`
	StartedAt  *time.Time  `json:"startedAt,omitempty"`

	// Status B86。waiting 是在等你决定（权限请求或问题）
	Status AiAgentRunStatus `json:"status"`

	// Summary 做完后的说明，或失败原因
	Summary *string `json:"summary,omitempty"`

	// TaskId CLI 类型对应的编码任务
	TaskId *int64 `json:"taskId,omitempty"`
}

// AiAgentRunEvent defines model for AiAgentRunEvent.
type AiAgentRunEvent struct {
	At time.Time `json:"at"`

	// Kind status 状态变化；tool 调了一个工具（text 是工具名和参数摘要）；text Agent 的输出；decision 等你决定；error 出错
	Kind AiAgentRunEventKind `json:"kind"`

	// Ok kind=tool 时工具是否成功
	Ok   *bool  `json:"ok,omitempty"`
	Seq  int64  `json:"seq"`
	Text string `json:"text"`

	// Tool kind=tool 时的工具名
	Tool *string `json:"tool,omitempty"`
}

// AiAgentRunEventKind status 状态变化；tool 调了一个工具（text 是工具名和参数摘要）；text Agent 的输出；decision 等你决定；error 出错
type AiAgentRunEventKind string

// AiAgentRunStatus B86。waiting 是在等你决定（权限请求或问题）
type AiAgentRunStatus string

// CliPermission defines model for CliPermission.
type CliPermission string

// GitConnection defines model for GitConnection.
type GitConnection struct {
	BaseUrl       string            `json:"baseUrl"`
	CreatedAt     time.Time         `json:"createdAt"`
	HasToken      bool              `json:"hasToken"`
	Id            int64             `json:"id"`
	Kind          GitConnectionKind `json:"kind"`
	LastCheckedAt *time.Time        `json:"lastCheckedAt,omitempty"`
	LastError     string            `json:"lastError"`
	Name          string            `json:"name"`

	// UseGithubModule B62 起不用，下个版本删
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	UseGithubModule bool   `json:"useGithubModule"`
	Username        string `json:"username"`
	WebhookPath     string `json:"webhookPath"`
}

// GitConnectionKind defines model for GitConnectionKind.
type GitConnectionKind string

// RemoteRepo defines model for RemoteRepo.
type RemoteRepo struct {
	CloneUrl      string  `json:"cloneUrl"`
	DefaultBranch string  `json:"defaultBranch"`
	Description   *string `json:"description,omitempty"`
	FullName      string  `json:"fullName"`
	HtmlUrl       *string `json:"htmlUrl,omitempty"`
	Name          string  `json:"name"`
	Owner         string  `json:"owner"`
	Private       bool    `json:"private"`
}

// AnswerAiAgentDecisionJSONBody defines parameters for AnswerAiAgentDecision.
type AnswerAiAgentDecisionJSONBody struct {
	Answer  *string `json:"answer,omitempty"`
	Approve *bool   `json:"approve,omitempty"`
}

// ListAiAgentRunsParams defines parameters for ListAiAgentRuns.
type ListAiAgentRunsParams struct {
	AgentId  *int64              `form:"agentId,omitempty" json:"agentId,omitempty"`
	IssueKey *string             `form:"issueKey,omitempty" json:"issueKey,omitempty"`
	Limit    *externalRef0.Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAiAgentRunEventsParams defines parameters for ListAiAgentRunEvents.
type ListAiAgentRunEventsParams struct {
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
}

// AssignAiAgentJSONBody defines parameters for AssignAiAgent.
type AssignAiAgentJSONBody struct {
	// BaseBranch 不传用仓库默认分支
	BaseBranch *string `json:"baseBranch,omitempty"`
	IssueKey   string  `json:"issueKey"`

	// Note 这次额外的要求
	Note *string `json:"note,omitempty"`

	// OpenPr B86。CLI 类型做完（开了自动构建时要构建通过）后自动提交、推送并提 PR，PR 地址写回卡片。不传按 true
	OpenPr *bool `json:"openPr,omitempty"`

	// RepoId CLI 类型要在 Agent 允许的仓库里。B86：不传时用卡片所在看板绑定的仓库，
	// 这台机器上还没有这个仓库就先 clone；看板也没绑定时回 409，code 是 board_repo_missing
	RepoId *int64 `json:"repoId,omitempty"`

	// RunnerAgentId 不传用 Agent 的默认机器
	RunnerAgentId *string `json:"runnerAgentId,omitempty"`
}

// CreateGitConnectionJSONBody defines parameters for CreateGitConnection.
type CreateGitConnectionJSONBody struct {
	// BaseUrl Forgejo 必填，比如 https://git.example.com；GitHub 不传用 https://api.github.com
	BaseUrl *string           `json:"baseUrl,omitempty"`
	Kind    GitConnectionKind `json:"kind"`
	Name    string            `json:"name"`

	// Token 访问令牌，useGithubModule 为 true 时不传
	Token *string `json:"token,omitempty"`

	// UseGithubModule B62 起不用，下个版本删。令牌都填在 Git 账号里
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	UseGithubModule *bool `json:"useGithubModule,omitempty"`
}

// UpdateGitConnectionJSONBody defines parameters for UpdateGitConnection.
type UpdateGitConnectionJSONBody struct {
	Name  *string `json:"name,omitempty"`
	Token *string `json:"token,omitempty"`
}

// ListRemoteReposParams defines parameters for ListRemoteRepos.
type ListRemoteReposParams struct {
	// Q 按名字过滤
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CreateAiAgentJSONRequestBody defines body for CreateAiAgent for application/json ContentType.
type CreateAiAgentJSONRequestBody = AiAgentInput

// AnswerAiAgentDecisionJSONRequestBody defines body for AnswerAiAgentDecision for application/json ContentType.
type AnswerAiAgentDecisionJSONRequestBody AnswerAiAgentDecisionJSONBody

// PutAiAgentNotifyJSONRequestBody defines body for PutAiAgentNotify for application/json ContentType.
type PutAiAgentNotifyJSONRequestBody = AiAgentNotify

// UpdateAiAgentJSONRequestBody defines body for UpdateAiAgent for application/json ContentType.
type UpdateAiAgentJSONRequestBody = AiAgentInput

// AssignAiAgentJSONRequestBody defines body for AssignAiAgent for application/json ContentType.
type AssignAiAgentJSONRequestBody AssignAiAgentJSONBody

// CreateGitConnectionJSONRequestBody defines body for CreateGitConnection for application/json ContentType.
type CreateGitConnectionJSONRequestBody CreateGitConnectionJSONBody

// UpdateGitConnectionJSONRequestBody defines body for UpdateGitConnection for application/json ContentType.
type UpdateGitConnectionJSONRequestBody UpdateGitConnectionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /ai-agents)
	ListAiAgents(w http.ResponseWriter, r *http.Request)

	// (POST /ai-agents)
	CreateAiAgent(w http.ResponseWriter, r *http.Request)

	// (GET /ai-agents/decisions)
	ListAiAgentDecisions(w http.ResponseWriter, r *http.Request)

	// (POST /ai-agents/decisions/{decisionId})
	AnswerAiAgentDecision(w http.ResponseWriter, r *http.Request, decisionId string)

	// (GET /ai-agents/notify)
	GetAiAgentNotify(w http.ResponseWriter, r *http.Request)

	// (PUT /ai-agents/notify)
	PutAiAgentNotify(w http.ResponseWriter, r *http.Request)

	// (GET /ai-agents/runs)
	ListAiAgentRuns(w http.ResponseWriter, r *http.Request, params ListAiAgentRunsParams)

	// (POST /ai-agents/runs/{runId}/cancel)
	CancelAiAgentRun(w http.ResponseWriter, r *http.Request, runId int64)

	// (GET /ai-agents/runs/{runId}/events)
	ListAiAgentRunEvents(w http.ResponseWriter, r *http.Request, runId int64, params ListAiAgentRunEventsParams)

	// (DELETE /ai-agents/{agentId})
	DeleteAiAgent(w http.ResponseWriter, r *http.Request, agentId int64)

	// (GET /ai-agents/{agentId})
	GetAiAgent(w http.ResponseWriter, r *http.Request, agentId int64)

	// (PATCH /ai-agents/{agentId})
	UpdateAiAgent(w http.ResponseWriter, r *http.Request, agentId int64)

	// (POST /ai-agents/{agentId}/assign)
	AssignAiAgent(w http.ResponseWriter, r *http.Request, agentId int64)

	// (GET /git-connections)
	ListGitConnections(w http.ResponseWriter, r *http.Request)

	// (POST /git-connections)
	CreateGitConnection(w http.ResponseWriter, r *http.Request)

	// (DELETE /git-connections/{connectionId})
	DeleteGitConnection(w http.ResponseWriter, r *http.Request, connectionId int64)

	// (PATCH /git-connections/{connectionId})
	UpdateGitConnection(w http.ResponseWriter, r *http.Request, connectionId int64)

	// (POST /git-connections/{connectionId}/check)
	CheckGitConnection(w http.ResponseWriter, r *http.Request, connectionId int64)

	// (GET /git-connections/{connectionId}/repos)
	ListRemoteRepos(w http.ResponseWriter, r *http.Request, connectionId int64, params ListRemoteReposParams)

	// (GET /git-connections/{connectionId}/webhook)
	GetGitWebhook(w http.ResponseWriter, r *http.Request, connectionId int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /ai-agents)
func (_ Unimplemented) ListAiAgents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai-agents)
func (_ Unimplemented) CreateAiAgent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai-agents/decisions)
func (_ Unimplemented) ListAiAgentDecisions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai-agents/decisions/{decisionId})
func (_ Unimplemented) AnswerAiAgentDecision(w http.ResponseWriter, r *http.Request, decisionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai-agents/notify)
func (_ Unimplemented) GetAiAgentNotify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /ai-agents/notify)
func (_ Unimplemented) PutAiAgentNotify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai-agents/runs)
func (_ Unimplemented) ListAiAgentRuns(w http.ResponseWriter, r *http.Request, params ListAiAgentRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai-agents/runs/{runId}/cancel)
func (_ Unimplemented) CancelAiAgentRun(w http.ResponseWriter, r *http.Request, runId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai-agents/runs/{runId}/events)
func (_ Unimplemented) ListAiAgentRunEvents(w http.ResponseWriter, r *http.Request, runId int64, params ListAiAgentRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /ai-agents/{agentId})
func (_ Unimplemented) DeleteAiAgent(w http.ResponseWriter, r *http.Request, agentId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai-agents/{agentId})
func (_ Unimplemented) GetAiAgent(w http.ResponseWriter, r *http.Request, agentId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /ai-agents/{agentId})
func (_ Unimplemented) UpdateAiAgent(w http.ResponseWriter, r *http.Request, agentId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai-agents/{agentId}/assign)
func (_ Unimplemented) AssignAiAgent(w http.ResponseWriter, r *http.Request, agentId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /git-connections)
func (_ Unimplemented) ListGitConnections(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /git-connections)
func (_ Unimplemented) CreateGitConnection(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /git-connections/{connectionId})
func (_ Unimplemented) DeleteGitConnection(w http.ResponseWriter, r *http.Request, connectionId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /git-connections/{connectionId})
func (_ Unimplemented) UpdateGitConnection(w http.ResponseWriter, r *http.Request, connectionId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /git-connections/{connectionId}/check)
func (_ Unimplemented) CheckGitConnection(w http.ResponseWriter, r *http.Request, connectionId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /git-connections/{connectionId}/repos)
func (_ Unimplemented) ListRemoteRepos(w http.ResponseWriter, r *http.Request, connectionId int64, params ListRemoteReposParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /git-connections/{connectionId}/webhook)
func (_ Unimplemented) GetGitWebhook(w http.ResponseWriter, r *http.Request, connectionId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAiAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAiAgents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAiAgents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAiAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAiAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAiAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAiAgentDecisions operation middleware
func (siw *ServerInterfaceWrapper) ListAiAgentDecisions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAiAgentDecisions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnswerAiAgentDecision operation middleware
func (siw *ServerInterfaceWrapper) AnswerAiAgentDecision(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "decisionId" -------------
	var decisionId string

	err = runtime.BindStyledParameterWithOptions("simple", "decisionId", chi.URLParam(r, "decisionId"), &decisionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "decisionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnswerAiAgentDecision(w, r, decisionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAiAgentNotify operation middleware
func (siw *ServerInterfaceWrapper) GetAiAgentNotify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAiAgentNotify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAiAgentNotify operation middleware
func (siw *ServerInterfaceWrapper) PutAiAgentNotify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAiAgentNotify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAiAgentRuns operation middleware
func (siw *ServerInterfaceWrapper) ListAiAgentRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAiAgentRunsParams

	// ------------- Optional query parameter "agentId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "agentId", r.URL.Query(), &params.AgentId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "agentId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "issueKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "issueKey", r.URL.Query(), &params.IssueKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "issueKey"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "issueKey", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAiAgentRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelAiAgentRun operation middleware
func (siw *ServerInterfaceWrapper) CancelAiAgentRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId int64

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelAiAgentRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAiAgentRunEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAiAgentRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId int64

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAiAgentRunEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAiAgentRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAiAgent operation middleware
func (siw *ServerInterfaceWrapper) DeleteAiAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "agentId" -------------
	var agentId int64

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAiAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAiAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAiAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "agentId" -------------
	var agentId int64

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAiAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAiAgent operation middleware
func (siw *ServerInterfaceWrapper) UpdateAiAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "agentId" -------------
	var agentId int64

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAiAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignAiAgent operation middleware
func (siw *ServerInterfaceWrapper) AssignAiAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "agentId" -------------
	var agentId int64

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignAiAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGitConnections operation middleware
func (siw *ServerInterfaceWrapper) ListGitConnections(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGitConnections(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGitConnection operation middleware
func (siw *ServerInterfaceWrapper) CreateGitConnection(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGitConnection(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGitConnection operation middleware
func (siw *ServerInterfaceWrapper) DeleteGitConnection(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "connectionId" -------------
	var connectionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "connectionId", chi.URLParam(r, "connectionId"), &connectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGitConnection(w, r, connectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGitConnection operation middleware
func (siw *ServerInterfaceWrapper) UpdateGitConnection(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "connectionId" -------------
	var connectionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "connectionId", chi.URLParam(r, "connectionId"), &connectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGitConnection(w, r, connectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckGitConnection operation middleware
func (siw *ServerInterfaceWrapper) CheckGitConnection(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "connectionId" -------------
	var connectionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "connectionId", chi.URLParam(r, "connectionId"), &connectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckGitConnection(w, r, connectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRemoteRepos operation middleware
func (siw *ServerInterfaceWrapper) ListRemoteRepos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "connectionId" -------------
	var connectionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "connectionId", chi.URLParam(r, "connectionId"), &connectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRemoteReposParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRemoteRepos(w, r, connectionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGitWebhook operation middleware
func (siw *ServerInterfaceWrapper) GetGitWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "connectionId" -------------
	var connectionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "connectionId", chi.URLParam(r, "connectionId"), &connectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGitWebhook(w, r, connectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai-agents", wrapper.ListAiAgents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai-agents", wrapper.CreateAiAgent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/ai-agents/{agentId}", wrapper.DeleteAiAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai-agents/{agentId}", wrapper.GetAiAgent)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/ai-agents/{agentId}", wrapper.UpdateAiAgent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai-agents/{agentId}/assign", wrapper.AssignAiAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai-agents/runs", wrapper.ListAiAgentRuns)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai-agents/runs/{runId}/events", wrapper.ListAiAgentRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai-agents/runs/{runId}/cancel", wrapper.CancelAiAgentRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai-agents/decisions", wrapper.ListAiAgentDecisions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai-agents/decisions/{decisionId}", wrapper.AnswerAiAgentDecision)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai-agents/notify", wrapper.GetAiAgentNotify)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/ai-agents/notify", wrapper.PutAiAgentNotify)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/git-connections", wrapper.ListGitConnections)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/git-connections", wrapper.CreateGitConnection)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/git-connections/{connectionId}", wrapper.DeleteGitConnection)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/git-connections/{connectionId}", wrapper.UpdateGitConnection)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/git-connections/{connectionId}/check", wrapper.CheckGitConnection)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/git-connections/{connectionId}/repos", wrapper.ListRemoteRepos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/git-connections/{connectionId}/webhook", wrapper.GetGitWebhook)
	})

	return r
}
