// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for PendingActionStatus.
const (
	Approved PendingActionStatus = "approved"
	Done     PendingActionStatus = "done"
	Failed   PendingActionStatus = "failed"
	Pending  PendingActionStatus = "pending"
	Rejected PendingActionStatus = "rejected"
)

// Valid indicates whether the value is a known member of the PendingActionStatus enum.
func (e PendingActionStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Done:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for ToolEffect.
const (
	Dangerous ToolEffect = "dangerous"
	Read      ToolEffect = "read"
	Write     ToolEffect = "write"
)

// Valid indicates whether the value is a known member of the ToolEffect enum.
func (e ToolEffect) Valid() bool {
	switch e {
	case Dangerous:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// AiSettings defines model for AiSettings.
type AiSettings struct {
	// ConfirmAllWrites 打开后所有写操作都先确认。关闭时只有删除类和 dangerous 动作要确认
	ConfirmAllWrites bool `json:"confirmAllWrites"`
	HasApiKey        bool `json:"hasApiKey"`

	// Model 默认 claude-opus-5-5
	Model string `json:"model"`
}

// ContentBlock 常见的几种：
// {type: text, text}；{type: tool_use, id, name, input}；
// {type: tool_result, tool_use_id, content, is_error}；{type: thinking, thinking}。
// 用户消息里的页面上下文放在 {type: text, text, context: true}，前端不显示。
type ContentBlock struct {
	Content              interface{}             `json:"content,omitempty"`
	Context              *bool                   `json:"context,omitempty"`
	Id                   *string                 `json:"id,omitempty"`
	Input                *map[string]interface{} `json:"input,omitempty"`
	IsError              *bool                   `json:"is_error,omitempty"`
	Name                 *string                 `json:"name,omitempty"`
	Text                 *string                 `json:"text,omitempty"`
	ToolUseId            *string                 `json:"tool_use_id,omitempty"`
	Type                 string                  `json:"type"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`

	// Title 第一条消息的开头，空对话为空字符串
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	Conversation Conversation `json:"conversation"`
	Messages     []Message    `json:"messages"`

	// PendingActions 这个对话里所有需要确认的动作，包括已经处理过的
	PendingActions []PendingAction `json:"pendingActions"`

	// Running 这一轮回复还没结束
	Running bool `json:"running"`
}

// Message defines model for Message.
type Message struct {
	// Content 原样保存 Anthropic API 的 content blocks
	Content   []ContentBlock `json:"content"`
	CreatedAt time.Time      `json:"createdAt"`
	Id        int64          `json:"id"`
	Role      MessageRole    `json:"role"`
	Seq       int            `json:"seq"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// PendingAction defines model for PendingAction.
type PendingAction struct {
	// Action 动作名，例如 notes.delete
	Action         string                 `json:"action"`
	ConversationId int64                  `json:"conversationId"`
	Id             int64                  `json:"id"`
	Input          map[string]interface{} `json:"input"`

	// Result 执行结果或错误信息
	Result    interface{}         `json:"result,omitempty"`
	Status    PendingActionStatus `json:"status"`
	ToolUseId string              `json:"toolUseId"`
}

// PendingActionStatus defines model for PendingAction.Status.
type PendingActionStatus string

// Tool defines model for Tool.
type Tool struct {
	Action string     `json:"action"`
	Effect ToolEffect `json:"effect"`

	// Name 给模型的工具名，. 换成 __
	Name string `json:"name"`

	// Title 中文名
	Title string `json:"title"`
}

// ToolEffect defines model for Tool.Effect.
type ToolEffect string

// ActionId defines model for ActionId.
type ActionId = int64

// ConversationId defines model for ConversationId.
type ConversationId = int64

// CreateAiConversationJSONBody defines parameters for CreateAiConversation.
type CreateAiConversationJSONBody struct {
	Title *string `json:"title,omitempty"`
}

// SendAiMessageJSONBody defines parameters for SendAiMessage.
type SendAiMessageJSONBody struct {
	// Context 用户发消息时所在的页面，写进这条消息的上下文
	Context *struct {
		// Path 例如 /projects/XC/12
		Path  *string `json:"path,omitempty"`
		Title *string `json:"title,omitempty"`
	} `json:"context,omitempty"`
	Text string `json:"text"`
}

// PutAiSettingsJSONBody defines parameters for PutAiSettings.
type PutAiSettingsJSONBody struct {
	ApiKey           *string `json:"apiKey,omitempty"`
	ConfirmAllWrites *bool   `json:"confirmAllWrites,omitempty"`
	Model            *string `json:"model,omitempty"`
}

// CreateAiConversationJSONRequestBody defines body for CreateAiConversation for application/json ContentType.
type CreateAiConversationJSONRequestBody CreateAiConversationJSONBody

// SendAiMessageJSONRequestBody defines body for SendAiMessage for application/json ContentType.
type SendAiMessageJSONRequestBody SendAiMessageJSONBody

// PutAiSettingsJSONRequestBody defines body for PutAiSettings for application/json ContentType.
type PutAiSettingsJSONRequestBody PutAiSettingsJSONBody

// Getter for additional properties for ContentBlock. Returns the specified
// element and whether it was found
func (a ContentBlock) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContentBlock
func (a *ContentBlock) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContentBlock to handle AdditionalProperties
func (a *ContentBlock) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["context"]; found {
		err = json.Unmarshal(raw, &a.Context)
		if err != nil {
			return fmt.Errorf("error reading 'context': %w", err)
		}
		delete(object, "context")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["input"]; found {
		err = json.Unmarshal(raw, &a.Input)
		if err != nil {
			return fmt.Errorf("error reading 'input': %w", err)
		}
		delete(object, "input")
	}

	if raw, found := object["is_error"]; found {
		err = json.Unmarshal(raw, &a.IsError)
		if err != nil {
			return fmt.Errorf("error reading 'is_error': %w", err)
		}
		delete(object, "is_error")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["tool_use_id"]; found {
		err = json.Unmarshal(raw, &a.ToolUseId)
		if err != nil {
			return fmt.Errorf("error reading 'tool_use_id': %w", err)
		}
		delete(object, "tool_use_id")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContentBlock to handle AdditionalProperties
func (a ContentBlock) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["content"], err = json.Marshal(a.Content)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'content': %w", err)
	}

	if a.Context != nil {
		object["context"], err = json.Marshal(a.Context)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'context': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Input != nil {
		object["input"], err = json.Marshal(a.Input)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'input': %w", err)
		}
	}

	if a.IsError != nil {
		object["is_error"], err = json.Marshal(a.IsError)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_error': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	if a.ToolUseId != nil {
		object["tool_use_id"], err = json.Marshal(a.ToolUseId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tool_use_id': %w", err)
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /ai/actions/{actionId}/approve)
	ApproveAiAction(w http.ResponseWriter, r *http.Request, actionId ActionId)

	// (POST /ai/actions/{actionId}/reject)
	RejectAiAction(w http.ResponseWriter, r *http.Request, actionId ActionId)

	// (GET /ai/conversations)
	ListAiConversations(w http.ResponseWriter, r *http.Request)

	// (POST /ai/conversations)
	CreateAiConversation(w http.ResponseWriter, r *http.Request)

	// (DELETE /ai/conversations/{conversationId})
	DeleteAiConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId)

	// (GET /ai/conversations/{conversationId})
	GetAiConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId)

	// (POST /ai/conversations/{conversationId}/messages)
	SendAiMessage(w http.ResponseWriter, r *http.Request, conversationId ConversationId)

	// (POST /ai/conversations/{conversationId}/stop)
	StopAiReply(w http.ResponseWriter, r *http.Request, conversationId ConversationId)

	// (GET /ai/settings)
	GetAiSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /ai/settings)
	PutAiSettings(w http.ResponseWriter, r *http.Request)

	// (GET /ai/tools)
	ListAiTools(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /ai/actions/{actionId}/approve)
func (_ Unimplemented) ApproveAiAction(w http.ResponseWriter, r *http.Request, actionId ActionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai/actions/{actionId}/reject)
func (_ Unimplemented) RejectAiAction(w http.ResponseWriter, r *http.Request, actionId ActionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai/conversations)
func (_ Unimplemented) ListAiConversations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai/conversations)
func (_ Unimplemented) CreateAiConversation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /ai/conversations/{conversationId})
func (_ Unimplemented) DeleteAiConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai/conversations/{conversationId})
func (_ Unimplemented) GetAiConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai/conversations/{conversationId}/messages)
func (_ Unimplemented) SendAiMessage(w http.ResponseWriter, r *http.Request, conversationId ConversationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ai/conversations/{conversationId}/stop)
func (_ Unimplemented) StopAiReply(w http.ResponseWriter, r *http.Request, conversationId ConversationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai/settings)
func (_ Unimplemented) GetAiSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /ai/settings)
func (_ Unimplemented) PutAiSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ai/tools)
func (_ Unimplemented) ListAiTools(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApproveAiAction operation middleware
func (siw *ServerInterfaceWrapper) ApproveAiAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "actionId" -------------
	var actionId ActionId

	err = runtime.BindStyledParameterWithOptions("simple", "actionId", chi.URLParam(r, "actionId"), &actionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveAiAction(w, r, actionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectAiAction operation middleware
func (siw *ServerInterfaceWrapper) RejectAiAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "actionId" -------------
	var actionId ActionId

	err = runtime.BindStyledParameterWithOptions("simple", "actionId", chi.URLParam(r, "actionId"), &actionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectAiAction(w, r, actionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAiConversations operation middleware
func (siw *ServerInterfaceWrapper) ListAiConversations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAiConversations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAiConversation operation middleware
func (siw *ServerInterfaceWrapper) CreateAiConversation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAiConversation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAiConversation operation middleware
func (siw *ServerInterfaceWrapper) DeleteAiConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAiConversation(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAiConversation operation middleware
func (siw *ServerInterfaceWrapper) GetAiConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAiConversation(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendAiMessage operation middleware
func (siw *ServerInterfaceWrapper) SendAiMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendAiMessage(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopAiReply operation middleware
func (siw *ServerInterfaceWrapper) StopAiReply(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopAiReply(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAiSettings operation middleware
func (siw *ServerInterfaceWrapper) GetAiSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAiSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAiSettings operation middleware
func (siw *ServerInterfaceWrapper) PutAiSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAiSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAiTools operation middleware
func (siw *ServerInterfaceWrapper) ListAiTools(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAiTools(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai/conversations", wrapper.ListAiConversations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai/conversations", wrapper.CreateAiConversation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/ai/conversations/{conversationId}", wrapper.DeleteAiConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai/conversations/{conversationId}", wrapper.GetAiConversation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai/conversations/{conversationId}/messages", wrapper.SendAiMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai/conversations/{conversationId}/stop", wrapper.StopAiReply)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai/actions/{actionId}/approve", wrapper.ApproveAiAction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ai/actions/{actionId}/reject", wrapper.RejectAiAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai/tools", wrapper.ListAiTools)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai/settings", wrapper.GetAiSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/ai/settings", wrapper.PutAiSettings)
	})

	return r
}
