// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HabitRemindWhen.
const (
	HabitRemindWhenActive HabitRemindWhen = "active"
	HabitRemindWhenAwake  HabitRemindWhen = "awake"
	HabitRemindWhenWindow HabitRemindWhen = "window"
	HabitRemindWhenWork   HabitRemindWhen = "work"
)

// Valid indicates whether the value is a known member of the HabitRemindWhen enum.
func (e HabitRemindWhen) Valid() bool {
	switch e {
	case HabitRemindWhenActive:
		return true
	case HabitRemindWhenAwake:
		return true
	case HabitRemindWhenWindow:
		return true
	case HabitRemindWhenWork:
		return true
	default:
		return false
	}
}

// Defines values for HabitTemplate.
const (
	HabitTemplateEyes     HabitTemplate = "eyes"
	HabitTemplateMedicine HabitTemplate = "medicine"
	HabitTemplateMove     HabitTemplate = "move"
	HabitTemplateWater    HabitTemplate = "water"
)

// Valid indicates whether the value is a known member of the HabitTemplate enum.
func (e HabitTemplate) Valid() bool {
	switch e {
	case HabitTemplateEyes:
		return true
	case HabitTemplateMedicine:
		return true
	case HabitTemplateMove:
		return true
	case HabitTemplateWater:
		return true
	default:
		return false
	}
}

// Defines values for HabitInputRemindWhen.
const (
	HabitInputRemindWhenActive HabitInputRemindWhen = "active"
	HabitInputRemindWhenAwake  HabitInputRemindWhen = "awake"
	HabitInputRemindWhenWindow HabitInputRemindWhen = "window"
	HabitInputRemindWhenWork   HabitInputRemindWhen = "work"
)

// Valid indicates whether the value is a known member of the HabitInputRemindWhen enum.
func (e HabitInputRemindWhen) Valid() bool {
	switch e {
	case HabitInputRemindWhenActive:
		return true
	case HabitInputRemindWhenAwake:
		return true
	case HabitInputRemindWhenWindow:
		return true
	case HabitInputRemindWhenWork:
		return true
	default:
		return false
	}
}

// Defines values for HabitInputTemplate.
const (
	HabitInputTemplateEyes     HabitInputTemplate = "eyes"
	HabitInputTemplateMedicine HabitInputTemplate = "medicine"
	HabitInputTemplateMove     HabitInputTemplate = "move"
	HabitInputTemplateWater    HabitInputTemplate = "water"
)

// Valid indicates whether the value is a known member of the HabitInputTemplate enum.
func (e HabitInputTemplate) Valid() bool {
	switch e {
	case HabitInputTemplateEyes:
		return true
	case HabitInputTemplateMedicine:
		return true
	case HabitInputTemplateMove:
		return true
	case HabitInputTemplateWater:
		return true
	default:
		return false
	}
}

// Defines values for HabitKind.
const (
	Count   HabitKind = "count"
	Workout HabitKind = "workout"
)

// Valid indicates whether the value is a known member of the HabitKind enum.
func (e HabitKind) Valid() bool {
	switch e {
	case Count:
		return true
	case Workout:
		return true
	default:
		return false
	}
}

// Defines values for HabitPatchRemindWhen.
const (
	HabitPatchRemindWhenActive HabitPatchRemindWhen = "active"
	HabitPatchRemindWhenAwake  HabitPatchRemindWhen = "awake"
	HabitPatchRemindWhenWindow HabitPatchRemindWhen = "window"
	HabitPatchRemindWhenWork   HabitPatchRemindWhen = "work"
)

// Valid indicates whether the value is a known member of the HabitPatchRemindWhen enum.
func (e HabitPatchRemindWhen) Valid() bool {
	switch e {
	case HabitPatchRemindWhenActive:
		return true
	case HabitPatchRemindWhenAwake:
		return true
	case HabitPatchRemindWhenWindow:
		return true
	case HabitPatchRemindWhenWork:
		return true
	default:
		return false
	}
}

// Defines values for HabitPatchTemplate.
const (
	HabitPatchTemplateEyes     HabitPatchTemplate = "eyes"
	HabitPatchTemplateMedicine HabitPatchTemplate = "medicine"
	HabitPatchTemplateMove     HabitPatchTemplate = "move"
	HabitPatchTemplateWater    HabitPatchTemplate = "water"
)

// Valid indicates whether the value is a known member of the HabitPatchTemplate enum.
func (e HabitPatchTemplate) Valid() bool {
	switch e {
	case HabitPatchTemplateEyes:
		return true
	case HabitPatchTemplateMedicine:
		return true
	case HabitPatchTemplateMove:
		return true
	case HabitPatchTemplateWater:
		return true
	default:
		return false
	}
}

// Defines values for HostPresenceState.
const (
	HostPresenceStateActive  HostPresenceState = "active"
	HostPresenceStateIdle    HostPresenceState = "idle"
	HostPresenceStateLocked  HostPresenceState = "locked"
	HostPresenceStateOffline HostPresenceState = "offline"
	HostPresenceStateUnknown HostPresenceState = "unknown"
)

// Valid indicates whether the value is a known member of the HostPresenceState enum.
func (e HostPresenceState) Valid() bool {
	switch e {
	case HostPresenceStateActive:
		return true
	case HostPresenceStateIdle:
		return true
	case HostPresenceStateLocked:
		return true
	case HostPresenceStateOffline:
		return true
	case HostPresenceStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for RemindMode.
const (
	Interval RemindMode = "interval"
	None     RemindMode = "none"
	Times    RemindMode = "times"
)

// Valid indicates whether the value is a known member of the RemindMode enum.
func (e RemindMode) Valid() bool {
	switch e {
	case Interval:
		return true
	case None:
		return true
	case Times:
		return true
	default:
		return false
	}
}

// Habit defines model for Habit.
type Habit struct {
	ActiveHostIds []string  `json:"activeHostIds"`
	Archived      bool      `json:"archived"`
	Color         string    `json:"color"`
	CreatedAt     time.Time `json:"createdAt"`
	DailyTarget   float64   `json:"dailyTarget"`

	// HaEntityId 这个 Home Assistant 实体状态变化时自动打卡一次
	HaEntityId string `json:"haEntityId"`
	Icon       string `json:"icon"`
	Id         int64  `json:"id"`

	// Kind count 普通打卡；workout 健身，记一次训练就算打卡一次
	Kind                  *HabitKind `json:"kind,omitempty"`
	Name                  string     `json:"name"`
	NextRemindAt          *time.Time `json:"nextRemindAt,omitempty"`
	RemindIntervalMinutes int        `json:"remindIntervalMinutes"`

	// RemindMode none 不提醒；interval 在时间窗内每隔一段时间提醒；times 在固定时间点提醒
	RemindMode   RemindMode        `json:"remindMode"`
	RemindOnHost bool              `json:"remindOnHost"`
	RemindTimes  []string          `json:"remindTimes"`
	RemindWhen   []HabitRemindWhen `json:"remindWhen"`

	// RemindWindow 形如 09:00-21:00
	RemindWindow string         `json:"remindWindow"`
	SortOrder    int            `json:"sortOrder"`
	Template     *HabitTemplate `json:"template,omitempty"`
	Unit         string         `json:"unit"`
}

// HabitRemindWhen defines model for Habit.RemindWhen.
type HabitRemindWhen string

// HabitTemplate defines model for Habit.Template.
type HabitTemplate string

// HabitDay defines model for HabitDay.
type HabitDay struct {
	Amount float64 `json:"amount"`

	// Date 用户时区的日期 YYYY-MM-DD
	Date    string `json:"date"`
	Reached bool   `json:"reached"`
}

// HabitInput defines model for HabitInput.
type HabitInput struct {
	ActiveHostIds *[]string `json:"activeHostIds,omitempty"`
	Color         *string   `json:"color,omitempty"`
	DailyTarget   *float64  `json:"dailyTarget,omitempty"`
	HaEntityId    *string   `json:"haEntityId,omitempty"`
	Icon          *string   `json:"icon,omitempty"`

	// Kind count 普通打卡；workout 健身，记一次训练就算打卡一次
	Kind                  *HabitKind `json:"kind,omitempty"`
	Name                  string     `json:"name"`
	RemindIntervalMinutes *int       `json:"remindIntervalMinutes,omitempty"`

	// RemindMode none 不提醒；interval 在时间窗内每隔一段时间提醒；times 在固定时间点提醒
	RemindMode   *RemindMode             `json:"remindMode,omitempty"`
	RemindOnHost *bool                   `json:"remindOnHost,omitempty"`
	RemindTimes  *[]string               `json:"remindTimes,omitempty"`
	RemindWhen   *[]HabitInputRemindWhen `json:"remindWhen,omitempty"`
	RemindWindow *string                 `json:"remindWindow,omitempty"`
	SortOrder    *int                    `json:"sortOrder,omitempty"`
	Template     *HabitInputTemplate     `json:"template,omitempty"`
	Unit         *string                 `json:"unit,omitempty"`
}

// HabitInputRemindWhen defines model for HabitInput.RemindWhen.
type HabitInputRemindWhen string

// HabitInputTemplate defines model for HabitInput.Template.
type HabitInputTemplate string

// HabitKind count 普通打卡；workout 健身，记一次训练就算打卡一次
type HabitKind string

// HabitLog defines model for HabitLog.
type HabitLog struct {
	Amount  float64   `json:"amount"`
	At      time.Time `json:"at"`
	HabitId int64     `json:"habitId"`
	Id      int64     `json:"id"`
	Note    string    `json:"note"`

	// Source web、telegram、webpush、ha、ai、automation、workout
	Source string `json:"source"`
}

// HabitPatch defines model for HabitPatch.
type HabitPatch struct {
	ActiveHostIds *[]string `json:"activeHostIds,omitempty"`
	Archived      *bool     `json:"archived,omitempty"`
	Color         *string   `json:"color,omitempty"`
	DailyTarget   *float64  `json:"dailyTarget,omitempty"`
	HaEntityId    *string   `json:"haEntityId,omitempty"`
	Icon          *string   `json:"icon,omitempty"`

	// Kind count 普通打卡；workout 健身，记一次训练就算打卡一次
	Kind                  *HabitKind `json:"kind,omitempty"`
	Name                  *string    `json:"name,omitempty"`
	RemindIntervalMinutes *int       `json:"remindIntervalMinutes,omitempty"`

	// RemindMode none 不提醒；interval 在时间窗内每隔一段时间提醒；times 在固定时间点提醒
	RemindMode   *RemindMode             `json:"remindMode,omitempty"`
	RemindOnHost *bool                   `json:"remindOnHost,omitempty"`
	RemindTimes  *[]string               `json:"remindTimes,omitempty"`
	RemindWhen   *[]HabitPatchRemindWhen `json:"remindWhen,omitempty"`
	RemindWindow *string                 `json:"remindWindow,omitempty"`
	SortOrder    *int                    `json:"sortOrder,omitempty"`
	Template     *HabitPatchTemplate     `json:"template,omitempty"`
	Unit         *string                 `json:"unit,omitempty"`
}

// HabitPatchRemindWhen defines model for HabitPatch.RemindWhen.
type HabitPatchRemindWhen string

// HabitPatchTemplate defines model for HabitPatch.Template.
type HabitPatchTemplate string

// HabitStats defines model for HabitStats.
type HabitStats struct {
	// BestStreak 统计范围内最长连续达标天数
	BestStreak  int        `json:"bestStreak"`
	Days        []HabitDay `json:"days"`
	HabitId     int64      `json:"habitId"`
	ReachedDays int        `json:"reachedDays"`
	Streak      int        `json:"streak"`
	Total       float64    `json:"total"`
}

// HabitToday defines model for HabitToday.
type HabitToday struct {
	// Done 今天累计
	Done  float64 `json:"done"`
	Habit Habit   `json:"habit"`

	// Logs 今天的打卡，新的在前
	Logs    []HabitLog `json:"logs"`
	Reached bool       `json:"reached"`

	// Streak 连续达标天数（含今天，如果今天已达标）
	Streak int `json:"streak"`
}

// HostPresence defines model for HostPresence.
type HostPresence struct {
	DisplayOff  *bool             `json:"displayOff,omitempty"`
	HostId      string            `json:"hostId"`
	IdleSeconds *int64            `json:"idleSeconds,omitempty"`
	Known       bool              `json:"known"`
	Locked      *bool             `json:"locked,omitempty"`
	Name        string            `json:"name"`
	Online      bool              `json:"online"`
	Since       time.Time         `json:"since"`
	State       HostPresenceState `json:"state"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

// HostPresenceState defines model for HostPresence.State.
type HostPresenceState string

// RemindMode none 不提醒；interval 在时间窗内每隔一段时间提醒；times 在固定时间点提醒
type RemindMode string

// Schedule defines model for Schedule.
type Schedule struct {
	IdleMinutes int     `json:"idleMinutes"`
	SleepTime   string  `json:"sleepTime"`
	Timezone    string  `json:"timezone"`
	WakeTime    string  `json:"wakeTime"`
	WorkDays    []int   `json:"workDays"`
	WorkEnd     *string `json:"workEnd,omitempty"`
	WorkStart   *string `json:"workStart,omitempty"`
}

// WorkoutItem defines model for WorkoutItem.
type WorkoutItem struct {
	Name string  `json:"name"`
	Note *string `json:"note,omitempty"`
	Reps *int    `json:"reps,omitempty"`
	Sets *int    `json:"sets,omitempty"`

	// Weight 公斤，0 表示自重
	Weight *float64 `json:"weight,omitempty"`
}

// WorkoutLog defines model for WorkoutLog.
type WorkoutLog struct {
	CreatedAt time.Time `json:"createdAt"`

	// Date YYYY-MM-DD
	Date            string        `json:"date"`
	DurationMinutes int           `json:"durationMinutes"`
	Id              int64         `json:"id"`
	Items           []WorkoutItem `json:"items"`
	Note            string        `json:"note"`
	PlanId          *int64        `json:"planId,omitempty"`
}

// WorkoutLogInput defines model for WorkoutLogInput.
type WorkoutLogInput struct {
	// Date YYYY-MM-DD，默认今天
	Date            *string        `json:"date,omitempty"`
	DurationMinutes *int           `json:"durationMinutes,omitempty"`
	Items           *[]WorkoutItem `json:"items,omitempty"`
	Note            *string        `json:"note,omitempty"`
	PlanId          *int64         `json:"planId,omitempty"`
}

// WorkoutPlan defines model for WorkoutPlan.
type WorkoutPlan struct {
	Id    *int64        `json:"id,omitempty"`
	Items []WorkoutItem `json:"items"`
	Title string        `json:"title"`

	// Weekday 1 是周一，7 是周日
	Weekday int `json:"weekday"`
}

// WorkoutSettings defines model for WorkoutSettings.
type WorkoutSettings struct {
	// NotifyEnabled 有计划的日子到点发通知
	NotifyEnabled bool   `json:"notifyEnabled"`
	NotifyTime    string `json:"notifyTime"`
}

// HabitId defines model for HabitId.
type HabitId = int64

// ListHabitsParams defines parameters for ListHabits.
type ListHabitsParams struct {
	// Archived true 时包含已归档的习惯
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`
}

// CheckinHabitJSONBody defines parameters for CheckinHabit.
type CheckinHabitJSONBody struct {
	// Amount 默认 1。可以是负数以外的任意值
	Amount *float64 `json:"amount,omitempty"`
	Note   *string  `json:"note,omitempty"`
}

// HabitStatsParams defines parameters for HabitStats.
type HabitStatsParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListWorkoutLogsParams defines parameters for ListWorkoutLogs.
type ListWorkoutLogsParams struct {
	// Days 最近多少天，默认 30
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ReplaceWorkoutPlansJSONBody defines parameters for ReplaceWorkoutPlans.
type ReplaceWorkoutPlansJSONBody = []WorkoutPlan

// CreateHabitJSONRequestBody defines body for CreateHabit for application/json ContentType.
type CreateHabitJSONRequestBody = HabitInput

// UpdateHabitScheduleJSONRequestBody defines body for UpdateHabitSchedule for application/json ContentType.
type UpdateHabitScheduleJSONRequestBody = Schedule

// UpdateHabitJSONRequestBody defines body for UpdateHabit for application/json ContentType.
type UpdateHabitJSONRequestBody = HabitPatch

// CheckinHabitJSONRequestBody defines body for CheckinHabit for application/json ContentType.
type CheckinHabitJSONRequestBody CheckinHabitJSONBody

// CreateWorkoutLogJSONRequestBody defines body for CreateWorkoutLog for application/json ContentType.
type CreateWorkoutLogJSONRequestBody = WorkoutLogInput

// ReplaceWorkoutPlansJSONRequestBody defines body for ReplaceWorkoutPlans for application/json ContentType.
type ReplaceWorkoutPlansJSONRequestBody = ReplaceWorkoutPlansJSONBody

// UpdateWorkoutSettingsJSONRequestBody defines body for UpdateWorkoutSettings for application/json ContentType.
type UpdateWorkoutSettingsJSONRequestBody = WorkoutSettings

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /habits)
	ListHabits(w http.ResponseWriter, r *http.Request, params ListHabitsParams)

	// (POST /habits)
	CreateHabit(w http.ResponseWriter, r *http.Request)

	// (DELETE /habits/logs/{logId})
	DeleteHabitLog(w http.ResponseWriter, r *http.Request, logId int64)

	// (GET /habits/presence)
	GetHabitPresence(w http.ResponseWriter, r *http.Request)

	// (GET /habits/schedule)
	GetHabitSchedule(w http.ResponseWriter, r *http.Request)

	// (PUT /habits/schedule)
	UpdateHabitSchedule(w http.ResponseWriter, r *http.Request)

	// (GET /habits/today)
	HabitsToday(w http.ResponseWriter, r *http.Request)

	// (DELETE /habits/{habitId})
	DeleteHabit(w http.ResponseWriter, r *http.Request, habitId HabitId)

	// (GET /habits/{habitId})
	GetHabit(w http.ResponseWriter, r *http.Request, habitId HabitId)

	// (PATCH /habits/{habitId})
	UpdateHabit(w http.ResponseWriter, r *http.Request, habitId HabitId)

	// (POST /habits/{habitId}/checkin)
	CheckinHabit(w http.ResponseWriter, r *http.Request, habitId HabitId)

	// (GET /habits/{habitId}/stats)
	HabitStats(w http.ResponseWriter, r *http.Request, habitId HabitId, params HabitStatsParams)

	// (GET /workouts/logs)
	ListWorkoutLogs(w http.ResponseWriter, r *http.Request, params ListWorkoutLogsParams)

	// (POST /workouts/logs)
	CreateWorkoutLog(w http.ResponseWriter, r *http.Request)

	// (DELETE /workouts/logs/{logId})
	DeleteWorkoutLog(w http.ResponseWriter, r *http.Request, logId int64)

	// (GET /workouts/plans)
	ListWorkoutPlans(w http.ResponseWriter, r *http.Request)

	// (PUT /workouts/plans)
	ReplaceWorkoutPlans(w http.ResponseWriter, r *http.Request)

	// (GET /workouts/settings)
	GetWorkoutSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /workouts/settings)
	UpdateWorkoutSettings(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /habits)
func (_ Unimplemented) ListHabits(w http.ResponseWriter, r *http.Request, params ListHabitsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /habits)
func (_ Unimplemented) CreateHabit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /habits/logs/{logId})
func (_ Unimplemented) DeleteHabitLog(w http.ResponseWriter, r *http.Request, logId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /habits/presence)
func (_ Unimplemented) GetHabitPresence(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /habits/schedule)
func (_ Unimplemented) GetHabitSchedule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /habits/schedule)
func (_ Unimplemented) UpdateHabitSchedule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /habits/today)
func (_ Unimplemented) HabitsToday(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /habits/{habitId})
func (_ Unimplemented) DeleteHabit(w http.ResponseWriter, r *http.Request, habitId HabitId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /habits/{habitId})
func (_ Unimplemented) GetHabit(w http.ResponseWriter, r *http.Request, habitId HabitId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /habits/{habitId})
func (_ Unimplemented) UpdateHabit(w http.ResponseWriter, r *http.Request, habitId HabitId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /habits/{habitId}/checkin)
func (_ Unimplemented) CheckinHabit(w http.ResponseWriter, r *http.Request, habitId HabitId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /habits/{habitId}/stats)
func (_ Unimplemented) HabitStats(w http.ResponseWriter, r *http.Request, habitId HabitId, params HabitStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /workouts/logs)
func (_ Unimplemented) ListWorkoutLogs(w http.ResponseWriter, r *http.Request, params ListWorkoutLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /workouts/logs)
func (_ Unimplemented) CreateWorkoutLog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /workouts/logs/{logId})
func (_ Unimplemented) DeleteWorkoutLog(w http.ResponseWriter, r *http.Request, logId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /workouts/plans)
func (_ Unimplemented) ListWorkoutPlans(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /workouts/plans)
func (_ Unimplemented) ReplaceWorkoutPlans(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /workouts/settings)
func (_ Unimplemented) GetWorkoutSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /workouts/settings)
func (_ Unimplemented) UpdateWorkoutSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListHabits operation middleware
func (siw *ServerInterfaceWrapper) ListHabits(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHabitsParams

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHabits(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHabit operation middleware
func (siw *ServerInterfaceWrapper) CreateHabit(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHabit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteHabitLog operation middleware
func (siw *ServerInterfaceWrapper) DeleteHabitLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "logId" -------------
	var logId int64

	err = runtime.BindStyledParameterWithOptions("simple", "logId", chi.URLParam(r, "logId"), &logId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "logId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteHabitLog(w, r, logId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHabitPresence operation middleware
func (siw *ServerInterfaceWrapper) GetHabitPresence(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHabitPresence(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHabitSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetHabitSchedule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHabitSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateHabitSchedule operation middleware
func (siw *ServerInterfaceWrapper) UpdateHabitSchedule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateHabitSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HabitsToday operation middleware
func (siw *ServerInterfaceWrapper) HabitsToday(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HabitsToday(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteHabit operation middleware
func (siw *ServerInterfaceWrapper) DeleteHabit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "habitId" -------------
	var habitId HabitId

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", chi.URLParam(r, "habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "habitId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteHabit(w, r, habitId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHabit operation middleware
func (siw *ServerInterfaceWrapper) GetHabit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "habitId" -------------
	var habitId HabitId

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", chi.URLParam(r, "habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "habitId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHabit(w, r, habitId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateHabit operation middleware
func (siw *ServerInterfaceWrapper) UpdateHabit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "habitId" -------------
	var habitId HabitId

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", chi.URLParam(r, "habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "habitId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateHabit(w, r, habitId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckinHabit operation middleware
func (siw *ServerInterfaceWrapper) CheckinHabit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "habitId" -------------
	var habitId HabitId

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", chi.URLParam(r, "habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "habitId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckinHabit(w, r, habitId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HabitStats operation middleware
func (siw *ServerInterfaceWrapper) HabitStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "habitId" -------------
	var habitId HabitId

	err = runtime.BindStyledParameterWithOptions("simple", "habitId", chi.URLParam(r, "habitId"), &habitId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "habitId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params HabitStatsParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", r.URL.Query(), &params.Days, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HabitStats(w, r, habitId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkoutLogs operation middleware
func (siw *ServerInterfaceWrapper) ListWorkoutLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkoutLogsParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", r.URL.Query(), &params.Days, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkoutLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkoutLog operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkoutLog(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkoutLog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorkoutLog operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkoutLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "logId" -------------
	var logId int64

	err = runtime.BindStyledParameterWithOptions("simple", "logId", chi.URLParam(r, "logId"), &logId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "logId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkoutLog(w, r, logId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkoutPlans operation middleware
func (siw *ServerInterfaceWrapper) ListWorkoutPlans(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkoutPlans(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceWorkoutPlans operation middleware
func (siw *ServerInterfaceWrapper) ReplaceWorkoutPlans(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceWorkoutPlans(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkoutSettings operation middleware
func (siw *ServerInterfaceWrapper) GetWorkoutSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkoutSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorkoutSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkoutSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorkoutSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/habits/schedule", wrapper.GetHabitSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/habits/schedule", wrapper.UpdateHabitSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/habits/presence", wrapper.GetHabitPresence)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/habits", wrapper.ListHabits)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/habits", wrapper.CreateHabit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/habits/today", wrapper.HabitsToday)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/habits/logs/{logId}", wrapper.DeleteHabitLog)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/habits/{habitId}", wrapper.DeleteHabit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/habits/{habitId}", wrapper.GetHabit)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/habits/{habitId}", wrapper.UpdateHabit)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/habits/{habitId}/checkin", wrapper.CheckinHabit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/habits/{habitId}/stats", wrapper.HabitStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workouts/plans", wrapper.ListWorkoutPlans)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/workouts/plans", wrapper.ReplaceWorkoutPlans)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workouts/logs", wrapper.ListWorkoutLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/workouts/logs", wrapper.CreateWorkoutLog)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/workouts/logs/{logId}", wrapper.DeleteWorkoutLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workouts/settings", wrapper.GetWorkoutSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/workouts/settings", wrapper.UpdateWorkoutSettings)
	})

	return r
}
