// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	externalRef0 "github.com/j0x3n/x-console/backend/internal/server/apigen/common"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MusicLyricsSource.
const (
	MusicLyricsSourceEmbedded MusicLyricsSource = "embedded"
	MusicLyricsSourceLrc      MusicLyricsSource = "lrc"
	MusicLyricsSourceNone     MusicLyricsSource = "none"
	MusicLyricsSourceOnline   MusicLyricsSource = "online"
)

// Valid indicates whether the value is a known member of the MusicLyricsSource enum.
func (e MusicLyricsSource) Valid() bool {
	switch e {
	case MusicLyricsSourceEmbedded:
		return true
	case MusicLyricsSourceLrc:
		return true
	case MusicLyricsSourceNone:
		return true
	case MusicLyricsSourceOnline:
		return true
	default:
		return false
	}
}

// Defines values for MusicTrackCoverSource.
const (
	MusicTrackCoverSourceEmbedded MusicTrackCoverSource = "embedded"
	MusicTrackCoverSourceFolder   MusicTrackCoverSource = "folder"
	MusicTrackCoverSourceNone     MusicTrackCoverSource = "none"
	MusicTrackCoverSourceOnline   MusicTrackCoverSource = "online"
)

// Valid indicates whether the value is a known member of the MusicTrackCoverSource enum.
func (e MusicTrackCoverSource) Valid() bool {
	switch e {
	case MusicTrackCoverSourceEmbedded:
		return true
	case MusicTrackCoverSourceFolder:
		return true
	case MusicTrackCoverSourceNone:
		return true
	case MusicTrackCoverSourceOnline:
		return true
	default:
		return false
	}
}

// Defines values for MusicTrackLyricsSource.
const (
	MusicTrackLyricsSourceEmbedded MusicTrackLyricsSource = "embedded"
	MusicTrackLyricsSourceLrc      MusicTrackLyricsSource = "lrc"
	MusicTrackLyricsSourceNone     MusicTrackLyricsSource = "none"
	MusicTrackLyricsSourceOnline   MusicTrackLyricsSource = "online"
)

// Valid indicates whether the value is a known member of the MusicTrackLyricsSource enum.
func (e MusicTrackLyricsSource) Valid() bool {
	switch e {
	case MusicTrackLyricsSourceEmbedded:
		return true
	case MusicTrackLyricsSourceLrc:
		return true
	case MusicTrackLyricsSourceNone:
		return true
	case MusicTrackLyricsSourceOnline:
		return true
	default:
		return false
	}
}

// Defines values for MusicTrackMatchState.
const (
	MusicTrackMatchStateFailed  MusicTrackMatchState = "failed"
	MusicTrackMatchStateMatched MusicTrackMatchState = "matched"
	MusicTrackMatchStateNone    MusicTrackMatchState = "none"
	MusicTrackMatchStatePending MusicTrackMatchState = "pending"
	MusicTrackMatchStateSkipped MusicTrackMatchState = "skipped"
)

// Valid indicates whether the value is a known member of the MusicTrackMatchState enum.
func (e MusicTrackMatchState) Valid() bool {
	switch e {
	case MusicTrackMatchStateFailed:
		return true
	case MusicTrackMatchStateMatched:
		return true
	case MusicTrackMatchStateNone:
		return true
	case MusicTrackMatchStatePending:
		return true
	case MusicTrackMatchStateSkipped:
		return true
	default:
		return false
	}
}

// Defines values for ListMusicTracksParamsSort.
const (
	Added  ListMusicTracksParamsSort = "added"
	Album  ListMusicTracksParamsSort = "album"
	Artist ListMusicTracksParamsSort = "artist"
	Plays  ListMusicTracksParamsSort = "plays"
	Recent ListMusicTracksParamsSort = "recent"
	Title  ListMusicTracksParamsSort = "title"
)

// Valid indicates whether the value is a known member of the ListMusicTracksParamsSort enum.
func (e ListMusicTracksParamsSort) Valid() bool {
	switch e {
	case Added:
		return true
	case Album:
		return true
	case Artist:
		return true
	case Plays:
		return true
	case Recent:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// Defines values for GetMusicTrackCoverParamsSize.
const (
	N256 GetMusicTrackCoverParamsSize = 256
	N640 GetMusicTrackCoverParamsSize = 640
	N96  GetMusicTrackCoverParamsSize = 96
)

// Valid indicates whether the value is a known member of the GetMusicTrackCoverParamsSize enum.
func (e GetMusicTrackCoverParamsSize) Valid() bool {
	switch e {
	case N256:
		return true
	case N640:
		return true
	case N96:
		return true
	default:
		return false
	}
}

// MusicAlbum defines model for MusicAlbum.
type MusicAlbum struct {
	Album       string `json:"album"`
	AlbumArtist string `json:"albumArtist"`

	// CoverTrackId 用它的封面做专辑封面，没有封面时为 0
	CoverTrackId int64 `json:"coverTrackId"`
	DurationMs   int   `json:"durationMs"`
	TrackCount   int   `json:"trackCount"`
	Year         int   `json:"year"`
}

// MusicArtist defines model for MusicArtist.
type MusicArtist struct {
	AlbumCount   int    `json:"albumCount"`
	Artist       string `json:"artist"`
	CoverTrackId int64  `json:"coverTrackId"`
	TrackCount   int    `json:"trackCount"`
}

// MusicFolder defines model for MusicFolder.
type MusicFolder struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
}

// MusicLyricLine defines model for MusicLyricLine.
type MusicLyricLine struct {
	Text string `json:"text"`

	// TimeMs 没有时间轴时没有这个字段
	TimeMs *int `json:"timeMs,omitempty"`
}

// MusicLyrics defines model for MusicLyrics.
type MusicLyrics struct {
	Lines  []MusicLyricLine  `json:"lines"`
	Source MusicLyricsSource `json:"source"`
	Synced bool              `json:"synced"`
}

// MusicLyricsSource defines model for MusicLyrics.Source.
type MusicLyricsSource string

// MusicPlaylist defines model for MusicPlaylist.
type MusicPlaylist struct {
	// CoverTrackIds 前 4 首有封面的歌，用来拼封面
	CoverTrackIds []int64   `json:"coverTrackIds"`
	CreatedAt     time.Time `json:"createdAt"`
	DurationMs    int       `json:"durationMs"`
	Id            int64     `json:"id"`
	Name          string    `json:"name"`
	TrackCount    int       `json:"trackCount"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// MusicPlaylistCreate defines model for MusicPlaylistCreate.
type MusicPlaylistCreate struct {
	Name     string   `json:"name"`
	TrackIds *[]int64 `json:"trackIds,omitempty"`
}

// MusicPlaylistDetail defines model for MusicPlaylistDetail.
type MusicPlaylistDetail struct {
	// CoverTrackIds 前 4 首有封面的歌，用来拼封面
	CoverTrackIds []int64      `json:"coverTrackIds"`
	CreatedAt     time.Time    `json:"createdAt"`
	DurationMs    int          `json:"durationMs"`
	Id            int64        `json:"id"`
	Name          string       `json:"name"`
	TrackCount    int          `json:"trackCount"`
	Tracks        []MusicTrack `json:"tracks"`
	UpdatedAt     time.Time    `json:"updatedAt"`
}

// MusicScanStatus defines model for MusicScanStatus.
type MusicScanStatus struct {
	Running bool `json:"running"`
}

// MusicSettings defines model for MusicSettings.
type MusicSettings struct {
	// Folders 音乐目录。里面已经不存在的目录不会列出
	Folders []MusicFolder `json:"folders"`
}

// MusicSettingsInput defines model for MusicSettingsInput.
type MusicSettingsInput struct {
	// Folders 云盘文件夹编号，最多 20 个。一个目录在另一个目录里时只保留外层的
	Folders []int64 `json:"folders"`
}

// MusicTrack defines model for MusicTrack.
type MusicTrack struct {
	Album       string `json:"album"`
	AlbumArtist string `json:"albumArtist"`

	// Artist 没有时为空字符串，界面显示“未知歌手”
	Artist string `json:"artist"`

	// Bitrate 单位 kbps
	Bitrate     int                   `json:"bitrate"`
	CoverSource MusicTrackCoverSource `json:"coverSource"`
	CreatedAt   time.Time             `json:"createdAt"`
	DiscNo      int                   `json:"discNo"`

	// DriveItemId 云盘里的文件编号
	DriveItemId int64 `json:"driveItemId"`
	DurationMs  int   `json:"durationMs"`
	Favorite    bool  `json:"favorite"`

	// Format 小写扩展名，例如 mp3、flac
	Format       string                 `json:"format"`
	HasCover     bool                   `json:"hasCover"`
	Id           int64                  `json:"id"`
	LastPlayedAt *time.Time             `json:"lastPlayedAt,omitempty"`
	LyricsSource MusicTrackLyricsSource `json:"lyricsSource"`

	// LyricsSynced 歌词带时间轴
	LyricsSynced bool `json:"lyricsSynced"`

	// MatchState 在线匹配的状态，B148 起使用
	MatchState MusicTrackMatchState `json:"matchState"`
	PlayCount  int                  `json:"playCount"`
	Title      string               `json:"title"`

	// TrackNo 没有时为 0
	TrackNo   int       `json:"trackNo"`
	UpdatedAt time.Time `json:"updatedAt"`
	Year      int       `json:"year"`
}

// MusicTrackCoverSource defines model for MusicTrack.CoverSource.
type MusicTrackCoverSource string

// MusicTrackLyricsSource defines model for MusicTrack.LyricsSource.
type MusicTrackLyricsSource string

// MusicTrackMatchState 在线匹配的状态，B148 起使用
type MusicTrackMatchState string

// MusicTrackIds defines model for MusicTrackIds.
type MusicTrackIds struct {
	TrackIds []int64 `json:"trackIds"`
}

// MusicTrackPage defines model for MusicTrackPage.
type MusicTrackPage struct {
	Items []MusicTrack `json:"items"`

	// NextCursor 没有下一页时没有这个字段
	NextCursor *string `json:"nextCursor,omitempty"`

	// Total 符合条件的总数
	Total int `json:"total"`
}

// MusicTrackPatch defines model for MusicTrackPatch.
type MusicTrackPatch struct {
	Album       *string `json:"album,omitempty"`
	AlbumArtist *string `json:"albumArtist,omitempty"`
	Artist      *string `json:"artist,omitempty"`
	Favorite    *bool   `json:"favorite,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// PlaylistId defines model for PlaylistId.
type PlaylistId = int64

// TrackId defines model for TrackId.
type TrackId = int64

// UpdateMusicPlaylistJSONBody defines parameters for UpdateMusicPlaylist.
type UpdateMusicPlaylistJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// ListMusicTracksParams defines parameters for ListMusicTracks.
type ListMusicTracksParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Artist 歌手名，要完全相同
	Artist *string `form:"artist,omitempty" json:"artist,omitempty"`

	// Album 专辑名，要完全相同
	Album    *string `form:"album,omitempty" json:"album,omitempty"`
	Favorite *bool   `form:"favorite,omitempty" json:"favorite,omitempty"`

	// DriveItemId 云盘里的文件编号。云盘页点音频文件时用它找对应的歌
	DriveItemId *int64 `form:"driveItemId,omitempty" json:"driveItemId,omitempty"`

	// Sort 默认 artist（歌手、专辑、碟号、曲目号、歌名）。recent 只列播放过的，最近的在前
	Sort   *ListMusicTracksParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
	Limit  *int                       `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *externalRef0.Cursor       `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListMusicTracksParamsSort defines parameters for ListMusicTracks.
type ListMusicTracksParamsSort string

// GetMusicTrackCoverParams defines parameters for GetMusicTrackCover.
type GetMusicTrackCoverParams struct {
	// Size 最长边像素，默认 256。原图比它小时不放大
	Size *GetMusicTrackCoverParamsSize `form:"size,omitempty" json:"size,omitempty"`
}

// GetMusicTrackCoverParamsSize defines parameters for GetMusicTrackCover.
type GetMusicTrackCoverParamsSize int

// ReportMusicPlayedJSONBody defines parameters for ReportMusicPlayed.
type ReportMusicPlayedJSONBody struct {
	// Seconds 这次听了多少秒
	Seconds int `json:"seconds"`
}

// CreateMusicPlaylistJSONRequestBody defines body for CreateMusicPlaylist for application/json ContentType.
type CreateMusicPlaylistJSONRequestBody = MusicPlaylistCreate

// UpdateMusicPlaylistJSONRequestBody defines body for UpdateMusicPlaylist for application/json ContentType.
type UpdateMusicPlaylistJSONRequestBody UpdateMusicPlaylistJSONBody

// AddMusicPlaylistItemsJSONRequestBody defines body for AddMusicPlaylistItems for application/json ContentType.
type AddMusicPlaylistItemsJSONRequestBody = MusicTrackIds

// SetMusicPlaylistItemsJSONRequestBody defines body for SetMusicPlaylistItems for application/json ContentType.
type SetMusicPlaylistItemsJSONRequestBody = MusicTrackIds

// PutMusicSettingsJSONRequestBody defines body for PutMusicSettings for application/json ContentType.
type PutMusicSettingsJSONRequestBody = MusicSettingsInput

// UpdateMusicTrackJSONRequestBody defines body for UpdateMusicTrack for application/json ContentType.
type UpdateMusicTrackJSONRequestBody = MusicTrackPatch

// ReportMusicPlayedJSONRequestBody defines body for ReportMusicPlayed for application/json ContentType.
type ReportMusicPlayedJSONRequestBody ReportMusicPlayedJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /music/albums)
	ListMusicAlbums(w http.ResponseWriter, r *http.Request)

	// (GET /music/artists)
	ListMusicArtists(w http.ResponseWriter, r *http.Request)

	// (GET /music/playlists)
	ListMusicPlaylists(w http.ResponseWriter, r *http.Request)

	// (POST /music/playlists)
	CreateMusicPlaylist(w http.ResponseWriter, r *http.Request)

	// (DELETE /music/playlists/{playlistId})
	DeleteMusicPlaylist(w http.ResponseWriter, r *http.Request, playlistId PlaylistId)

	// (GET /music/playlists/{playlistId})
	GetMusicPlaylist(w http.ResponseWriter, r *http.Request, playlistId PlaylistId)

	// (PATCH /music/playlists/{playlistId})
	UpdateMusicPlaylist(w http.ResponseWriter, r *http.Request, playlistId PlaylistId)

	// (POST /music/playlists/{playlistId}/items)
	AddMusicPlaylistItems(w http.ResponseWriter, r *http.Request, playlistId PlaylistId)

	// (PUT /music/playlists/{playlistId}/items)
	SetMusicPlaylistItems(w http.ResponseWriter, r *http.Request, playlistId PlaylistId)

	// (POST /music/scan)
	ScanMusic(w http.ResponseWriter, r *http.Request)

	// (GET /music/settings)
	GetMusicSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /music/settings)
	PutMusicSettings(w http.ResponseWriter, r *http.Request)

	// (GET /music/tracks)
	ListMusicTracks(w http.ResponseWriter, r *http.Request, params ListMusicTracksParams)

	// (GET /music/tracks/{trackId})
	GetMusicTrack(w http.ResponseWriter, r *http.Request, trackId TrackId)

	// (PATCH /music/tracks/{trackId})
	UpdateMusicTrack(w http.ResponseWriter, r *http.Request, trackId TrackId)

	// (GET /music/tracks/{trackId}/cover)
	GetMusicTrackCover(w http.ResponseWriter, r *http.Request, trackId TrackId, params GetMusicTrackCoverParams)

	// (GET /music/tracks/{trackId}/lyrics)
	GetMusicTrackLyrics(w http.ResponseWriter, r *http.Request, trackId TrackId)

	// (POST /music/tracks/{trackId}/played)
	ReportMusicPlayed(w http.ResponseWriter, r *http.Request, trackId TrackId)

	// (GET /music/tracks/{trackId}/stream)
	StreamMusicTrack(w http.ResponseWriter, r *http.Request, trackId TrackId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /music/albums)
func (_ Unimplemented) ListMusicAlbums(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/artists)
func (_ Unimplemented) ListMusicArtists(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/playlists)
func (_ Unimplemented) ListMusicPlaylists(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /music/playlists)
func (_ Unimplemented) CreateMusicPlaylist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /music/playlists/{playlistId})
func (_ Unimplemented) DeleteMusicPlaylist(w http.ResponseWriter, r *http.Request, playlistId PlaylistId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/playlists/{playlistId})
func (_ Unimplemented) GetMusicPlaylist(w http.ResponseWriter, r *http.Request, playlistId PlaylistId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /music/playlists/{playlistId})
func (_ Unimplemented) UpdateMusicPlaylist(w http.ResponseWriter, r *http.Request, playlistId PlaylistId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /music/playlists/{playlistId}/items)
func (_ Unimplemented) AddMusicPlaylistItems(w http.ResponseWriter, r *http.Request, playlistId PlaylistId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /music/playlists/{playlistId}/items)
func (_ Unimplemented) SetMusicPlaylistItems(w http.ResponseWriter, r *http.Request, playlistId PlaylistId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /music/scan)
func (_ Unimplemented) ScanMusic(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/settings)
func (_ Unimplemented) GetMusicSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /music/settings)
func (_ Unimplemented) PutMusicSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/tracks)
func (_ Unimplemented) ListMusicTracks(w http.ResponseWriter, r *http.Request, params ListMusicTracksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/tracks/{trackId})
func (_ Unimplemented) GetMusicTrack(w http.ResponseWriter, r *http.Request, trackId TrackId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /music/tracks/{trackId})
func (_ Unimplemented) UpdateMusicTrack(w http.ResponseWriter, r *http.Request, trackId TrackId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/tracks/{trackId}/cover)
func (_ Unimplemented) GetMusicTrackCover(w http.ResponseWriter, r *http.Request, trackId TrackId, params GetMusicTrackCoverParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/tracks/{trackId}/lyrics)
func (_ Unimplemented) GetMusicTrackLyrics(w http.ResponseWriter, r *http.Request, trackId TrackId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /music/tracks/{trackId}/played)
func (_ Unimplemented) ReportMusicPlayed(w http.ResponseWriter, r *http.Request, trackId TrackId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /music/tracks/{trackId}/stream)
func (_ Unimplemented) StreamMusicTrack(w http.ResponseWriter, r *http.Request, trackId TrackId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListMusicAlbums operation middleware
func (siw *ServerInterfaceWrapper) ListMusicAlbums(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMusicAlbums(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMusicArtists operation middleware
func (siw *ServerInterfaceWrapper) ListMusicArtists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMusicArtists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMusicPlaylists operation middleware
func (siw *ServerInterfaceWrapper) ListMusicPlaylists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMusicPlaylists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMusicPlaylist operation middleware
func (siw *ServerInterfaceWrapper) CreateMusicPlaylist(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMusicPlaylist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMusicPlaylist operation middleware
func (siw *ServerInterfaceWrapper) DeleteMusicPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMusicPlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusicPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetMusicPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusicPlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMusicPlaylist operation middleware
func (siw *ServerInterfaceWrapper) UpdateMusicPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMusicPlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddMusicPlaylistItems operation middleware
func (siw *ServerInterfaceWrapper) AddMusicPlaylistItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddMusicPlaylistItems(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetMusicPlaylistItems operation middleware
func (siw *ServerInterfaceWrapper) SetMusicPlaylistItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetMusicPlaylistItems(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScanMusic operation middleware
func (siw *ServerInterfaceWrapper) ScanMusic(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScanMusic(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusicSettings operation middleware
func (siw *ServerInterfaceWrapper) GetMusicSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusicSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMusicSettings operation middleware
func (siw *ServerInterfaceWrapper) PutMusicSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMusicSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMusicTracks operation middleware
func (siw *ServerInterfaceWrapper) ListMusicTracks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMusicTracksParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "artist", r.URL.Query(), &params.Artist, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "artist"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artist", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "album" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "album", r.URL.Query(), &params.Album, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "album"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "album", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "favorite" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "favorite", r.URL.Query(), &params.Favorite, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "favorite"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "favorite", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "driveItemId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "driveItemId", r.URL.Query(), &params.DriveItemId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "driveItemId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "driveItemId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMusicTracks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusicTrack operation middleware
func (siw *ServerInterfaceWrapper) GetMusicTrack(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusicTrack(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMusicTrack operation middleware
func (siw *ServerInterfaceWrapper) UpdateMusicTrack(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMusicTrack(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusicTrackCover operation middleware
func (siw *ServerInterfaceWrapper) GetMusicTrackCover(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMusicTrackCoverParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusicTrackCover(w, r, trackId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusicTrackLyrics operation middleware
func (siw *ServerInterfaceWrapper) GetMusicTrackLyrics(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusicTrackLyrics(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportMusicPlayed operation middleware
func (siw *ServerInterfaceWrapper) ReportMusicPlayed(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportMusicPlayed(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamMusicTrack operation middleware
func (siw *ServerInterfaceWrapper) StreamMusicTrack(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamMusicTrack(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/tracks", wrapper.ListMusicTracks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/tracks/{trackId}", wrapper.GetMusicTrack)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/music/tracks/{trackId}", wrapper.UpdateMusicTrack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/tracks/{trackId}/stream", wrapper.StreamMusicTrack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/tracks/{trackId}/cover", wrapper.GetMusicTrackCover)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/tracks/{trackId}/lyrics", wrapper.GetMusicTrackLyrics)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/music/tracks/{trackId}/played", wrapper.ReportMusicPlayed)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/albums", wrapper.ListMusicAlbums)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/artists", wrapper.ListMusicArtists)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/playlists", wrapper.ListMusicPlaylists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/music/playlists", wrapper.CreateMusicPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/music/playlists/{playlistId}", wrapper.DeleteMusicPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/playlists/{playlistId}", wrapper.GetMusicPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/music/playlists/{playlistId}", wrapper.UpdateMusicPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/music/playlists/{playlistId}/items", wrapper.AddMusicPlaylistItems)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/music/playlists/{playlistId}/items", wrapper.SetMusicPlaylistItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/music/settings", wrapper.GetMusicSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/music/settings", wrapper.PutMusicSettings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/music/scan", wrapper.ScanMusic)
	})

	return r
}
