// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HAMode.
const (
	Agent  HAMode = "agent"
	Direct HAMode = "direct"
)

// Valid indicates whether the value is a known member of the HAMode enum.
func (e HAMode) Valid() bool {
	switch e {
	case Agent:
		return true
	case Direct:
		return true
	default:
		return false
	}
}

// HAConfig defines model for HAConfig.
type HAConfig struct {
	// AgentId mode 为 agent 时使用的代理 id
	AgentId  string `json:"agentId"`
	HasToken bool   `json:"hasToken"`

	// Mode direct 表示服务端直接访问 HA；agent 表示通过家里的代理转发
	Mode HAMode `json:"mode"`

	// Token 打码后的令牌，例如 ••••••••x9Qa
	Token string `json:"token"`

	// Url 例如 http://homeassistant.local:8123，空表示未配置
	Url string `json:"url"`
}

// HAConfigInput defines model for HAConfigInput.
type HAConfigInput struct {
	AgentId *string `json:"agentId,omitempty"`

	// Mode direct 表示服务端直接访问 HA；agent 表示通过家里的代理转发
	Mode HAMode `json:"mode"`

	// Token 留空表示保留原令牌
	Token *string `json:"token,omitempty"`
	Url   string  `json:"url"`
}

// HAFavorite defines model for HAFavorite.
type HAFavorite struct {
	Alias     string   `json:"alias"`
	EntityId  string   `json:"entityId"`
	SortOrder int      `json:"sortOrder"`
	State     *HAState `json:"state,omitempty"`
}

// HAFavoriteInput defines model for HAFavoriteInput.
type HAFavoriteInput struct {
	Alias    *string `json:"alias,omitempty"`
	EntityId string  `json:"entityId"`
}

// HAMode direct 表示服务端直接访问 HA；agent 表示通过家里的代理转发
type HAMode string

// HAServiceCall defines model for HAServiceCall.
type HAServiceCall struct {
	// Data service_data
	Data *map[string]interface{} `json:"data,omitempty"`

	// EntityId 目标实体，会放进 target.entity_id
	EntityId *string `json:"entityId,omitempty"`
}

// HAState defines model for HAState.
type HAState struct {
	Attributes  map[string]interface{} `json:"attributes"`
	EntityId    string                 `json:"entityId"`
	LastChanged time.Time              `json:"lastChanged"`
	State       string                 `json:"state"`
}

// HAStatus defines model for HAStatus.
type HAStatus struct {
	Configured  bool       `json:"configured"`
	Connected   bool       `json:"connected"`
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	EntityCount int        `json:"entityCount"`

	// Error 最近一次连接失败的原因
	Error *string `json:"error,omitempty"`

	// Mode direct 表示服务端直接访问 HA；agent 表示通过家里的代理转发
	Mode HAMode `json:"mode"`

	// Version HA 版本
	Version *string `json:"version,omitempty"`
}

// HATestResult defines model for HATestResult.
type HATestResult struct {
	LocationName *string `json:"locationName,omitempty"`

	// Message 失败原因，给人看
	Message *string `json:"message,omitempty"`
	Ok      bool    `json:"ok"`
	Version *string `json:"version,omitempty"`
}

// PutHAFavoritesJSONBody defines parameters for PutHAFavorites.
type PutHAFavoritesJSONBody struct {
	Items []HAFavoriteInput `json:"items"`
}

// ListHAStatesParams defines parameters for ListHAStates.
type ListHAStatesParams struct {
	// Domain 只看某个域，例如 light
	Domain *string `form:"domain,omitempty" json:"domain,omitempty"`

	// Q 按 entityId 或名称模糊搜索
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PutHAConfigJSONRequestBody defines body for PutHAConfig for application/json ContentType.
type PutHAConfigJSONRequestBody = HAConfigInput

// PutHAFavoritesJSONRequestBody defines body for PutHAFavorites for application/json ContentType.
type PutHAFavoritesJSONRequestBody PutHAFavoritesJSONBody

// CallHAServiceJSONRequestBody defines body for CallHAService for application/json ContentType.
type CallHAServiceJSONRequestBody = HAServiceCall

// TestHAJSONRequestBody defines body for TestHA for application/json ContentType.
type TestHAJSONRequestBody = HAConfigInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /ha/config)
	GetHAConfig(w http.ResponseWriter, r *http.Request)

	// (PUT /ha/config)
	PutHAConfig(w http.ResponseWriter, r *http.Request)

	// (GET /ha/favorites)
	ListHAFavorites(w http.ResponseWriter, r *http.Request)

	// (PUT /ha/favorites)
	PutHAFavorites(w http.ResponseWriter, r *http.Request)

	// (POST /ha/services/{domain}/{service})
	CallHAService(w http.ResponseWriter, r *http.Request, domain string, service string)

	// (GET /ha/states)
	ListHAStates(w http.ResponseWriter, r *http.Request, params ListHAStatesParams)

	// (GET /ha/states/{entityId})
	GetHAState(w http.ResponseWriter, r *http.Request, entityId string)

	// (GET /ha/status)
	GetHAStatus(w http.ResponseWriter, r *http.Request)

	// (POST /ha/test)
	TestHA(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /ha/config)
func (_ Unimplemented) GetHAConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /ha/config)
func (_ Unimplemented) PutHAConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ha/favorites)
func (_ Unimplemented) ListHAFavorites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /ha/favorites)
func (_ Unimplemented) PutHAFavorites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ha/services/{domain}/{service})
func (_ Unimplemented) CallHAService(w http.ResponseWriter, r *http.Request, domain string, service string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ha/states)
func (_ Unimplemented) ListHAStates(w http.ResponseWriter, r *http.Request, params ListHAStatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ha/states/{entityId})
func (_ Unimplemented) GetHAState(w http.ResponseWriter, r *http.Request, entityId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ha/status)
func (_ Unimplemented) GetHAStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ha/test)
func (_ Unimplemented) TestHA(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHAConfig operation middleware
func (siw *ServerInterfaceWrapper) GetHAConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHAConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutHAConfig operation middleware
func (siw *ServerInterfaceWrapper) PutHAConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutHAConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHAFavorites operation middleware
func (siw *ServerInterfaceWrapper) ListHAFavorites(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHAFavorites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutHAFavorites operation middleware
func (siw *ServerInterfaceWrapper) PutHAFavorites(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutHAFavorites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CallHAService operation middleware
func (siw *ServerInterfaceWrapper) CallHAService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "domain" -------------
	var domain string

	err = runtime.BindStyledParameterWithOptions("simple", "domain", chi.URLParam(r, "domain"), &domain, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	// ------------- Path parameter "service" -------------
	var service string

	err = runtime.BindStyledParameterWithOptions("simple", "service", chi.URLParam(r, "service"), &service, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CallHAService(w, r, domain, service)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHAStates operation middleware
func (siw *ServerInterfaceWrapper) ListHAStates(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHAStatesParams

	// ------------- Optional query parameter "domain" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "domain", r.URL.Query(), &params.Domain, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "domain"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHAStates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHAState operation middleware
func (siw *ServerInterfaceWrapper) GetHAState(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entityId" -------------
	var entityId string

	err = runtime.BindStyledParameterWithOptions("simple", "entityId", chi.URLParam(r, "entityId"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHAState(w, r, entityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHAStatus operation middleware
func (siw *ServerInterfaceWrapper) GetHAStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHAStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestHA operation middleware
func (siw *ServerInterfaceWrapper) TestHA(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestHA(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ha/config", wrapper.GetHAConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/ha/config", wrapper.PutHAConfig)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ha/test", wrapper.TestHA)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ha/status", wrapper.GetHAStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ha/states", wrapper.ListHAStates)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ha/states/{entityId}", wrapper.GetHAState)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ha/services/{domain}/{service}", wrapper.CallHAService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ha/favorites", wrapper.ListHAFavorites)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/ha/favorites", wrapper.PutHAFavorites)
	})

	return r
}
