// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const confirmPendingTOTP = `-- name: ConfirmPendingTOTP :execrows
UPDATE users SET totp_enabled = 1, totp_secret = ? WHERE id = ? AND setup_completed = 1 AND totp_enabled = 0
`

type ConfirmPendingTOTPParams struct {
	TotpSecret string
	ID         int64
}

func (q *Queries) ConfirmPendingTOTP(ctx context.Context, arg ConfirmPendingTOTPParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, confirmPendingTOTP, arg.TotpSecret, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, kind, os, arch, hostname, version, capabilities, token_hash, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	ID           string
	Name         string
	Kind         string
	Os           string
	Arch         string
	Hostname     string
	Version      string
	Capabilities string
	TokenHash    string
	CreatedAt    time.Time
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Os,
		arg.Arch,
		arg.Hostname,
		arg.Version,
		arg.Capabilities,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const createPairingCode = `-- name: CreatePairingCode :exec
INSERT INTO pairing_codes (code_hash, name, kind, expires_at) VALUES (?, ?, ?, ?)
`

type CreatePairingCodeParams struct {
	CodeHash  string
	Name      string
	Kind      string
	ExpiresAt time.Time
}

func (q *Queries) CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) error {
	_, err := q.db.ExecContext(ctx, createPairingCode,
		arg.CodeHash,
		arg.Name,
		arg.Kind,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, created_at, expires_at, user_agent, ip)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
	UserAgent string
	Ip        string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, totp_secret, created_at, setup_completed)
VALUES (?, ?, ?, ?, 0)
RETURNING id, username, password_hash, totp_secret, totp_enabled, created_at, setup_completed
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	TotpSecret   string
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.TotpSecret,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.SetupCompleted,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications WHERE id = ?
`

func (q *Queries) DeleteNotification(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotification, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = ? AND id <> ?
`

type DeleteOtherSessionsParams struct {
	UserID int64
	ID     string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSessions, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_enabled = 0, totp_secret = '' WHERE id = ?
`

func (q *Queries) DisableTOTP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableTOTP, id)
	return err
}

const elevateSession = `-- name: ElevateSession :exec
UPDATE sessions SET elevated_until = ? WHERE id = ?
`

type ElevateSessionParams struct {
	ElevatedUntil *time.Time
	ID            string
}

func (q *Queries) ElevateSession(ctx context.Context, arg ElevateSessionParams) error {
	_, err := q.db.ExecContext(ctx, elevateSession, arg.ElevatedUntil, arg.ID)
	return err
}

const enableTOTP = `-- name: EnableTOTP :execrows
UPDATE users SET totp_enabled = 1, setup_completed = 1 WHERE id = ? AND setup_completed = 0 AND totp_enabled = 0 AND totp_secret <> ''
`

func (q *Queries) EnableTOTP(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, enableTOTP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishSetupWithoutTOTP = `-- name: FinishSetupWithoutTOTP :execrows
UPDATE users SET totp_secret = '', setup_completed = 1 WHERE id = ? AND setup_completed = 0 AND totp_enabled = 0
`

func (q *Queries) FinishSetupWithoutTOTP(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishSetupWithoutTOTP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, kind, os, arch, hostname, version, capabilities, token_hash, created_at, last_seen_at, revoked_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Os,
		&i.Arch,
		&i.Hostname,
		&i.Version,
		&i.Capabilities,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAgentByTokenHash = `-- name: GetAgentByTokenHash :one
SELECT id, name, kind, os, arch, hostname, version, capabilities, token_hash, created_at, last_seen_at, revoked_at FROM agents WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetAgentByTokenHash(ctx context.Context, tokenHash string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByTokenHash, tokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Os,
		&i.Arch,
		&i.Hostname,
		&i.Version,
		&i.Capabilities,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getFirstUser = `-- name: GetFirstUser :one
SELECT id, username, password_hash, totp_secret, totp_enabled, created_at, setup_completed FROM users ORDER BY id LIMIT 1
`

func (q *Queries) GetFirstUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getFirstUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.SetupCompleted,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT sessions.id, sessions.user_id, sessions.created_at, sessions.expires_at, sessions.elevated_until, sessions.user_agent, sessions.ip, users.username
FROM sessions JOIN users ON users.id = sessions.user_id
WHERE sessions.id = ? AND sessions.expires_at > ?
`

type GetSessionParams struct {
	ID        string
	ExpiresAt time.Time
}

type GetSessionRow struct {
	ID            string
	UserID        int64
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ElevatedUntil *time.Time
	UserAgent     string
	Ip            string
	Username      string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.ExpiresAt)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ElevatedUntil,
		&i.UserAgent,
		&i.Ip,
		&i.Username,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT "key", value, encrypted, updated_at FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Encrypted,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, totp_secret, totp_enabled, created_at, setup_completed FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.SetupCompleted,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, totp_secret, totp_enabled, created_at, setup_completed FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.SetupCompleted,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (at, actor, action, target, detail, result)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAuditParams struct {
	At     time.Time
	Actor  string
	Action string
	Target string
	Detail string
	Result string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.At,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Detail,
		arg.Result,
	)
	return err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (created_at, kind, title, body, link, priority, source, data)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, kind, title, body, link, priority, source, data, read_at
`

type InsertNotificationParams struct {
	CreatedAt time.Time
	Kind      string
	Title     string
	Body      string
	Link      string
	Priority  string
	Source    string
	Data      string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.CreatedAt,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Priority,
		arg.Source,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Priority,
		&i.Source,
		&i.Data,
		&i.ReadAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, kind, os, arch, hostname, version, capabilities, token_hash, created_at, last_seen_at, revoked_at FROM agents WHERE revoked_at IS NULL ORDER BY kind, name
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Os,
			&i.Arch,
			&i.Hostname,
			&i.Version,
			&i.Capabilities,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, actor, "action", target, detail, result FROM audit_log WHERE id < ? ORDER BY id DESC LIMIT ?
`

type ListAuditParams struct {
	ID    int64
	Limit int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Detail,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, created_at, kind, title, body, link, priority, source, data, read_at FROM notifications
WHERE id < ?1 AND (CAST(?2 AS INTEGER) = 0 OR read_at IS NULL)
ORDER BY id DESC LIMIT ?3
`

type ListNotificationsParams struct {
	Before     int64
	UnreadOnly int64
	Lim        int64
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.Before, arg.UnreadOnly, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Priority,
			&i.Source,
			&i.Data,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettingsByPrefix = `-- name: ListSettingsByPrefix :many
SELECT "key", value, encrypted, updated_at FROM settings WHERE key LIKE ? || '%' ORDER BY key
`

func (q *Queries) ListSettingsByPrefix(ctx context.Context, dollar_1 *string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsByPrefix, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Encrypted,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = ? WHERE read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, readAt *time.Time) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, readAt)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = ? WHERE id = ? AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ReadAt *time.Time
	ID     int64
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, arg.ReadAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAgent = `-- name: RevokeAgent :execrows
UPDATE agents SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeAgentParams struct {
	RevokedAt *time.Time
	ID        string
}

func (q *Queries) RevokeAgent(ctx context.Context, arg RevokeAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAgent, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}

const updateAgentSeen = `-- name: UpdateAgentSeen :exec
UPDATE agents SET last_seen_at = ?, os = ?, arch = ?, hostname = ?, version = ?, capabilities = ? WHERE id = ?
`

type UpdateAgentSeenParams struct {
	LastSeenAt   *time.Time
	Os           string
	Arch         string
	Hostname     string
	Version      string
	Capabilities string
	ID           string
}

func (q *Queries) UpdateAgentSeen(ctx context.Context, arg UpdateAgentSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentSeen,
		arg.LastSeenAt,
		arg.Os,
		arg.Arch,
		arg.Hostname,
		arg.Version,
		arg.Capabilities,
		arg.ID,
	)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, encrypted, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, encrypted = excluded.encrypted, updated_at = excluded.updated_at
`

type UpsertSettingParams struct {
	Key       string
	Value     string
	Encrypted int64
	UpdatedAt time.Time
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.Encrypted,
		arg.UpdatedAt,
	)
	return err
}

const usePairingCode = `-- name: UsePairingCode :one
UPDATE pairing_codes SET used_at = ?
WHERE code_hash = ? AND used_at IS NULL AND expires_at > ?
RETURNING code_hash, name, kind, expires_at, used_at
`

type UsePairingCodeParams struct {
	UsedAt    *time.Time
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) UsePairingCode(ctx context.Context, arg UsePairingCodeParams) (PairingCode, error) {
	row := q.db.QueryRowContext(ctx, usePairingCode, arg.UsedAt, arg.CodeHash, arg.ExpiresAt)
	var i PairingCode
	err := row.Scan(
		&i.CodeHash,
		&i.Name,
		&i.Kind,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
