// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (name, icon, color, unit, daily_target, remind_mode, remind_interval_minutes,
                    remind_window, remind_times, ha_entity_id, sort_order, created_at, kind)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, icon, color, unit, daily_target, remind_mode, remind_interval_minutes, remind_window, remind_times, ha_entity_id, archived_at, sort_order, created_at, last_reminded_at, quiet_until, kind
`

type CreateHabitParams struct {
	Name                  string
	Icon                  string
	Color                 string
	Unit                  string
	DailyTarget           float64
	RemindMode            string
	RemindIntervalMinutes int64
	RemindWindow          string
	RemindTimes           string
	HaEntityID            string
	SortOrder             int64
	CreatedAt             time.Time
	Kind                  string
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, createHabit,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Unit,
		arg.DailyTarget,
		arg.RemindMode,
		arg.RemindIntervalMinutes,
		arg.RemindWindow,
		arg.RemindTimes,
		arg.HaEntityID,
		arg.SortOrder,
		arg.CreatedAt,
		arg.Kind,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Unit,
		&i.DailyTarget,
		&i.RemindMode,
		&i.RemindIntervalMinutes,
		&i.RemindWindow,
		&i.RemindTimes,
		&i.HaEntityID,
		&i.ArchivedAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.LastRemindedAt,
		&i.QuietUntil,
		&i.Kind,
	)
	return i, err
}

const createHabitLog = `-- name: CreateHabitLog :one
INSERT INTO habit_logs (habit_id, at, amount, source, note, workout_log_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, habit_id, at, amount, source, note, workout_log_id
`

type CreateHabitLogParams struct {
	HabitID      int64
	At           time.Time
	Amount       float64
	Source       string
	Note         string
	WorkoutLogID *int64
}

func (q *Queries) CreateHabitLog(ctx context.Context, arg CreateHabitLogParams) (HabitLog, error) {
	row := q.db.QueryRowContext(ctx, createHabitLog,
		arg.HabitID,
		arg.At,
		arg.Amount,
		arg.Source,
		arg.Note,
		arg.WorkoutLogID,
	)
	var i HabitLog
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.At,
		&i.Amount,
		&i.Source,
		&i.Note,
		&i.WorkoutLogID,
	)
	return i, err
}

const createWorkoutLog = `-- name: CreateWorkoutLog :one
INSERT INTO workout_logs (date, plan_id, items, duration_minutes, note, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, date, plan_id, items, duration_minutes, note, created_at
`

type CreateWorkoutLogParams struct {
	Date            string
	PlanID          *int64
	Items           string
	DurationMinutes int64
	Note            string
	CreatedAt       time.Time
}

func (q *Queries) CreateWorkoutLog(ctx context.Context, arg CreateWorkoutLogParams) (WorkoutLog, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutLog,
		arg.Date,
		arg.PlanID,
		arg.Items,
		arg.DurationMinutes,
		arg.Note,
		arg.CreatedAt,
	)
	var i WorkoutLog
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.PlanID,
		&i.Items,
		&i.DurationMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :execrows
DELETE FROM habits WHERE id = ?
`

func (q *Queries) DeleteHabit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHabit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteHabitLog = `-- name: DeleteHabitLog :execrows
DELETE FROM habit_logs WHERE id = ?
`

func (q *Queries) DeleteHabitLog(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHabitLog, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWorkoutCheckins = `-- name: DeleteWorkoutCheckins :many
DELETE FROM habit_logs WHERE workout_log_id = ? RETURNING id, habit_id
`

type DeleteWorkoutCheckinsRow struct {
	ID      int64
	HabitID int64
}

func (q *Queries) DeleteWorkoutCheckins(ctx context.Context, workoutLogID *int64) ([]DeleteWorkoutCheckinsRow, error) {
	rows, err := q.db.QueryContext(ctx, deleteWorkoutCheckins, workoutLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteWorkoutCheckinsRow
	for rows.Next() {
		var i DeleteWorkoutCheckinsRow
		if err := rows.Scan(&i.ID, &i.HabitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWorkoutLog = `-- name: DeleteWorkoutLog :execrows
DELETE FROM workout_logs WHERE id = ?
`

func (q *Queries) DeleteWorkoutLog(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkoutLog, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWorkoutPlans = `-- name: DeleteWorkoutPlans :exec
DELETE FROM workout_plans
`

func (q *Queries) DeleteWorkoutPlans(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutPlans)
	return err
}

const getHabit = `-- name: GetHabit :one
SELECT id, name, icon, color, unit, daily_target, remind_mode, remind_interval_minutes, remind_window, remind_times, ha_entity_id, archived_at, sort_order, created_at, last_reminded_at, quiet_until, kind FROM habits WHERE id = ?
`

func (q *Queries) GetHabit(ctx context.Context, id int64) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Unit,
		&i.DailyTarget,
		&i.RemindMode,
		&i.RemindIntervalMinutes,
		&i.RemindWindow,
		&i.RemindTimes,
		&i.HaEntityID,
		&i.ArchivedAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.LastRemindedAt,
		&i.QuietUntil,
		&i.Kind,
	)
	return i, err
}

const getHabitLog = `-- name: GetHabitLog :one
SELECT id, habit_id, at, amount, source, note, workout_log_id FROM habit_logs WHERE id = ?
`

func (q *Queries) GetHabitLog(ctx context.Context, id int64) (HabitLog, error) {
	row := q.db.QueryRowContext(ctx, getHabitLog, id)
	var i HabitLog
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.At,
		&i.Amount,
		&i.Source,
		&i.Note,
		&i.WorkoutLogID,
	)
	return i, err
}

const insertWorkoutPlan = `-- name: InsertWorkoutPlan :one
INSERT INTO workout_plans (weekday, title, items) VALUES (?, ?, ?) RETURNING id, weekday, title, items
`

type InsertWorkoutPlanParams struct {
	Weekday int64
	Title   string
	Items   string
}

func (q *Queries) InsertWorkoutPlan(ctx context.Context, arg InsertWorkoutPlanParams) (WorkoutPlan, error) {
	row := q.db.QueryRowContext(ctx, insertWorkoutPlan, arg.Weekday, arg.Title, arg.Items)
	var i WorkoutPlan
	err := row.Scan(
		&i.ID,
		&i.Weekday,
		&i.Title,
		&i.Items,
	)
	return i, err
}

const listActiveWorkoutHabits = `-- name: ListActiveWorkoutHabits :many
SELECT id, name, icon, color, unit, daily_target, remind_mode, remind_interval_minutes, remind_window, remind_times, ha_entity_id, archived_at, sort_order, created_at, last_reminded_at, quiet_until, kind FROM habits WHERE kind = 'workout' AND archived_at IS NULL ORDER BY id
`

func (q *Queries) ListActiveWorkoutHabits(ctx context.Context) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWorkoutHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Unit,
			&i.DailyTarget,
			&i.RemindMode,
			&i.RemindIntervalMinutes,
			&i.RemindWindow,
			&i.RemindTimes,
			&i.HaEntityID,
			&i.ArchivedAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.LastRemindedAt,
			&i.QuietUntil,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitLogsForHabitSince = `-- name: ListHabitLogsForHabitSince :many
SELECT id, habit_id, at, amount, source, note, workout_log_id FROM habit_logs WHERE habit_id = ? AND at >= ? ORDER BY at DESC, id DESC
`

type ListHabitLogsForHabitSinceParams struct {
	HabitID int64
	At      time.Time
}

func (q *Queries) ListHabitLogsForHabitSince(ctx context.Context, arg ListHabitLogsForHabitSinceParams) ([]HabitLog, error) {
	rows, err := q.db.QueryContext(ctx, listHabitLogsForHabitSince, arg.HabitID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitLog
	for rows.Next() {
		var i HabitLog
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.At,
			&i.Amount,
			&i.Source,
			&i.Note,
			&i.WorkoutLogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitLogsSince = `-- name: ListHabitLogsSince :many
SELECT id, habit_id, at, amount, source, note, workout_log_id FROM habit_logs WHERE at >= ? ORDER BY at DESC, id DESC
`

func (q *Queries) ListHabitLogsSince(ctx context.Context, at time.Time) ([]HabitLog, error) {
	rows, err := q.db.QueryContext(ctx, listHabitLogsSince, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitLog
	for rows.Next() {
		var i HabitLog
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.At,
			&i.Amount,
			&i.Source,
			&i.Note,
			&i.WorkoutLogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT id, name, icon, color, unit, daily_target, remind_mode, remind_interval_minutes, remind_window, remind_times, ha_entity_id, archived_at, sort_order, created_at, last_reminded_at, quiet_until, kind FROM habits
WHERE CAST(?1 AS INTEGER) = 1 OR archived_at IS NULL
ORDER BY sort_order, id
`

func (q *Queries) ListHabits(ctx context.Context, includeArchived int64) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabits, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Unit,
			&i.DailyTarget,
			&i.RemindMode,
			&i.RemindIntervalMinutes,
			&i.RemindWindow,
			&i.RemindTimes,
			&i.HaEntityID,
			&i.ArchivedAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.LastRemindedAt,
			&i.QuietUntil,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsByEntity = `-- name: ListHabitsByEntity :many
SELECT id, name, icon, color, unit, daily_target, remind_mode, remind_interval_minutes, remind_window, remind_times, ha_entity_id, archived_at, sort_order, created_at, last_reminded_at, quiet_until, kind FROM habits WHERE ha_entity_id = ? AND archived_at IS NULL
`

func (q *Queries) ListHabitsByEntity(ctx context.Context, haEntityID string) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabitsByEntity, haEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Unit,
			&i.DailyTarget,
			&i.RemindMode,
			&i.RemindIntervalMinutes,
			&i.RemindWindow,
			&i.RemindTimes,
			&i.HaEntityID,
			&i.ArchivedAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.LastRemindedAt,
			&i.QuietUntil,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutLogsSince = `-- name: ListWorkoutLogsSince :many
SELECT id, date, plan_id, items, duration_minutes, note, created_at FROM workout_logs WHERE date >= ? ORDER BY date DESC, id DESC
`

func (q *Queries) ListWorkoutLogsSince(ctx context.Context, date string) ([]WorkoutLog, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutLogsSince, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutLog
	for rows.Next() {
		var i WorkoutLog
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.PlanID,
			&i.Items,
			&i.DurationMinutes,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutPlans = `-- name: ListWorkoutPlans :many
SELECT id, weekday, title, items FROM workout_plans ORDER BY weekday, id
`

func (q *Queries) ListWorkoutPlans(ctx context.Context) ([]WorkoutPlan, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutPlan
	for rows.Next() {
		var i WorkoutPlan
		if err := rows.Scan(
			&i.ID,
			&i.Weekday,
			&i.Title,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHabitReminded = `-- name: MarkHabitReminded :exec
UPDATE habits SET last_reminded_at = ? WHERE id = ?
`

type MarkHabitRemindedParams struct {
	LastRemindedAt *time.Time
	ID             int64
}

func (q *Queries) MarkHabitReminded(ctx context.Context, arg MarkHabitRemindedParams) error {
	_, err := q.db.ExecContext(ctx, markHabitReminded, arg.LastRemindedAt, arg.ID)
	return err
}

const maxHabitSortOrder = `-- name: MaxHabitSortOrder :one
SELECT CAST(coalesce(max(sort_order), 0) AS INTEGER) FROM habits
`

func (q *Queries) MaxHabitSortOrder(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxHabitSortOrder)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setHabitQuietUntil = `-- name: SetHabitQuietUntil :exec
UPDATE habits SET quiet_until = ? WHERE id = ?
`

type SetHabitQuietUntilParams struct {
	QuietUntil *time.Time
	ID         int64
}

func (q *Queries) SetHabitQuietUntil(ctx context.Context, arg SetHabitQuietUntilParams) error {
	_, err := q.db.ExecContext(ctx, setHabitQuietUntil, arg.QuietUntil, arg.ID)
	return err
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET name = ?, icon = ?, color = ?, unit = ?, daily_target = ?, remind_mode = ?,
    remind_interval_minutes = ?, remind_window = ?, remind_times = ?, ha_entity_id = ?,
    archived_at = ?, sort_order = ?, kind = ?
WHERE id = ?
RETURNING id, name, icon, color, unit, daily_target, remind_mode, remind_interval_minutes, remind_window, remind_times, ha_entity_id, archived_at, sort_order, created_at, last_reminded_at, quiet_until, kind
`

type UpdateHabitParams struct {
	Name                  string
	Icon                  string
	Color                 string
	Unit                  string
	DailyTarget           float64
	RemindMode            string
	RemindIntervalMinutes int64
	RemindWindow          string
	RemindTimes           string
	HaEntityID            string
	ArchivedAt            *time.Time
	SortOrder             int64
	Kind                  string
	ID                    int64
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, updateHabit,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Unit,
		arg.DailyTarget,
		arg.RemindMode,
		arg.RemindIntervalMinutes,
		arg.RemindWindow,
		arg.RemindTimes,
		arg.HaEntityID,
		arg.ArchivedAt,
		arg.SortOrder,
		arg.Kind,
		arg.ID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Unit,
		&i.DailyTarget,
		&i.RemindMode,
		&i.RemindIntervalMinutes,
		&i.RemindWindow,
		&i.RemindTimes,
		&i.HaEntityID,
		&i.ArchivedAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.LastRemindedAt,
		&i.QuietUntil,
		&i.Kind,
	)
	return i, err
}
