// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ReadItemKind.
const (
	Page  ReadItemKind = "page"
	Tweet ReadItemKind = "tweet"
)

// Valid indicates whether the value is a known member of the ReadItemKind enum.
func (e ReadItemKind) Valid() bool {
	switch e {
	case Page:
		return true
	case Tweet:
		return true
	default:
		return false
	}
}

// Defines values for ReadItemSource.
const (
	ReadItemSourceAi       ReadItemSource = "ai"
	ReadItemSourceShare    ReadItemSource = "share"
	ReadItemSourceTelegram ReadItemSource = "telegram"
	ReadItemSourceWeb      ReadItemSource = "web"
)

// Valid indicates whether the value is a known member of the ReadItemSource enum.
func (e ReadItemSource) Valid() bool {
	switch e {
	case ReadItemSourceAi:
		return true
	case ReadItemSourceShare:
		return true
	case ReadItemSourceTelegram:
		return true
	case ReadItemSourceWeb:
		return true
	default:
		return false
	}
}

// Defines values for ReadItemInputSource.
const (
	ReadItemInputSourceShare ReadItemInputSource = "share"
	ReadItemInputSourceWeb   ReadItemInputSource = "web"
)

// Valid indicates whether the value is a known member of the ReadItemInputSource enum.
func (e ReadItemInputSource) Valid() bool {
	switch e {
	case ReadItemInputSourceShare:
		return true
	case ReadItemInputSourceWeb:
		return true
	default:
		return false
	}
}

// Defines values for ReadStatus.
const (
	Failed ReadStatus = "failed"
	Queued ReadStatus = "queued"
	Ready  ReadStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadStatus enum.
func (e ReadStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Queued:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for XAuthStatus.
const (
	Error      XAuthStatus = "error"
	Expired    XAuthStatus = "expired"
	None       XAuthStatus = "none"
	Ok         XAuthStatus = "ok"
	Unverified XAuthStatus = "unverified"
)

// Valid indicates whether the value is a known member of the XAuthStatus enum.
func (e XAuthStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Expired:
		return true
	case None:
		return true
	case Ok:
		return true
	case Unverified:
		return true
	default:
		return false
	}
}

// Defines values for ListReadItemsParamsView.
const (
	All    ListReadItemsParamsView = "all"
	Read   ListReadItemsParamsView = "read"
	Unread ListReadItemsParamsView = "unread"
)

// Valid indicates whether the value is a known member of the ListReadItemsParamsView enum.
func (e ListReadItemsParamsView) Valid() bool {
	switch e {
	case All:
		return true
	case Read:
		return true
	case Unread:
		return true
	default:
		return false
	}
}

// ReadCounts defines model for ReadCounts.
type ReadCounts struct {
	All    int `json:"all"`
	Failed int `json:"failed"`
	Read   int `json:"read"`
	Unread int `json:"unread"`
}

// ReadItem defines model for ReadItem.
type ReadItem struct {
	// Content 存档的正文，纯文本。只有详情接口给，列表里没有
	Content *string `json:"content,omitempty"`

	// ContentHtml 存档的图文 HTML，已清理，图片是本站地址。只有详情接口给
	ContentHtml *string   `json:"contentHtml,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`

	// Error 抓取失败的原因
	Error string `json:"error"`

	// Excerpt 网页自己写的描述
	Excerpt    string     `json:"excerpt"`
	FetchedAt  *time.Time `json:"fetchedAt,omitempty"`
	HasContent bool       `json:"hasContent"`

	// HasHtml 有存档的图文 HTML
	HasHtml bool         `json:"hasHtml"`
	Id      int64        `json:"id"`
	Kind    ReadItemKind `json:"kind"`

	// Meta 推文的作者、发布时间、用哪一步读到的、内容是否不完整等
	Meta   map[string]interface{} `json:"meta"`
	Note   string                 `json:"note"`
	Read   bool                   `json:"read"`
	ReadAt *time.Time             `json:"readAt,omitempty"`
	Site   string                 `json:"site"`
	Source ReadItemSource         `json:"source"`

	// Status queued 等着抓，ready 抓好了，failed 抓取失败
	Status ReadStatus `json:"status"`

	// Summary AI 写的摘要，最多三行，没有为空字符串
	Summary string   `json:"summary"`
	Tags    []string `json:"tags"`

	// Title 没抓到标题时是网址里的主机名
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
	Url       string    `json:"url"`
}

// ReadItemKind defines model for ReadItem.Kind.
type ReadItemKind string

// ReadItemSource defines model for ReadItem.Source.
type ReadItemSource string

// ReadItemInput defines model for ReadItemInput.
type ReadItemInput struct {
	Note   *string              `json:"note,omitempty"`
	Source *ReadItemInputSource `json:"source,omitempty"`
	Url    string               `json:"url"`
}

// ReadItemInputSource defines model for ReadItemInput.Source.
type ReadItemInputSource string

// ReadItemPatch defines model for ReadItemPatch.
type ReadItemPatch struct {
	Note  *string   `json:"note,omitempty"`
	Read  *bool     `json:"read,omitempty"`
	Tags  *[]string `json:"tags,omitempty"`
	Title *string   `json:"title,omitempty"`
}

// ReadItemResult defines model for ReadItemResult.
type ReadItemResult struct {
	Duplicate bool     `json:"duplicate"`
	Item      ReadItem `json:"item"`
}

// ReadList defines model for ReadList.
type ReadList struct {
	Counts ReadCounts `json:"counts"`
	Items  []ReadItem `json:"items"`

	// Tags 用得最多的 30 个标签
	Tags []ReadTag `json:"tags"`
}

// ReadStatus queued 等着抓，ready 抓好了，failed 抓取失败
type ReadStatus string

// ReadTag defines model for ReadTag.
type ReadTag struct {
	Count int    `json:"count"`
	Tag   string `json:"tag"`
}

// XAuth defines model for XAuth.
type XAuth struct {
	// Configured 是否保存了 Cookie
	Configured bool `json:"configured"`

	// Fxtwitter 前两步失败时是否用第三方转换服务
	Fxtwitter bool `json:"fxtwitter"`

	// Message 上次测试或抓取失败的原因
	Message *string `json:"message,omitempty"`

	// QueryId GraphQL 接口的 queryId，空表示用内置的
	QueryId string `json:"queryId"`

	// Status none 没配置，unverified 还没验证，ok 可用，expired Cookie 可能过期，error 上次测试失败
	Status     XAuthStatus `json:"status"`
	VerifiedAt *time.Time  `json:"verifiedAt,omitempty"`
}

// XAuthStatus none 没配置，unverified 还没验证，ok 可用，expired Cookie 可能过期，error 上次测试失败
type XAuthStatus string

// XAuthInput defines model for XAuthInput.
type XAuthInput struct {
	AuthToken *string `json:"authToken,omitempty"`
	Ct0       *string `json:"ct0,omitempty"`
	Fxtwitter *bool   `json:"fxtwitter,omitempty"`
	QueryId   *string `json:"queryId,omitempty"`
}

// ItemId defines model for ItemId.
type ItemId = int64

// ListReadItemsParams defines parameters for ListReadItems.
type ListReadItemsParams struct {
	View *ListReadItemsParamsView `form:"view,omitempty" json:"view,omitempty"`
	Tag  *string                  `form:"tag,omitempty" json:"tag,omitempty"`

	// Q 在标题、网址、摘要、备注和正文里找
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListReadItemsParamsView defines parameters for ListReadItems.
type ListReadItemsParamsView string

// CreateReadItemJSONRequestBody defines body for CreateReadItem for application/json ContentType.
type CreateReadItemJSONRequestBody = ReadItemInput

// SaveReadXAuthJSONRequestBody defines body for SaveReadXAuth for application/json ContentType.
type SaveReadXAuthJSONRequestBody = XAuthInput

// UpdateReadItemJSONRequestBody defines body for UpdateReadItem for application/json ContentType.
type UpdateReadItemJSONRequestBody = ReadItemPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /readlater)
	ListReadItems(w http.ResponseWriter, r *http.Request, params ListReadItemsParams)

	// (POST /readlater)
	CreateReadItem(w http.ResponseWriter, r *http.Request)

	// (DELETE /readlater/x-auth)
	ClearReadXAuth(w http.ResponseWriter, r *http.Request)

	// (GET /readlater/x-auth)
	GetReadXAuth(w http.ResponseWriter, r *http.Request)

	// (PUT /readlater/x-auth)
	SaveReadXAuth(w http.ResponseWriter, r *http.Request)

	// (POST /readlater/x-auth/test)
	TestReadXAuth(w http.ResponseWriter, r *http.Request)

	// (DELETE /readlater/{itemId})
	DeleteReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId)

	// (GET /readlater/{itemId})
	GetReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId)

	// (PATCH /readlater/{itemId})
	UpdateReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId)

	// (GET /readlater/{itemId}/assets/{hash})
	GetReadAsset(w http.ResponseWriter, r *http.Request, itemId ItemId, hash string)

	// (GET /readlater/{itemId}/export)
	ExportReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId)

	// (POST /readlater/{itemId}/refetch)
	RefetchReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId)

	// (POST /readlater/{itemId}/summarize)
	SummarizeReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /readlater)
func (_ Unimplemented) ListReadItems(w http.ResponseWriter, r *http.Request, params ListReadItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /readlater)
func (_ Unimplemented) CreateReadItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /readlater/x-auth)
func (_ Unimplemented) ClearReadXAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readlater/x-auth)
func (_ Unimplemented) GetReadXAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /readlater/x-auth)
func (_ Unimplemented) SaveReadXAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /readlater/x-auth/test)
func (_ Unimplemented) TestReadXAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /readlater/{itemId})
func (_ Unimplemented) DeleteReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readlater/{itemId})
func (_ Unimplemented) GetReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /readlater/{itemId})
func (_ Unimplemented) UpdateReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readlater/{itemId}/assets/{hash})
func (_ Unimplemented) GetReadAsset(w http.ResponseWriter, r *http.Request, itemId ItemId, hash string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readlater/{itemId}/export)
func (_ Unimplemented) ExportReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /readlater/{itemId}/refetch)
func (_ Unimplemented) RefetchReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /readlater/{itemId}/summarize)
func (_ Unimplemented) SummarizeReadItem(w http.ResponseWriter, r *http.Request, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListReadItems operation middleware
func (siw *ServerInterfaceWrapper) ListReadItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReadItemsParams

	// ------------- Optional query parameter "view" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "view", r.URL.Query(), &params.View, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "view"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "view", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReadItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateReadItem operation middleware
func (siw *ServerInterfaceWrapper) CreateReadItem(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReadItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearReadXAuth operation middleware
func (siw *ServerInterfaceWrapper) ClearReadXAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearReadXAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadXAuth operation middleware
func (siw *ServerInterfaceWrapper) GetReadXAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadXAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveReadXAuth operation middleware
func (siw *ServerInterfaceWrapper) SaveReadXAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveReadXAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestReadXAuth operation middleware
func (siw *ServerInterfaceWrapper) TestReadXAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestReadXAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteReadItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteReadItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteReadItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadItem operation middleware
func (siw *ServerInterfaceWrapper) GetReadItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateReadItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateReadItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateReadItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadAsset operation middleware
func (siw *ServerInterfaceWrapper) GetReadAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadAsset(w, r, itemId, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportReadItem operation middleware
func (siw *ServerInterfaceWrapper) ExportReadItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportReadItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefetchReadItem operation middleware
func (siw *ServerInterfaceWrapper) RefetchReadItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefetchReadItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SummarizeReadItem operation middleware
func (siw *ServerInterfaceWrapper) SummarizeReadItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SummarizeReadItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readlater", wrapper.ListReadItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/readlater", wrapper.CreateReadItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/readlater/{itemId}", wrapper.DeleteReadItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readlater/{itemId}", wrapper.GetReadItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/readlater/{itemId}", wrapper.UpdateReadItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/readlater/{itemId}/refetch", wrapper.RefetchReadItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/readlater/{itemId}/summarize", wrapper.SummarizeReadItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readlater/{itemId}/assets/{hash}", wrapper.GetReadAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readlater/{itemId}/export", wrapper.ExportReadItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/readlater/x-auth", wrapper.ClearReadXAuth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readlater/x-auth", wrapper.GetReadXAuth)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/readlater/x-auth", wrapper.SaveReadXAuth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/readlater/x-auth/test", wrapper.TestReadXAuth)
	})

	return r
}
