// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	externalRef0 "github.com/j0x3n/x-console/backend/internal/server/apigen/common"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Attachment defines model for Attachment.
type Attachment struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	Mime      string    `json:"mime"`
	Name      string    `json:"name"`
	NoteId    int64     `json:"noteId"`
	Size      int64     `json:"size"`

	// Url 下载地址，例如 /api/v1/notes/attachments/3
	Url string `json:"url"`
}

// CreateNote defines model for CreateNote.
type CreateNote struct {
	Body *string `json:"body,omitempty"`

	// Hidden 直接建成隐藏笔记，要先解锁
	Hidden *bool     `json:"hidden,omitempty"`
	Pinned *bool     `json:"pinned,omitempty"`
	Tags   *[]string `json:"tags,omitempty"`
	Title  *string   `json:"title,omitempty"`
}

// Note defines model for Note.
type Note struct {
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`

	// Body Markdown
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`

	// Hidden B13 隐藏笔记，只在解锁后出现
	Hidden    *bool     `json:"hidden,omitempty"`
	Id        int64     `json:"id"`
	Pinned    bool      `json:"pinned"`
	Tags      []string  `json:"tags"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// NoteSummary defines model for NoteSummary.
type NoteSummary struct {
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`

	// Excerpt 正文开头的一段纯文本
	Excerpt string `json:"excerpt"`

	// Hidden B13 隐藏笔记，只在解锁后出现
	Hidden *bool `json:"hidden,omitempty"`
	Id     int64 `json:"id"`
	Pinned bool  `json:"pinned"`

	// Snippet 搜索时的命中片段，命中的部分用 U+E000 和 U+E001 包住
	Snippet *string  `json:"snippet,omitempty"`
	Tags    []string `json:"tags"`

	// Thumbnail 正文里第一张附件图片的地址，没有图片时不返回
	Thumbnail *string   `json:"thumbnail,omitempty"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TagColorInput defines model for TagColorInput.
type TagColorInput struct {
	// Color 形如
	Color string `json:"color"`
	Tag   string `json:"tag"`
}

// TagCount defines model for TagCount.
type TagCount struct {
	// Color 用户给标签设的颜色，形如
	Color *string `json:"color,omitempty"`
	Count int     `json:"count"`
	Tag   string  `json:"tag"`
}

// UpdateNote defines model for UpdateNote.
type UpdateNote struct {
	Archived *bool   `json:"archived,omitempty"`
	Body     *string `json:"body,omitempty"`

	// Hidden 设为隐藏或取消隐藏，要先解锁
	Hidden *bool `json:"hidden,omitempty"`
	Pinned *bool `json:"pinned,omitempty"`

	// Tags 传了就整体替换
	Tags  *[]string `json:"tags,omitempty"`
	Title *string   `json:"title,omitempty"`
}

// AttachmentId defines model for AttachmentId.
type AttachmentId = int64

// NoteId defines model for NoteId.
type NoteId = int64

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Tag    *string `form:"tag,omitempty" json:"tag,omitempty"`
	Pinned *bool   `form:"pinned,omitempty" json:"pinned,omitempty"`

	// Archived true 时只看已归档的笔记，默认只看未归档的
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`

	// Hidden B13。true 时只返回隐藏笔记，要先解锁隐藏内容，没解锁时返回空列表。
	// 不传时只返回普通笔记。隐藏笔记不进全文索引，搜索用 LIKE。
	Hidden *bool                `form:"hidden,omitempty" json:"hidden,omitempty"`
	Limit  *externalRef0.Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *externalRef0.Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UploadNoteAttachmentMultipartBody defines parameters for UploadNoteAttachment.
type UploadNoteAttachmentMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// NoteToIssueJSONBody defines parameters for NoteToIssue.
type NoteToIssueJSONBody struct {
	ProjectId int64 `json:"projectId"`
}

// NoteToReminderJSONBody defines parameters for NoteToReminder.
type NoteToReminderJSONBody struct {
	At time.Time `json:"at"`

	// Rrule 重复规则，例如 FREQ=DAILY;BYHOUR=9
	Rrule *string `json:"rrule,omitempty"`
}

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNote

// SetNoteTagColorJSONRequestBody defines body for SetNoteTagColor for application/json ContentType.
type SetNoteTagColorJSONRequestBody = TagColorInput

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = UpdateNote

// UploadNoteAttachmentMultipartRequestBody defines body for UploadNoteAttachment for multipart/form-data ContentType.
type UploadNoteAttachmentMultipartRequestBody UploadNoteAttachmentMultipartBody

// NoteToIssueJSONRequestBody defines body for NoteToIssue for application/json ContentType.
type NoteToIssueJSONRequestBody NoteToIssueJSONBody

// NoteToReminderJSONRequestBody defines body for NoteToReminder for application/json ContentType.
type NoteToReminderJSONRequestBody NoteToReminderJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /notes)
	ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams)

	// (POST /notes)
	CreateNote(w http.ResponseWriter, r *http.Request)

	// (DELETE /notes/attachments/{attachmentId})
	DeleteNoteAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)

	// (GET /notes/attachments/{attachmentId})
	DownloadNoteAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)

	// (PUT /notes/tag-colors)
	SetNoteTagColor(w http.ResponseWriter, r *http.Request)

	// (GET /notes/tags)
	ListNoteTags(w http.ResponseWriter, r *http.Request)

	// (DELETE /notes/{noteId})
	DeleteNote(w http.ResponseWriter, r *http.Request, noteId NoteId)

	// (GET /notes/{noteId})
	GetNote(w http.ResponseWriter, r *http.Request, noteId NoteId)

	// (PATCH /notes/{noteId})
	UpdateNote(w http.ResponseWriter, r *http.Request, noteId NoteId)

	// (GET /notes/{noteId}/attachments)
	ListNoteAttachments(w http.ResponseWriter, r *http.Request, noteId NoteId)

	// (POST /notes/{noteId}/attachments)
	UploadNoteAttachment(w http.ResponseWriter, r *http.Request, noteId NoteId)

	// (POST /notes/{noteId}/to-issue)
	NoteToIssue(w http.ResponseWriter, r *http.Request, noteId NoteId)

	// (POST /notes/{noteId}/to-reminder)
	NoteToReminder(w http.ResponseWriter, r *http.Request, noteId NoteId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /notes)
func (_ Unimplemented) ListNotes(w http.ResponseWriter, r *http.Request, params ListNotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /notes)
func (_ Unimplemented) CreateNote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /notes/attachments/{attachmentId})
func (_ Unimplemented) DeleteNoteAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /notes/attachments/{attachmentId})
func (_ Unimplemented) DownloadNoteAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /notes/tag-colors)
func (_ Unimplemented) SetNoteTagColor(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /notes/tags)
func (_ Unimplemented) ListNoteTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /notes/{noteId})
func (_ Unimplemented) DeleteNote(w http.ResponseWriter, r *http.Request, noteId NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /notes/{noteId})
func (_ Unimplemented) GetNote(w http.ResponseWriter, r *http.Request, noteId NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /notes/{noteId})
func (_ Unimplemented) UpdateNote(w http.ResponseWriter, r *http.Request, noteId NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /notes/{noteId}/attachments)
func (_ Unimplemented) ListNoteAttachments(w http.ResponseWriter, r *http.Request, noteId NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /notes/{noteId}/attachments)
func (_ Unimplemented) UploadNoteAttachment(w http.ResponseWriter, r *http.Request, noteId NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /notes/{noteId}/to-issue)
func (_ Unimplemented) NoteToIssue(w http.ResponseWriter, r *http.Request, noteId NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /notes/{noteId}/to-reminder)
func (_ Unimplemented) NoteToReminder(w http.ResponseWriter, r *http.Request, noteId NoteId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListNotes operation middleware
func (siw *ServerInterfaceWrapper) ListNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pinned" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pinned", r.URL.Query(), &params.Pinned, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pinned"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pinned", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "hidden" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hidden", r.URL.Query(), &params.Hidden, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "hidden"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hidden", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNoteAttachment operation middleware
func (siw *ServerInterfaceWrapper) DeleteNoteAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNoteAttachment(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadNoteAttachment operation middleware
func (siw *ServerInterfaceWrapper) DownloadNoteAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadNoteAttachment(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetNoteTagColor operation middleware
func (siw *ServerInterfaceWrapper) SetNoteTagColor(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetNoteTagColor(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNoteTags operation middleware
func (siw *ServerInterfaceWrapper) ListNoteTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNoteTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNote operation middleware
func (siw *ServerInterfaceWrapper) DeleteNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNote operation middleware
func (siw *ServerInterfaceWrapper) UpdateNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNoteAttachments operation middleware
func (siw *ServerInterfaceWrapper) ListNoteAttachments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNoteAttachments(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadNoteAttachment operation middleware
func (siw *ServerInterfaceWrapper) UploadNoteAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadNoteAttachment(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// NoteToIssue operation middleware
func (siw *ServerInterfaceWrapper) NoteToIssue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NoteToIssue(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// NoteToReminder operation middleware
func (siw *ServerInterfaceWrapper) NoteToReminder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId NoteId

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NoteToReminder(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes", wrapper.ListNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes", wrapper.CreateNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes/tags", wrapper.ListNoteTags)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/notes/tag-colors", wrapper.SetNoteTagColor)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/notes/{noteId}", wrapper.DeleteNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes/{noteId}", wrapper.GetNote)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/notes/{noteId}", wrapper.UpdateNote)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes/{noteId}/to-issue", wrapper.NoteToIssue)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes/{noteId}/to-reminder", wrapper.NoteToReminder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes/{noteId}/attachments", wrapper.ListNoteAttachments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/notes/{noteId}/attachments", wrapper.UploadNoteAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/notes/attachments/{attachmentId}", wrapper.DeleteNoteAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notes/attachments/{attachmentId}", wrapper.DownloadNoteAttachment)
	})

	return r
}
