// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE id = ?
`

func (q *Queries) DeleteContact(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContact = `-- name: GetContact :one
SELECT id, name, group_kind, events, last_contact_on, contact_every_days, remind_days, notes, notified_json, lost_for, archived_at, created_at, updated_at FROM contacts WHERE id = ?
`

func (q *Queries) GetContact(ctx context.Context, id int64) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupKind,
		&i.Events,
		&i.LastContactOn,
		&i.ContactEveryDays,
		&i.RemindDays,
		&i.Notes,
		&i.NotifiedJson,
		&i.LostFor,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :one
INSERT INTO contacts (name, group_kind, events, last_contact_on, contact_every_days, remind_days, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, group_kind, events, last_contact_on, contact_every_days, remind_days, notes, notified_json, lost_for, archived_at, created_at, updated_at
`

type InsertContactParams struct {
	Name             string
	GroupKind        string
	Events           string
	LastContactOn    string
	ContactEveryDays int64
	RemindDays       string
	Notes            string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, insertContact,
		arg.Name,
		arg.GroupKind,
		arg.Events,
		arg.LastContactOn,
		arg.ContactEveryDays,
		arg.RemindDays,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupKind,
		&i.Events,
		&i.LastContactOn,
		&i.ContactEveryDays,
		&i.RemindDays,
		&i.Notes,
		&i.NotifiedJson,
		&i.LostFor,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, name, group_kind, events, last_contact_on, contact_every_days, remind_days, notes, notified_json, lost_for, archived_at, created_at, updated_at FROM contacts ORDER BY id
`

func (q *Queries) ListContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupKind,
			&i.Events,
			&i.LastContactOn,
			&i.ContactEveryDays,
			&i.RemindDays,
			&i.Notes,
			&i.NotifiedJson,
			&i.LostFor,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContactLost = `-- name: SetContactLost :exec
UPDATE contacts SET lost_for = ? WHERE id = ?
`

type SetContactLostParams struct {
	LostFor string
	ID      int64
}

func (q *Queries) SetContactLost(ctx context.Context, arg SetContactLostParams) error {
	_, err := q.db.ExecContext(ctx, setContactLost, arg.LostFor, arg.ID)
	return err
}

const setContactNotified = `-- name: SetContactNotified :exec
UPDATE contacts SET notified_json = ? WHERE id = ?
`

type SetContactNotifiedParams struct {
	NotifiedJson string
	ID           int64
}

func (q *Queries) SetContactNotified(ctx context.Context, arg SetContactNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, setContactNotified, arg.NotifiedJson, arg.ID)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET name = ?1, group_kind = ?2, events = ?3, last_contact_on = ?4, contact_every_days = ?5,
  remind_days = ?6, notes = ?7, archived_at = ?8, updated_at = ?9
WHERE id = ?10 RETURNING id, name, group_kind, events, last_contact_on, contact_every_days, remind_days, notes, notified_json, lost_for, archived_at, created_at, updated_at
`

type UpdateContactParams struct {
	Name             string
	GroupKind        string
	Events           string
	LastContactOn    string
	ContactEveryDays int64
	RemindDays       string
	Notes            string
	ArchivedAt       *time.Time
	UpdatedAt        time.Time
	ID               int64
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, updateContact,
		arg.Name,
		arg.GroupKind,
		arg.Events,
		arg.LastContactOn,
		arg.ContactEveryDays,
		arg.RemindDays,
		arg.Notes,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupKind,
		&i.Events,
		&i.LastContactOn,
		&i.ContactEveryDays,
		&i.RemindDays,
		&i.Notes,
		&i.NotifiedJson,
		&i.LostFor,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
