// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const countPushSubscriptions = `-- name: CountPushSubscriptions :one
SELECT count(*) FROM webpush_subscriptions
`

func (q *Queries) CountPushSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPushSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (title, body, link, rrule, dtstart, next_at, enabled, created_at, icon)
VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)
RETURNING id, title, body, link, rrule, dtstart, next_at, last_fired_at, snoozed_until, done_at, enabled, created_at, icon
`

type CreateReminderParams struct {
	Title     string
	Body      string
	Link      string
	Rrule     string
	Dtstart   time.Time
	NextAt    *time.Time
	CreatedAt time.Time
	Icon      string
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, createReminder,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Rrule,
		arg.Dtstart,
		arg.NextAt,
		arg.CreatedAt,
		arg.Icon,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Rrule,
		&i.Dtstart,
		&i.NextAt,
		&i.LastFiredAt,
		&i.SnoozedUntil,
		&i.DoneAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.Icon,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM webpush_subscriptions WHERE endpoint = ?
`

func (q *Queries) DeletePushSubscription(ctx context.Context, endpoint string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePushSubscription, endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePushSubscriptionByID = `-- name: DeletePushSubscriptionByID :execrows
DELETE FROM webpush_subscriptions WHERE id = ?
`

func (q *Queries) DeletePushSubscriptionByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePushSubscriptionByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReminder = `-- name: DeleteReminder :execrows
DELETE FROM reminders WHERE id = ?
`

func (q *Queries) DeleteReminder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReminder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRoutes = `-- name: DeleteRoutes :exec
DELETE FROM notification_routes
`

func (q *Queries) DeleteRoutes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRoutes)
	return err
}

const getReminder = `-- name: GetReminder :one
SELECT id, title, body, link, rrule, dtstart, next_at, last_fired_at, snoozed_until, done_at, enabled, created_at, icon FROM reminders WHERE id = ?
`

func (q *Queries) GetReminder(ctx context.Context, id int64) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, getReminder, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Rrule,
		&i.Dtstart,
		&i.NextAt,
		&i.LastFiredAt,
		&i.SnoozedUntil,
		&i.DoneAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.Icon,
	)
	return i, err
}

const insertRoute = `-- name: InsertRoute :one
INSERT INTO notification_routes (kind_pattern, min_priority, channels, enabled, sort_order)
VALUES (?, ?, ?, ?, ?)
RETURNING id, kind_pattern, min_priority, channels, enabled, sort_order
`

type InsertRouteParams struct {
	KindPattern string
	MinPriority string
	Channels    string
	Enabled     int64
	SortOrder   int64
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (NotificationRoute, error) {
	row := q.db.QueryRowContext(ctx, insertRoute,
		arg.KindPattern,
		arg.MinPriority,
		arg.Channels,
		arg.Enabled,
		arg.SortOrder,
	)
	var i NotificationRoute
	err := row.Scan(
		&i.ID,
		&i.KindPattern,
		&i.MinPriority,
		&i.Channels,
		&i.Enabled,
		&i.SortOrder,
	)
	return i, err
}

const listDueReminders = `-- name: ListDueReminders :many
SELECT id, title, body, link, rrule, dtstart, next_at, last_fired_at, snoozed_until, done_at, enabled, created_at, icon FROM reminders
WHERE enabled = 1
  AND ((next_at IS NOT NULL AND next_at <= ?1) OR (snoozed_until IS NOT NULL AND snoozed_until <= ?1))
ORDER BY id
`

func (q *Queries) ListDueReminders(ctx context.Context, now *time.Time) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listDueReminders, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Rrule,
			&i.Dtstart,
			&i.NextAt,
			&i.LastFiredAt,
			&i.SnoozedUntil,
			&i.DoneAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, endpoint, p256dh, auth, user_agent, created_at, last_ok_at, last_error, last_error_at FROM webpush_subscriptions ORDER BY id
`

func (q *Queries) ListPushSubscriptions(ctx context.Context) ([]WebpushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebpushSubscription
	for rows.Next() {
		var i WebpushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastOkAt,
			&i.LastError,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsNewestFirst = `-- name: ListPushSubscriptionsNewestFirst :many
SELECT id, endpoint, p256dh, auth, user_agent, created_at, last_ok_at, last_error, last_error_at FROM webpush_subscriptions ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPushSubscriptionsNewestFirst(ctx context.Context) ([]WebpushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsNewestFirst)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebpushSubscription
	for rows.Next() {
		var i WebpushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastOkAt,
			&i.LastError,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
SELECT id, title, body, link, rrule, dtstart, next_at, last_fired_at, snoozed_until, done_at, enabled, created_at, icon FROM reminders ORDER BY id
`

// A personal list stays small; ranges are filtered in Go.
func (q *Queries) ListReminders(ctx context.Context) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Rrule,
			&i.Dtstart,
			&i.NextAt,
			&i.LastFiredAt,
			&i.SnoozedUntil,
			&i.DoneAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, kind_pattern, min_priority, channels, enabled, sort_order FROM notification_routes ORDER BY sort_order, id
`

func (q *Queries) ListRoutes(ctx context.Context) ([]NotificationRoute, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationRoute
	for rows.Next() {
		var i NotificationRoute
		if err := rows.Scan(
			&i.ID,
			&i.KindPattern,
			&i.MinPriority,
			&i.Channels,
			&i.Enabled,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPushError = `-- name: MarkPushError :exec
UPDATE webpush_subscriptions SET last_error = ?, last_error_at = ? WHERE id = ?
`

type MarkPushErrorParams struct {
	LastError   *string
	LastErrorAt *time.Time
	ID          int64
}

func (q *Queries) MarkPushError(ctx context.Context, arg MarkPushErrorParams) error {
	_, err := q.db.ExecContext(ctx, markPushError, arg.LastError, arg.LastErrorAt, arg.ID)
	return err
}

const markPushOK = `-- name: MarkPushOK :exec
UPDATE webpush_subscriptions SET last_ok_at = ?, last_error = NULL, last_error_at = NULL WHERE id = ?
`

type MarkPushOKParams struct {
	LastOkAt *time.Time
	ID       int64
}

func (q *Queries) MarkPushOK(ctx context.Context, arg MarkPushOKParams) error {
	_, err := q.db.ExecContext(ctx, markPushOK, arg.LastOkAt, arg.ID)
	return err
}

const updateReminder = `-- name: UpdateReminder :one
UPDATE reminders
SET title = ?, body = ?, link = ?, rrule = ?, dtstart = ?, next_at = ?, last_fired_at = ?,
    snoozed_until = ?, done_at = ?, enabled = ?, icon = ?
WHERE id = ?
RETURNING id, title, body, link, rrule, dtstart, next_at, last_fired_at, snoozed_until, done_at, enabled, created_at, icon
`

type UpdateReminderParams struct {
	Title        string
	Body         string
	Link         string
	Rrule        string
	Dtstart      time.Time
	NextAt       *time.Time
	LastFiredAt  *time.Time
	SnoozedUntil *time.Time
	DoneAt       *time.Time
	Enabled      int64
	Icon         string
	ID           int64
}

func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, updateReminder,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Rrule,
		arg.Dtstart,
		arg.NextAt,
		arg.LastFiredAt,
		arg.SnoozedUntil,
		arg.DoneAt,
		arg.Enabled,
		arg.Icon,
		arg.ID,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Rrule,
		&i.Dtstart,
		&i.NextAt,
		&i.LastFiredAt,
		&i.SnoozedUntil,
		&i.DoneAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.Icon,
	)
	return i, err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO webpush_subscriptions (endpoint, p256dh, auth, user_agent, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (endpoint) DO UPDATE SET p256dh = excluded.p256dh, auth = excluded.auth, user_agent = excluded.user_agent
`

type UpsertPushSubscriptionParams struct {
	Endpoint  string
	P256dh    string
	Auth      string
	UserAgent string
	CreatedAt time.Time
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushSubscription,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}
