// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CredentialKind.
const (
	AccessToken CredentialKind = "access_token"
	ApiKey      CredentialKind = "api_key"
	Other       CredentialKind = "other"
	SigningKey  CredentialKind = "signing_key"
	SshKey      CredentialKind = "ssh_key"
)

// Valid indicates whether the value is a known member of the CredentialKind enum.
func (e CredentialKind) Valid() bool {
	switch e {
	case AccessToken:
		return true
	case ApiKey:
		return true
	case Other:
		return true
	case SigningKey:
		return true
	case SshKey:
		return true
	default:
		return false
	}
}

// Defines values for CredentialStatus.
const (
	Expired CredentialStatus = "expired"
	None    CredentialStatus = "none"
	Ok      CredentialStatus = "ok"
	Soon    CredentialStatus = "soon"
	Stale   CredentialStatus = "stale"
)

// Valid indicates whether the value is a known member of the CredentialStatus enum.
func (e CredentialStatus) Valid() bool {
	switch e {
	case Expired:
		return true
	case None:
		return true
	case Ok:
		return true
	case Soon:
		return true
	case Stale:
		return true
	default:
		return false
	}
}

// Credential defines model for Credential.
type Credential struct {
	Account   string    `json:"account"`
	Archived  bool      `json:"archived"`
	CreatedAt time.Time `json:"createdAt"`

	// CreatedOn 创建日期，YYYY-MM-DD，没有为空字符串
	CreatedOn string `json:"createdOn"`

	// ExpiresIn 离到期日还有几天，过期为负数，没有到期日为空
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// ExpiresOn 到期日，YYYY-MM-DD，没有为空字符串
	ExpiresOn string `json:"expiresOn"`

	// Hint 识别用的尾号或指纹前几位，最多 16 个字符
	Hint     string         `json:"hint"`
	Id       int64          `json:"id"`
	Kind     CredentialKind `json:"kind"`
	Name     string         `json:"name"`
	Notes    string         `json:"notes"`
	Platform string         `json:"platform"`

	// RemindDays 到期前多少天提醒，从大到小
	RemindDays []int `json:"remindDays"`

	// RotateDueIn 离该更换还有几天，已超过为负数，没设周期为空
	RotateDueIn *int `json:"rotateDueIn,omitempty"`

	// RotateEveryDays 超过多少天没更换就提醒，0 表示不设
	RotateEveryDays int `json:"rotateEveryDays"`

	// RotatedOn 上次更换日期，YYYY-MM-DD，没有为空字符串
	RotatedOn string `json:"rotatedOn"`
	Scopes    string `json:"scopes"`

	// Status expired 已过期，soon 在这一条最大的提醒天数内到期（没设提醒时 30 天），
	// stale 超过更换周期没更换，ok 都没到，none 没有到期日也没设更换周期。
	// 同时满足多个时按 expired、soon、stale 的顺序取第一个。
	Status    CredentialStatus `json:"status"`
	UpdatedAt time.Time        `json:"updatedAt"`

	// UsedBy 用在哪台服务器或哪个项目，最多 20 项
	UsedBy []string `json:"usedBy"`
}

// CredentialInput defines model for CredentialInput.
type CredentialInput struct {
	Account         *string        `json:"account,omitempty"`
	CreatedOn       *string        `json:"createdOn,omitempty"`
	ExpiresOn       *string        `json:"expiresOn,omitempty"`
	Hint            *string        `json:"hint,omitempty"`
	Kind            CredentialKind `json:"kind"`
	Name            string         `json:"name"`
	Notes           *string        `json:"notes,omitempty"`
	Platform        *string        `json:"platform,omitempty"`
	RemindDays      *[]int         `json:"remindDays,omitempty"`
	RotateEveryDays *int           `json:"rotateEveryDays,omitempty"`
	RotatedOn       *string        `json:"rotatedOn,omitempty"`
	Scopes          *string        `json:"scopes,omitempty"`
	UsedBy          *[]string      `json:"usedBy,omitempty"`
}

// CredentialKind defines model for CredentialKind.
type CredentialKind string

// CredentialPatch defines model for CredentialPatch.
type CredentialPatch struct {
	Account         *string         `json:"account,omitempty"`
	Archived        *bool           `json:"archived,omitempty"`
	CreatedOn       *string         `json:"createdOn,omitempty"`
	ExpiresOn       *string         `json:"expiresOn,omitempty"`
	Hint            *string         `json:"hint,omitempty"`
	Kind            *CredentialKind `json:"kind,omitempty"`
	Name            *string         `json:"name,omitempty"`
	Notes           *string         `json:"notes,omitempty"`
	Platform        *string         `json:"platform,omitempty"`
	RemindDays      *[]int          `json:"remindDays,omitempty"`
	RotateEveryDays *int            `json:"rotateEveryDays,omitempty"`
	RotatedOn       *string         `json:"rotatedOn,omitempty"`
	Scopes          *string         `json:"scopes,omitempty"`
	UsedBy          *[]string       `json:"usedBy,omitempty"`
}

// CredentialRotate defines model for CredentialRotate.
type CredentialRotate struct {
	// ExpiresOn 不给就保持原样
	ExpiresOn *string `json:"expiresOn,omitempty"`

	// Hint 不给就保持原样
	Hint *string `json:"hint,omitempty"`

	// RotatedOn 默认今天
	RotatedOn *string `json:"rotatedOn,omitempty"`
}

// CredentialStatus expired 已过期，soon 在这一条最大的提醒天数内到期（没设提醒时 30 天），
// stale 超过更换周期没更换，ok 都没到，none 没有到期日也没设更换周期。
// 同时满足多个时按 expired、soon、stale 的顺序取第一个。
type CredentialStatus string

// CredentialSummary defines model for CredentialSummary.
type CredentialSummary struct {
	Expired int `json:"expired"`
	None    int `json:"none"`
	Soon    int `json:"soon"`
	Stale   int `json:"stale"`
	Total   int `json:"total"`
}

// CredentialId defines model for CredentialId.
type CredentialId = int64

// ListCredentialsParams defines parameters for ListCredentials.
type ListCredentialsParams struct {
	Kind *CredentialKind `form:"kind,omitempty" json:"kind,omitempty"`

	// Q 在名称、平台、账号、用在哪里、权限范围、备注里找
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Archived true 时包含已归档的，默认不含
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`
}

// CreateCredentialJSONRequestBody defines body for CreateCredential for application/json ContentType.
type CreateCredentialJSONRequestBody = CredentialInput

// UpdateCredentialJSONRequestBody defines body for UpdateCredential for application/json ContentType.
type UpdateCredentialJSONRequestBody = CredentialPatch

// RotateCredentialJSONRequestBody defines body for RotateCredential for application/json ContentType.
type RotateCredentialJSONRequestBody = CredentialRotate

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /credentials)
	ListCredentials(w http.ResponseWriter, r *http.Request, params ListCredentialsParams)

	// (POST /credentials)
	CreateCredential(w http.ResponseWriter, r *http.Request)

	// (DELETE /credentials/{credentialId})
	DeleteCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId)

	// (GET /credentials/{credentialId})
	GetCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId)

	// (PATCH /credentials/{credentialId})
	UpdateCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId)

	// (POST /credentials/{credentialId}/rotate)
	RotateCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /credentials)
func (_ Unimplemented) ListCredentials(w http.ResponseWriter, r *http.Request, params ListCredentialsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /credentials)
func (_ Unimplemented) CreateCredential(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /credentials/{credentialId})
func (_ Unimplemented) DeleteCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /credentials/{credentialId})
func (_ Unimplemented) GetCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /credentials/{credentialId})
func (_ Unimplemented) UpdateCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /credentials/{credentialId}/rotate)
func (_ Unimplemented) RotateCredential(w http.ResponseWriter, r *http.Request, credentialId CredentialId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCredentials operation middleware
func (siw *ServerInterfaceWrapper) ListCredentials(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCredentialsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCredentials(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCredential operation middleware
func (siw *ServerInterfaceWrapper) CreateCredential(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCredential(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCredential operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredential(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "credentialId" -------------
	var credentialId CredentialId

	err = runtime.BindStyledParameterWithOptions("simple", "credentialId", chi.URLParam(r, "credentialId"), &credentialId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "credentialId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCredential(w, r, credentialId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCredential operation middleware
func (siw *ServerInterfaceWrapper) GetCredential(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "credentialId" -------------
	var credentialId CredentialId

	err = runtime.BindStyledParameterWithOptions("simple", "credentialId", chi.URLParam(r, "credentialId"), &credentialId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "credentialId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredential(w, r, credentialId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCredential operation middleware
func (siw *ServerInterfaceWrapper) UpdateCredential(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "credentialId" -------------
	var credentialId CredentialId

	err = runtime.BindStyledParameterWithOptions("simple", "credentialId", chi.URLParam(r, "credentialId"), &credentialId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "credentialId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCredential(w, r, credentialId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateCredential operation middleware
func (siw *ServerInterfaceWrapper) RotateCredential(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "credentialId" -------------
	var credentialId CredentialId

	err = runtime.BindStyledParameterWithOptions("simple", "credentialId", chi.URLParam(r, "credentialId"), &credentialId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "credentialId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateCredential(w, r, credentialId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/credentials", wrapper.ListCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/credentials", wrapper.CreateCredential)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/credentials/{credentialId}", wrapper.DeleteCredential)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/credentials/{credentialId}", wrapper.GetCredential)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/credentials/{credentialId}", wrapper.UpdateCredential)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/credentials/{credentialId}/rotate", wrapper.RotateCredential)
	})

	return r
}
