// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for QuotaAccountStatus.
const (
	Error   QuotaAccountStatus = "error"
	Ok      QuotaAccountStatus = "ok"
	Pending QuotaAccountStatus = "pending"
)

// Valid indicates whether the value is a known member of the QuotaAccountStatus enum.
func (e QuotaAccountStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Ok:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for QuotaKind.
const (
	Claude   QuotaKind = "claude"
	Codex    QuotaKind = "codex"
	Deepseek QuotaKind = "deepseek"
	Grok     QuotaKind = "grok"
)

// Valid indicates whether the value is a known member of the QuotaKind enum.
func (e QuotaKind) Valid() bool {
	switch e {
	case Claude:
		return true
	case Codex:
		return true
	case Deepseek:
		return true
	case Grok:
		return true
	default:
		return false
	}
}

// QuotaAccount defines model for QuotaAccount.
type QuotaAccount struct {
	// BalanceLow DeepSeek 余额低于这个数时通知，用余额里第一个币种比。空表示不通知
	BalanceLow *string        `json:"balanceLow,omitempty"`
	Balances   []QuotaBalance `json:"balances"`
	CreatedAt  time.Time      `json:"createdAt"`
	Credits    *string        `json:"credits,omitempty"`
	Error      *string        `json:"error,omitempty"`

	// ErrorCode offline、signed_out、unavailable、unsupported、host_missing 之一，或空
	ErrorCode *string `json:"errorCode,omitempty"`

	// Home 登录目录，空表示这台机器上的默认目录
	Home string `json:"home"`

	// HostId 机器（代理）编号，DeepSeek 为空
	HostId     string  `json:"hostId"`
	HostName   *string `json:"hostName,omitempty"`
	HostOnline *bool   `json:"hostOnline,omitempty"`
	Id         int64   `json:"id"`

	// KeySet DeepSeek 是否已设置 API Key，Key 本身不会返回
	KeySet bool      `json:"keySet"`
	Kind   QuotaKind `json:"kind"`
	Name   string    `json:"name"`
	Plan   *string   `json:"plan,omitempty"`

	// ReadAt 上一次成功读到数据的时间
	ReadAt *time.Time `json:"readAt,omitempty"`

	// Status pending 还没读过，ok 最近一次读取成功，error 最近一次失败
	Status QuotaAccountStatus `json:"status"`

	// TriedAt 上一次尝试的时间
	TriedAt *time.Time `json:"triedAt,omitempty"`

	// User 账号的邮箱，知道时才有
	User    *string       `json:"user,omitempty"`
	Windows []QuotaWindow `json:"windows"`
}

// QuotaAccountStatus pending 还没读过，ok 最近一次读取成功，error 最近一次失败
type QuotaAccountStatus string

// QuotaAccountInput defines model for QuotaAccountInput.
type QuotaAccountInput struct {
	// ApiKey 只有 DeepSeek 用
	ApiKey *string `json:"apiKey,omitempty"`

	// BalanceLow 只有 DeepSeek 用，数字，空表示不通知
	BalanceLow *string `json:"balanceLow,omitempty"`

	// Home 绝对路径，或以 ~/ 开头。不能含 ..。空表示默认目录
	Home   *string   `json:"home,omitempty"`
	HostId *string   `json:"hostId,omitempty"`
	Kind   QuotaKind `json:"kind"`
	Name   string    `json:"name"`
}

// QuotaAccountPatch defines model for QuotaAccountPatch.
type QuotaAccountPatch struct {
	ApiKey *string `json:"apiKey,omitempty"`

	// BalanceLow 数字，空字符串表示不再通知
	BalanceLow *string `json:"balanceLow,omitempty"`
	Home       *string `json:"home,omitempty"`
	HostId     *string `json:"hostId,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// QuotaBalance defines model for QuotaBalance.
type QuotaBalance struct {
	// Amount 原样的数字文本，比如 110.00
	Amount   string `json:"amount"`
	Currency string `json:"currency"`
}

// QuotaHost defines model for QuotaHost.
type QuotaHost struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Online bool   `json:"online"`
}

// QuotaKind defines model for QuotaKind.
type QuotaKind string

// QuotaNotifySettings defines model for QuotaNotifySettings.
type QuotaNotifySettings struct {
	// Balance DeepSeek 余额低于设定的数
	Balance bool `json:"balance"`

	// Empty 窗口用完
	Empty bool `json:"empty"`

	// Failed 连续读取失败
	Failed bool `json:"failed"`

	// Low 窗口剩余 10% 以下
	Low bool `json:"low"`
}

// QuotaWindow defines model for QuotaWindow.
type QuotaWindow struct {
	// Aside 用完也不停账号的窗口，比如按量付费
	Aside *bool `json:"aside,omitempty"`

	// Model 只统计某个模型的窗口，其余为空
	Model *string `json:"model,omitempty"`

	// Name 5 小时、7 天、7 天 · 模型名、今日、本月、按量付费
	Name     string     `json:"name"`
	ResetsAt *time.Time `json:"resetsAt,omitempty"`

	// SpanSecs 窗口长度，秒，不知道时为 0
	SpanSecs *int64 `json:"spanSecs,omitempty"`

	// UsedPercent 已用百分比，0 到 100
	UsedPercent float64 `json:"usedPercent"`
}

// AccountId defines model for AccountId.
type AccountId = int64

// ReorderQuotaAccountsJSONBody defines parameters for ReorderQuotaAccounts.
type ReorderQuotaAccountsJSONBody struct {
	Ids []int64 `json:"ids"`
}

// CreateQuotaAccountJSONRequestBody defines body for CreateQuotaAccount for application/json ContentType.
type CreateQuotaAccountJSONRequestBody = QuotaAccountInput

// PutQuotaNotifyJSONRequestBody defines body for PutQuotaNotify for application/json ContentType.
type PutQuotaNotifyJSONRequestBody = QuotaNotifySettings

// ReorderQuotaAccountsJSONRequestBody defines body for ReorderQuotaAccounts for application/json ContentType.
type ReorderQuotaAccountsJSONRequestBody ReorderQuotaAccountsJSONBody

// UpdateQuotaAccountJSONRequestBody defines body for UpdateQuotaAccount for application/json ContentType.
type UpdateQuotaAccountJSONRequestBody = QuotaAccountPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /quotas)
	ListQuotaAccounts(w http.ResponseWriter, r *http.Request)

	// (POST /quotas)
	CreateQuotaAccount(w http.ResponseWriter, r *http.Request)

	// (GET /quotas/hosts)
	ListQuotaHosts(w http.ResponseWriter, r *http.Request)

	// (GET /quotas/notify)
	GetQuotaNotify(w http.ResponseWriter, r *http.Request)

	// (PUT /quotas/notify)
	PutQuotaNotify(w http.ResponseWriter, r *http.Request)

	// (POST /quotas/reorder)
	ReorderQuotaAccounts(w http.ResponseWriter, r *http.Request)

	// (DELETE /quotas/{accountId})
	DeleteQuotaAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)

	// (PATCH /quotas/{accountId})
	UpdateQuotaAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)

	// (POST /quotas/{accountId}/refresh)
	RefreshQuotaAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /quotas)
func (_ Unimplemented) ListQuotaAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /quotas)
func (_ Unimplemented) CreateQuotaAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /quotas/hosts)
func (_ Unimplemented) ListQuotaHosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /quotas/notify)
func (_ Unimplemented) GetQuotaNotify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /quotas/notify)
func (_ Unimplemented) PutQuotaNotify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /quotas/reorder)
func (_ Unimplemented) ReorderQuotaAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /quotas/{accountId})
func (_ Unimplemented) DeleteQuotaAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /quotas/{accountId})
func (_ Unimplemented) UpdateQuotaAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /quotas/{accountId}/refresh)
func (_ Unimplemented) RefreshQuotaAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListQuotaAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListQuotaAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQuotaAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuotaAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateQuotaAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuotaAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQuotaHosts operation middleware
func (siw *ServerInterfaceWrapper) ListQuotaHosts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQuotaHosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuotaNotify operation middleware
func (siw *ServerInterfaceWrapper) GetQuotaNotify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuotaNotify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutQuotaNotify operation middleware
func (siw *ServerInterfaceWrapper) PutQuotaNotify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutQuotaNotify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReorderQuotaAccounts operation middleware
func (siw *ServerInterfaceWrapper) ReorderQuotaAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReorderQuotaAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteQuotaAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuotaAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteQuotaAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateQuotaAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateQuotaAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateQuotaAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshQuotaAccount operation middleware
func (siw *ServerInterfaceWrapper) RefreshQuotaAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshQuotaAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/quotas", wrapper.ListQuotaAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/quotas", wrapper.CreateQuotaAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/quotas/hosts", wrapper.ListQuotaHosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/quotas/reorder", wrapper.ReorderQuotaAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/quotas/notify", wrapper.GetQuotaNotify)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/quotas/notify", wrapper.PutQuotaNotify)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/quotas/{accountId}", wrapper.DeleteQuotaAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/quotas/{accountId}", wrapper.UpdateQuotaAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/quotas/{accountId}/refresh", wrapper.RefreshQuotaAccount)
	})

	return r
}
