// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	externalRef0 "github.com/j0x3n/x-console/backend/internal/server/apigen/common"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CatalogActionEffect.
const (
	Dangerous CatalogActionEffect = "dangerous"
	Read      CatalogActionEffect = "read"
	Write     CatalogActionEffect = "write"
)

// Valid indicates whether the value is a known member of the CatalogActionEffect enum.
func (e CatalogActionEffect) Valid() bool {
	switch e {
	case Dangerous:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for ConditionOp.
const (
	ConditionOpContains         ConditionOp = "contains"
	ConditionOpEmpty            ConditionOp = "!="
	ConditionOpEqualEqual       ConditionOp = "=="
	ConditionOpGreaterThan      ConditionOp = ">"
	ConditionOpGreaterThanEqual ConditionOp = ">="
	ConditionOpLessThan         ConditionOp = "<"
	ConditionOpLessThanEqual    ConditionOp = "<="
)

// Valid indicates whether the value is a known member of the ConditionOp enum.
func (e ConditionOp) Valid() bool {
	switch e {
	case ConditionOpContains:
		return true
	case ConditionOpEmpty:
		return true
	case ConditionOpEqualEqual:
		return true
	case ConditionOpGreaterThan:
		return true
	case ConditionOpGreaterThanEqual:
		return true
	case ConditionOpLessThan:
		return true
	case ConditionOpLessThanEqual:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	Failed  RunStatus = "failed"
	Ok      RunStatus = "ok"
	Running RunStatus = "running"
	Skipped RunStatus = "skipped"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Ok:
		return true
	case Running:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for TriggerMetric.
const (
	Cpu  TriggerMetric = "cpu"
	Disk TriggerMetric = "disk"
	Mem  TriggerMetric = "mem"
)

// Valid indicates whether the value is a known member of the TriggerMetric enum.
func (e TriggerMetric) Valid() bool {
	switch e {
	case Cpu:
		return true
	case Disk:
		return true
	case Mem:
		return true
	default:
		return false
	}
}

// Defines values for TriggerOp.
const (
	TriggerOpGreaterThan      TriggerOp = ">"
	TriggerOpGreaterThanEqual TriggerOp = ">="
	TriggerOpLessThan         TriggerOp = "<"
	TriggerOpLessThanEqual    TriggerOp = "<="
)

// Valid indicates whether the value is a known member of the TriggerOp enum.
func (e TriggerOp) Valid() bool {
	switch e {
	case TriggerOpGreaterThan:
		return true
	case TriggerOpGreaterThanEqual:
		return true
	case TriggerOpLessThan:
		return true
	case TriggerOpLessThanEqual:
		return true
	default:
		return false
	}
}

// Defines values for TriggerType.
const (
	Event    TriggerType = "event"
	HaState  TriggerType = "ha_state"
	Metric   TriggerType = "metric"
	Schedule TriggerType = "schedule"
	Webhook  TriggerType = "webhook"
)

// Valid indicates whether the value is a known member of the TriggerType enum.
func (e TriggerType) Valid() bool {
	switch e {
	case Event:
		return true
	case HaState:
		return true
	case Metric:
		return true
	case Schedule:
		return true
	case Webhook:
		return true
	default:
		return false
	}
}

// Automation defines model for Automation.
type Automation struct {
	Actions []Step `json:"actions"`

	// Authorized 有 dangerous 动作时，保存时是否已提升权限
	Authorized      bool        `json:"authorized"`
	Conditions      []Condition `json:"conditions"`
	CooldownSeconds int         `json:"cooldownSeconds"`
	CreatedAt       time.Time   `json:"createdAt"`
	Enabled         bool        `json:"enabled"`
	Id              int64       `json:"id"`
	LastRun         *Run        `json:"lastRun,omitempty"`
	Name            string      `json:"name"`

	// Trigger schedule：{cron}；event：{topic, match?}；metric：{hostId?, metric, op, value}；
	// ha_state：{entityId, to?}；webhook：{}（保存后返回 webhookPath）。
	Trigger   Trigger   `json:"trigger"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// AutomationInput defines model for AutomationInput.
type AutomationInput struct {
	Actions         []Step      `json:"actions"`
	Conditions      []Condition `json:"conditions"`
	CooldownSeconds int         `json:"cooldownSeconds"`
	Enabled         bool        `json:"enabled"`
	Name            string      `json:"name"`

	// Trigger schedule：{cron}；event：{topic, match?}；metric：{hostId?, metric, op, value}；
	// ha_state：{entityId, to?}；webhook：{}（保存后返回 webhookPath）。
	Trigger Trigger `json:"trigger"`
}

// Catalog defines model for Catalog.
type Catalog struct {
	// Actions 包括 ai.ask
	Actions []CatalogAction `json:"actions"`

	// Topics 可以订阅的事件主题
	Topics []struct {
		Title string `json:"title"`
		Topic string `json:"topic"`
	} `json:"topics"`
}

// CatalogAction defines model for CatalogAction.
type CatalogAction struct {
	Description *string             `json:"description,omitempty"`
	Effect      CatalogActionEffect `json:"effect"`

	// Input JSON Schema
	Input map[string]interface{} `json:"input"`
	Name  string                 `json:"name"`
	Title string                 `json:"title"`
}

// CatalogActionEffect defines model for CatalogAction.Effect.
type CatalogActionEffect string

// Condition defines model for Condition.
type Condition struct {
	// Field 触发数据里的字段路径，例如 data.cpu
	Field string      `json:"field"`
	Op    ConditionOp `json:"op"`

	// Value 按字符串填写，数字比较时服务端转成数字
	Value string `json:"value"`
}

// ConditionOp defines model for Condition.Op.
type ConditionOp string

// Run defines model for Run.
type Run struct {
	AutomationId int64       `json:"automationId"`
	FinishedAt   *time.Time  `json:"finishedAt,omitempty"`
	Id           int64       `json:"id"`
	StartedAt    time.Time   `json:"startedAt"`
	Status       RunStatus   `json:"status"`
	Steps        []RunStep   `json:"steps"`
	TriggerData  interface{} `json:"triggerData,omitempty"`
}

// RunStatus defines model for Run.Status.
type RunStatus string

// RunStep defines model for RunStep.
type RunStep struct {
	Action string                 `json:"action"`
	Error  *string                `json:"error,omitempty"`
	Input  map[string]interface{} `json:"input"`
	Result interface{}            `json:"result,omitempty"`
}

// Step defines model for Step.
type Step struct {
	// Action 动作名，或 ai.ask
	Action string `json:"action"`

	// Input 字符串里可以用 {{trigger.data.xxx}} 和 {{steps.0.result}}
	Input map[string]interface{} `json:"input"`
}

// Trigger schedule：{cron}；event：{topic, match?}；metric：{hostId?, metric, op, value}；
// ha_state：{entityId, to?}；webhook：{}（保存后返回 webhookPath）。
type Trigger struct {
	// Cron 5 段 cron，按用户时区
	Cron     *string `json:"cron,omitempty"`
	EntityId *string `json:"entityId,omitempty"`
	HostId   *string `json:"hostId,omitempty"`

	// Match 可选，例如 data.hostId == "abc"
	Match  *string        `json:"match,omitempty"`
	Metric *TriggerMetric `json:"metric,omitempty"`
	Op     *TriggerOp     `json:"op,omitempty"`

	// To 目标状态，不填表示任何变化
	To *string `json:"to,omitempty"`

	// Topic 事件主题前缀，例如 monitor.down
	Topic *string     `json:"topic,omitempty"`
	Type  TriggerType `json:"type"`
	Value *float32    `json:"value,omitempty"`

	// WebhookPath 只读，例如 /hooks/3f9a…，完整地址 = 面板地址 + /api/v1 + 这个路径
	WebhookPath *string `json:"webhookPath,omitempty"`
}

// TriggerMetric defines model for Trigger.Metric.
type TriggerMetric string

// TriggerOp defines model for Trigger.Op.
type TriggerOp string

// TriggerType defines model for Trigger.Type.
type TriggerType string

// AutomationId defines model for AutomationId.
type AutomationId = int64

// ToggleAutomationJSONBody defines parameters for ToggleAutomation.
type ToggleAutomationJSONBody struct {
	Enabled bool `json:"enabled"`
}

// ListAutomationRunsParams defines parameters for ListAutomationRuns.
type ListAutomationRunsParams struct {
	Limit *externalRef0.Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateAutomationJSONRequestBody defines body for CreateAutomation for application/json ContentType.
type CreateAutomationJSONRequestBody = AutomationInput

// ToggleAutomationJSONRequestBody defines body for ToggleAutomation for application/json ContentType.
type ToggleAutomationJSONRequestBody ToggleAutomationJSONBody

// UpdateAutomationJSONRequestBody defines body for UpdateAutomation for application/json ContentType.
type UpdateAutomationJSONRequestBody = AutomationInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /automations)
	ListAutomations(w http.ResponseWriter, r *http.Request)

	// (POST /automations)
	CreateAutomation(w http.ResponseWriter, r *http.Request)

	// (GET /automations/catalog)
	GetAutomationCatalog(w http.ResponseWriter, r *http.Request)

	// (DELETE /automations/{automationId})
	DeleteAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId)

	// (GET /automations/{automationId})
	GetAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId)

	// (PATCH /automations/{automationId})
	ToggleAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId)

	// (PUT /automations/{automationId})
	UpdateAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId)

	// (POST /automations/{automationId}/run)
	RunAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId)

	// (GET /automations/{automationId}/runs)
	ListAutomationRuns(w http.ResponseWriter, r *http.Request, automationId AutomationId, params ListAutomationRunsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /automations)
func (_ Unimplemented) ListAutomations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /automations)
func (_ Unimplemented) CreateAutomation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /automations/catalog)
func (_ Unimplemented) GetAutomationCatalog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /automations/{automationId})
func (_ Unimplemented) DeleteAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /automations/{automationId})
func (_ Unimplemented) GetAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /automations/{automationId})
func (_ Unimplemented) ToggleAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /automations/{automationId})
func (_ Unimplemented) UpdateAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /automations/{automationId}/run)
func (_ Unimplemented) RunAutomation(w http.ResponseWriter, r *http.Request, automationId AutomationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /automations/{automationId}/runs)
func (_ Unimplemented) ListAutomationRuns(w http.ResponseWriter, r *http.Request, automationId AutomationId, params ListAutomationRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAutomations operation middleware
func (siw *ServerInterfaceWrapper) ListAutomations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAutomations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAutomation operation middleware
func (siw *ServerInterfaceWrapper) CreateAutomation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAutomation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAutomationCatalog operation middleware
func (siw *ServerInterfaceWrapper) GetAutomationCatalog(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAutomationCatalog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAutomation operation middleware
func (siw *ServerInterfaceWrapper) DeleteAutomation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "automationId" -------------
	var automationId AutomationId

	err = runtime.BindStyledParameterWithOptions("simple", "automationId", chi.URLParam(r, "automationId"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "automationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAutomation(w, r, automationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAutomation operation middleware
func (siw *ServerInterfaceWrapper) GetAutomation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "automationId" -------------
	var automationId AutomationId

	err = runtime.BindStyledParameterWithOptions("simple", "automationId", chi.URLParam(r, "automationId"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "automationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAutomation(w, r, automationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ToggleAutomation operation middleware
func (siw *ServerInterfaceWrapper) ToggleAutomation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "automationId" -------------
	var automationId AutomationId

	err = runtime.BindStyledParameterWithOptions("simple", "automationId", chi.URLParam(r, "automationId"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "automationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ToggleAutomation(w, r, automationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAutomation operation middleware
func (siw *ServerInterfaceWrapper) UpdateAutomation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "automationId" -------------
	var automationId AutomationId

	err = runtime.BindStyledParameterWithOptions("simple", "automationId", chi.URLParam(r, "automationId"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "automationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAutomation(w, r, automationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunAutomation operation middleware
func (siw *ServerInterfaceWrapper) RunAutomation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "automationId" -------------
	var automationId AutomationId

	err = runtime.BindStyledParameterWithOptions("simple", "automationId", chi.URLParam(r, "automationId"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "automationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunAutomation(w, r, automationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAutomationRuns operation middleware
func (siw *ServerInterfaceWrapper) ListAutomationRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "automationId" -------------
	var automationId AutomationId

	err = runtime.BindStyledParameterWithOptions("simple", "automationId", chi.URLParam(r, "automationId"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "automationId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAutomationRunsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAutomationRuns(w, r, automationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/automations", wrapper.ListAutomations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/automations", wrapper.CreateAutomation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/automations/catalog", wrapper.GetAutomationCatalog)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/automations/{automationId}", wrapper.DeleteAutomation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/automations/{automationId}", wrapper.GetAutomation)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/automations/{automationId}", wrapper.ToggleAutomation)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/automations/{automationId}", wrapper.UpdateAutomation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/automations/{automationId}/run", wrapper.RunAutomation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/automations/{automationId}/runs", wrapper.ListAutomationRuns)
	})

	return r
}
