// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Agent struct {
	ID           string
	Name         string
	Kind         string
	Os           string
	Arch         string
	Hostname     string
	Version      string
	Capabilities string
	TokenHash    string
	CreatedAt    time.Time
	LastSeenAt   *time.Time
	RevokedAt    *time.Time
}

type AuditLog struct {
	ID     int64
	At     time.Time
	Actor  string
	Action string
	Target string
	Detail string
	Result string
}

type Issue struct {
	ID             int64
	ProjectID      int64
	Number         int64
	Title          string
	Description    string
	Status         string
	Priority       int64
	DueDate        *string
	MilestoneID    *int64
	SortOrder      float64
	ExternalSource string
	ExternalID     string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
}

type IssueComment struct {
	ID        int64
	IssueID   int64
	Body      string
	CreatedAt time.Time
}

type IssueLabel struct {
	IssueID int64
	LabelID int64
}

type IssueLink struct {
	ID        int64
	IssueID   int64
	Kind      string
	Title     string
	Url       string
	Ref       string
	CreatedAt time.Time
}

type Label struct {
	ID        int64
	ProjectID *int64
	Name      string
	Color     string
}

type Milestone struct {
	ID        int64
	ProjectID int64
	Name      string
	DueDate   *string
	CreatedAt time.Time
}

type Note struct {
	ID         int64
	Title      string
	Body       string
	Pinned     int64
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type NoteTag struct {
	NoteID int64
	Tag    string
}

type NotesFt struct {
	Title string
	Body  string
}

type Notification struct {
	ID        int64
	CreatedAt time.Time
	Kind      string
	Title     string
	Body      string
	Link      string
	Priority  string
	Source    string
	Data      string
	ReadAt    *time.Time
}

type PairingCode struct {
	CodeHash  string
	Name      string
	Kind      string
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Project struct {
	ID          int64
	Key         string
	Name        string
	Description string
	Color       string
	Icon        string
	ArchivedAt  *time.Time
	NextNumber  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID            string
	UserID        int64
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ElevatedUntil *time.Time
	UserAgent     string
	Ip            string
}

type Setting struct {
	Key       string
	Value     string
	Encrypted int64
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	TotpSecret   string
	TotpEnabled  int64
	CreatedAt    time.Time
}
