// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const deleteCredential = `-- name: DeleteCredential :execrows
DELETE FROM credentials WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCredential, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCredential = `-- name: GetCredential :one
SELECT id, kind, name, platform, account, used_by, scopes, hint, created_on, rotated_on, expires_on, rotate_every_days, remind_days, notes, notified_for, notified_json, stale_for, stale_notified_on, archived_at, created_at, updated_at FROM credentials WHERE id = ?
`

func (q *Queries) GetCredential(ctx context.Context, id int64) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Platform,
		&i.Account,
		&i.UsedBy,
		&i.Scopes,
		&i.Hint,
		&i.CreatedOn,
		&i.RotatedOn,
		&i.ExpiresOn,
		&i.RotateEveryDays,
		&i.RemindDays,
		&i.Notes,
		&i.NotifiedFor,
		&i.NotifiedJson,
		&i.StaleFor,
		&i.StaleNotifiedOn,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO credentials (kind, name, platform, account, used_by, scopes, hint, created_on, rotated_on, expires_on, rotate_every_days, remind_days, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, kind, name, platform, account, used_by, scopes, hint, created_on, rotated_on, expires_on, rotate_every_days, remind_days, notes, notified_for, notified_json, stale_for, stale_notified_on, archived_at, created_at, updated_at
`

type InsertCredentialParams struct {
	Kind            string
	Name            string
	Platform        string
	Account         string
	UsedBy          string
	Scopes          string
	Hint            string
	CreatedOn       string
	RotatedOn       string
	ExpiresOn       string
	RotateEveryDays int64
	RemindDays      string
	Notes           string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, insertCredential,
		arg.Kind,
		arg.Name,
		arg.Platform,
		arg.Account,
		arg.UsedBy,
		arg.Scopes,
		arg.Hint,
		arg.CreatedOn,
		arg.RotatedOn,
		arg.ExpiresOn,
		arg.RotateEveryDays,
		arg.RemindDays,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Platform,
		&i.Account,
		&i.UsedBy,
		&i.Scopes,
		&i.Hint,
		&i.CreatedOn,
		&i.RotatedOn,
		&i.ExpiresOn,
		&i.RotateEveryDays,
		&i.RemindDays,
		&i.Notes,
		&i.NotifiedFor,
		&i.NotifiedJson,
		&i.StaleFor,
		&i.StaleNotifiedOn,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, kind, name, platform, account, used_by, scopes, hint, created_on, rotated_on, expires_on, rotate_every_days, remind_days, notes, notified_for, notified_json, stale_for, stale_notified_on, archived_at, created_at, updated_at FROM credentials ORDER BY id
`

func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Platform,
			&i.Account,
			&i.UsedBy,
			&i.Scopes,
			&i.Hint,
			&i.CreatedOn,
			&i.RotatedOn,
			&i.ExpiresOn,
			&i.RotateEveryDays,
			&i.RemindDays,
			&i.Notes,
			&i.NotifiedFor,
			&i.NotifiedJson,
			&i.StaleFor,
			&i.StaleNotifiedOn,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCredentialNotified = `-- name: SetCredentialNotified :exec
UPDATE credentials SET notified_for = ?, notified_json = ? WHERE id = ?
`

type SetCredentialNotifiedParams struct {
	NotifiedFor  string
	NotifiedJson string
	ID           int64
}

func (q *Queries) SetCredentialNotified(ctx context.Context, arg SetCredentialNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, setCredentialNotified, arg.NotifiedFor, arg.NotifiedJson, arg.ID)
	return err
}

const setCredentialStale = `-- name: SetCredentialStale :exec
UPDATE credentials SET stale_for = ?, stale_notified_on = ? WHERE id = ?
`

type SetCredentialStaleParams struct {
	StaleFor        string
	StaleNotifiedOn string
	ID              int64
}

func (q *Queries) SetCredentialStale(ctx context.Context, arg SetCredentialStaleParams) error {
	_, err := q.db.ExecContext(ctx, setCredentialStale, arg.StaleFor, arg.StaleNotifiedOn, arg.ID)
	return err
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials SET kind = ?1, name = ?2, platform = ?3, account = ?4, used_by = ?5, scopes = ?6, hint = ?7,
  created_on = ?8, rotated_on = ?9, expires_on = ?10, rotate_every_days = ?11, remind_days = ?12, notes = ?13,
  archived_at = ?14, updated_at = ?15,
  notified_for = CASE WHEN expires_on = ?10 THEN notified_for ELSE '' END,
  notified_json = CASE WHEN expires_on = ?10 THEN notified_json ELSE '[]' END
WHERE id = ?16 RETURNING id, kind, name, platform, account, used_by, scopes, hint, created_on, rotated_on, expires_on, rotate_every_days, remind_days, notes, notified_for, notified_json, stale_for, stale_notified_on, archived_at, created_at, updated_at
`

type UpdateCredentialParams struct {
	Kind            string
	Name            string
	Platform        string
	Account         string
	UsedBy          string
	Scopes          string
	Hint            string
	CreatedOn       string
	RotatedOn       string
	ExpiresOn       string
	RotateEveryDays int64
	RemindDays      string
	Notes           string
	ArchivedAt      *time.Time
	UpdatedAt       time.Time
	ID              int64
}

// A new expiry date starts the expiry reminders over. The reminders for a
// missed rotation key on the date they were told for, so they need no reset.
func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, updateCredential,
		arg.Kind,
		arg.Name,
		arg.Platform,
		arg.Account,
		arg.UsedBy,
		arg.Scopes,
		arg.Hint,
		arg.CreatedOn,
		arg.RotatedOn,
		arg.ExpiresOn,
		arg.RotateEveryDays,
		arg.RemindDays,
		arg.Notes,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Platform,
		&i.Account,
		&i.UsedBy,
		&i.Scopes,
		&i.Hint,
		&i.CreatedOn,
		&i.RotatedOn,
		&i.ExpiresOn,
		&i.RotateEveryDays,
		&i.RemindDays,
		&i.Notes,
		&i.NotifiedFor,
		&i.NotifiedJson,
		&i.StaleFor,
		&i.StaleNotifiedOn,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
