// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const currentFocus = `-- name: CurrentFocus :one
SELECT id, issue_key, started_at, ended_at, planned_minutes, actual_seconds, completed, note, notified_at FROM focus_sessions WHERE ended_at IS NULL ORDER BY id DESC LIMIT 1
`

func (q *Queries) CurrentFocus(ctx context.Context) (FocusSession, error) {
	row := q.db.QueryRowContext(ctx, currentFocus)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.IssueKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.PlannedMinutes,
		&i.ActualSeconds,
		&i.Completed,
		&i.Note,
		&i.NotifiedAt,
	)
	return i, err
}

const getFocus = `-- name: GetFocus :one
SELECT id, issue_key, started_at, ended_at, planned_minutes, actual_seconds, completed, note, notified_at FROM focus_sessions WHERE id = ?
`

func (q *Queries) GetFocus(ctx context.Context, id int64) (FocusSession, error) {
	row := q.db.QueryRowContext(ctx, getFocus, id)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.IssueKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.PlannedMinutes,
		&i.ActualSeconds,
		&i.Completed,
		&i.Note,
		&i.NotifiedAt,
	)
	return i, err
}

const listFocusSince = `-- name: ListFocusSince :many
SELECT id, issue_key, started_at, ended_at, planned_minutes, actual_seconds, completed, note, notified_at FROM focus_sessions WHERE started_at >= ? ORDER BY started_at
`

func (q *Queries) ListFocusSince(ctx context.Context, startedAt time.Time) ([]FocusSession, error) {
	rows, err := q.db.QueryContext(ctx, listFocusSince, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FocusSession
	for rows.Next() {
		var i FocusSession
		if err := rows.Scan(
			&i.ID,
			&i.IssueKey,
			&i.StartedAt,
			&i.EndedAt,
			&i.PlannedMinutes,
			&i.ActualSeconds,
			&i.Completed,
			&i.Note,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFocus = `-- name: ListOpenFocus :many
SELECT id, issue_key, started_at, ended_at, planned_minutes, actual_seconds, completed, note, notified_at FROM focus_sessions WHERE ended_at IS NULL ORDER BY id
`

func (q *Queries) ListOpenFocus(ctx context.Context) ([]FocusSession, error) {
	rows, err := q.db.QueryContext(ctx, listOpenFocus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FocusSession
	for rows.Next() {
		var i FocusSession
		if err := rows.Scan(
			&i.ID,
			&i.IssueKey,
			&i.StartedAt,
			&i.EndedAt,
			&i.PlannedMinutes,
			&i.ActualSeconds,
			&i.Completed,
			&i.Note,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFocus = `-- name: ListRecentFocus :many
SELECT id, issue_key, started_at, ended_at, planned_minutes, actual_seconds, completed, note, notified_at FROM focus_sessions WHERE ended_at IS NOT NULL ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListRecentFocus(ctx context.Context, limit int64) ([]FocusSession, error) {
	rows, err := q.db.QueryContext(ctx, listRecentFocus, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FocusSession
	for rows.Next() {
		var i FocusSession
		if err := rows.Scan(
			&i.ID,
			&i.IssueKey,
			&i.StartedAt,
			&i.EndedAt,
			&i.PlannedMinutes,
			&i.ActualSeconds,
			&i.Completed,
			&i.Note,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFocusNotified = `-- name: MarkFocusNotified :execrows
UPDATE focus_sessions SET notified_at = ? WHERE id = ? AND notified_at IS NULL AND ended_at IS NULL
`

type MarkFocusNotifiedParams struct {
	NotifiedAt *time.Time
	ID         int64
}

// Only the first caller wins, so the timer and the sweep never notify twice.
func (q *Queries) MarkFocusNotified(ctx context.Context, arg MarkFocusNotifiedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markFocusNotified, arg.NotifiedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startFocus = `-- name: StartFocus :one
INSERT INTO focus_sessions (issue_key, started_at, planned_minutes, note)
VALUES (?, ?, ?, ?)
RETURNING id, issue_key, started_at, ended_at, planned_minutes, actual_seconds, completed, note, notified_at
`

type StartFocusParams struct {
	IssueKey       string
	StartedAt      time.Time
	PlannedMinutes int64
	Note           string
}

func (q *Queries) StartFocus(ctx context.Context, arg StartFocusParams) (FocusSession, error) {
	row := q.db.QueryRowContext(ctx, startFocus,
		arg.IssueKey,
		arg.StartedAt,
		arg.PlannedMinutes,
		arg.Note,
	)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.IssueKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.PlannedMinutes,
		&i.ActualSeconds,
		&i.Completed,
		&i.Note,
		&i.NotifiedAt,
	)
	return i, err
}

const stopFocus = `-- name: StopFocus :one
UPDATE focus_sessions
SET ended_at = ?, actual_seconds = ?, completed = ?, note = ?
WHERE id = ? AND ended_at IS NULL
RETURNING id, issue_key, started_at, ended_at, planned_minutes, actual_seconds, completed, note, notified_at
`

type StopFocusParams struct {
	EndedAt       *time.Time
	ActualSeconds int64
	Completed     int64
	Note          string
	ID            int64
}

func (q *Queries) StopFocus(ctx context.Context, arg StopFocusParams) (FocusSession, error) {
	row := q.db.QueryRowContext(ctx, stopFocus,
		arg.EndedAt,
		arg.ActualSeconds,
		arg.Completed,
		arg.Note,
		arg.ID,
	)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.IssueKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.PlannedMinutes,
		&i.ActualSeconds,
		&i.Completed,
		&i.Note,
		&i.NotifiedAt,
	)
	return i, err
}
