// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const countUnreadReadItems = `-- name: CountUnreadReadItems :one
SELECT COUNT(*) FROM read_items WHERE read_at IS NULL
`

func (q *Queries) CountUnreadReadItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadReadItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteReadAsset = `-- name: DeleteReadAsset :exec
DELETE FROM read_assets WHERE item_id = ? AND hash = ?
`

type DeleteReadAssetParams struct {
	ItemID int64
	Hash   string
}

func (q *Queries) DeleteReadAsset(ctx context.Context, arg DeleteReadAssetParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadAsset, arg.ItemID, arg.Hash)
	return err
}

const deleteReadItem = `-- name: DeleteReadItem :execrows
DELETE FROM read_items WHERE id = ?
`

func (q *Queries) DeleteReadItem(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReadItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReadAsset = `-- name: GetReadAsset :one
SELECT item_id, hash, mime, size, src_url, created_at FROM read_assets WHERE item_id = ? AND hash = ?
`

type GetReadAssetParams struct {
	ItemID int64
	Hash   string
}

func (q *Queries) GetReadAsset(ctx context.Context, arg GetReadAssetParams) (ReadAsset, error) {
	row := q.db.QueryRowContext(ctx, getReadAsset, arg.ItemID, arg.Hash)
	var i ReadAsset
	err := row.Scan(
		&i.ItemID,
		&i.Hash,
		&i.Mime,
		&i.Size,
		&i.SrcUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getReadItem = `-- name: GetReadItem :one
SELECT id, url, title, title_locked, site, excerpt, content, summary, tags_json, note, source, status, error, attempts, read_at, created_at, fetched_at, updated_at, content_html, kind, meta_json FROM read_items WHERE id = ?
`

func (q *Queries) GetReadItem(ctx context.Context, id int64) (ReadItem, error) {
	row := q.db.QueryRowContext(ctx, getReadItem, id)
	var i ReadItem
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.TitleLocked,
		&i.Site,
		&i.Excerpt,
		&i.Content,
		&i.Summary,
		&i.TagsJson,
		&i.Note,
		&i.Source,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.ReadAt,
		&i.CreatedAt,
		&i.FetchedAt,
		&i.UpdatedAt,
		&i.ContentHtml,
		&i.Kind,
		&i.MetaJson,
	)
	return i, err
}

const getReadItemByURL = `-- name: GetReadItemByURL :one
SELECT id, url, title, title_locked, site, excerpt, content, summary, tags_json, note, source, status, error, attempts, read_at, created_at, fetched_at, updated_at, content_html, kind, meta_json FROM read_items WHERE url = ?
`

func (q *Queries) GetReadItemByURL(ctx context.Context, url string) (ReadItem, error) {
	row := q.db.QueryRowContext(ctx, getReadItemByURL, url)
	var i ReadItem
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.TitleLocked,
		&i.Site,
		&i.Excerpt,
		&i.Content,
		&i.Summary,
		&i.TagsJson,
		&i.Note,
		&i.Source,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.ReadAt,
		&i.CreatedAt,
		&i.FetchedAt,
		&i.UpdatedAt,
		&i.ContentHtml,
		&i.Kind,
		&i.MetaJson,
	)
	return i, err
}

const insertReadAsset = `-- name: InsertReadAsset :exec
INSERT INTO read_assets (item_id, hash, mime, size, src_url, created_at) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(item_id, hash) DO NOTHING
`

type InsertReadAssetParams struct {
	ItemID    int64
	Hash      string
	Mime      string
	Size      int64
	SrcUrl    string
	CreatedAt time.Time
}

func (q *Queries) InsertReadAsset(ctx context.Context, arg InsertReadAssetParams) error {
	_, err := q.db.ExecContext(ctx, insertReadAsset,
		arg.ItemID,
		arg.Hash,
		arg.Mime,
		arg.Size,
		arg.SrcUrl,
		arg.CreatedAt,
	)
	return err
}

const insertReadItem = `-- name: InsertReadItem :one
INSERT INTO read_items (url, title, site, note, source, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'queued', ?, ?) RETURNING id, url, title, title_locked, site, excerpt, content, summary, tags_json, note, source, status, error, attempts, read_at, created_at, fetched_at, updated_at, content_html, kind, meta_json
`

type InsertReadItemParams struct {
	Url       string
	Title     string
	Site      string
	Note      string
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertReadItem(ctx context.Context, arg InsertReadItemParams) (ReadItem, error) {
	row := q.db.QueryRowContext(ctx, insertReadItem,
		arg.Url,
		arg.Title,
		arg.Site,
		arg.Note,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ReadItem
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.TitleLocked,
		&i.Site,
		&i.Excerpt,
		&i.Content,
		&i.Summary,
		&i.TagsJson,
		&i.Note,
		&i.Source,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.ReadAt,
		&i.CreatedAt,
		&i.FetchedAt,
		&i.UpdatedAt,
		&i.ContentHtml,
		&i.Kind,
		&i.MetaJson,
	)
	return i, err
}

const listReadAssets = `-- name: ListReadAssets :many
SELECT item_id, hash, mime, size, src_url, created_at FROM read_assets WHERE item_id = ? ORDER BY hash
`

func (q *Queries) ListReadAssets(ctx context.Context, itemID int64) ([]ReadAsset, error) {
	rows, err := q.db.QueryContext(ctx, listReadAssets, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadAsset
	for rows.Next() {
		var i ReadAsset
		if err := rows.Scan(
			&i.ItemID,
			&i.Hash,
			&i.Mime,
			&i.Size,
			&i.SrcUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadItems = `-- name: ListReadItems :many
SELECT id, url, title, title_locked, site, excerpt, summary, tags_json, note, source, status, error, attempts,
       read_at, created_at, fetched_at, updated_at, kind, meta_json,
       CAST(content <> '' AS INTEGER) AS has_content, CAST(content_html <> '' AS INTEGER) AS has_html
FROM read_items ORDER BY created_at DESC, id DESC
`

type ListReadItemsRow struct {
	ID          int64
	Url         string
	Title       string
	TitleLocked int64
	Site        string
	Excerpt     string
	Summary     string
	TagsJson    string
	Note        string
	Source      string
	Status      string
	Error       string
	Attempts    int64
	ReadAt      *time.Time
	CreatedAt   time.Time
	FetchedAt   *time.Time
	UpdatedAt   time.Time
	Kind        string
	MetaJson    string
	HasContent  int64
	HasHtml     int64
}

// The list leaves out the body text. has_content says whether one is stored.
func (q *Queries) ListReadItems(ctx context.Context) ([]ListReadItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReadItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadItemsRow
	for rows.Next() {
		var i ListReadItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.TitleLocked,
			&i.Site,
			&i.Excerpt,
			&i.Summary,
			&i.TagsJson,
			&i.Note,
			&i.Source,
			&i.Status,
			&i.Error,
			&i.Attempts,
			&i.ReadAt,
			&i.CreatedAt,
			&i.FetchedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.MetaJson,
			&i.HasContent,
			&i.HasHtml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleQueuedReadItems = `-- name: ListStaleQueuedReadItems :many
SELECT id FROM read_items WHERE status = 'queued' AND updated_at < ? AND attempts < 3 ORDER BY id LIMIT 20
`

// Queued but never finished (for example after a restart). At most 3 tries.
func (q *Queries) ListStaleQueuedReadItems(ctx context.Context, updatedAt time.Time) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listStaleQueuedReadItems, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnreadReadItems = `-- name: OldestUnreadReadItems :many
SELECT id, title, url, site FROM read_items WHERE read_at IS NULL ORDER BY created_at ASC, id ASC LIMIT ?
`

type OldestUnreadReadItemsRow struct {
	ID    int64
	Title string
	Url   string
	Site  string
}

func (q *Queries) OldestUnreadReadItems(ctx context.Context, limit int64) ([]OldestUnreadReadItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, oldestUnreadReadItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OldestUnreadReadItemsRow
	for rows.Next() {
		var i OldestUnreadReadItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Site,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueReadItem = `-- name: QueueReadItem :exec
UPDATE read_items SET status = 'queued', error = '', updated_at = ? WHERE id = ?
`

type QueueReadItemParams struct {
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) QueueReadItem(ctx context.Context, arg QueueReadItemParams) error {
	_, err := q.db.ExecContext(ctx, queueReadItem, arg.UpdatedAt, arg.ID)
	return err
}

const resetReadAttempts = `-- name: ResetReadAttempts :exec
UPDATE read_items SET attempts = 0 WHERE id = ?
`

func (q *Queries) ResetReadAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetReadAttempts, id)
	return err
}

const saveReadFailure = `-- name: SaveReadFailure :exec
UPDATE read_items SET status = 'failed', error = ?, attempts = attempts + 1, updated_at = ? WHERE id = ?
`

type SaveReadFailureParams struct {
	Error     string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) SaveReadFailure(ctx context.Context, arg SaveReadFailureParams) error {
	_, err := q.db.ExecContext(ctx, saveReadFailure, arg.Error, arg.UpdatedAt, arg.ID)
	return err
}

const saveReadFetched = `-- name: SaveReadFetched :exec
UPDATE read_items SET
  title = CASE WHEN title_locked = 1 OR ?1 = '' THEN title ELSE ?1 END,
  site = ?2, excerpt = ?3, content = ?4,
  content_html = ?5, kind = ?6, meta_json = ?7,
  status = 'ready', error = '', attempts = attempts + 1, fetched_at = ?8, updated_at = ?8
WHERE id = ?9
`

type SaveReadFetchedParams struct {
	Title       interface{}
	Site        string
	Excerpt     string
	Content     string
	ContentHtml string
	Kind        string
	MetaJson    string
	At          *time.Time
	ID          int64
}

// An empty title keeps the old one (the user edited it, or the page had none).
func (q *Queries) SaveReadFetched(ctx context.Context, arg SaveReadFetchedParams) error {
	_, err := q.db.ExecContext(ctx, saveReadFetched,
		arg.Title,
		arg.Site,
		arg.Excerpt,
		arg.Content,
		arg.ContentHtml,
		arg.Kind,
		arg.MetaJson,
		arg.At,
		arg.ID,
	)
	return err
}

const saveReadSummary = `-- name: SaveReadSummary :exec
UPDATE read_items SET summary = ?, tags_json = ?, updated_at = ? WHERE id = ?
`

type SaveReadSummaryParams struct {
	Summary   string
	TagsJson  string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) SaveReadSummary(ctx context.Context, arg SaveReadSummaryParams) error {
	_, err := q.db.ExecContext(ctx, saveReadSummary,
		arg.Summary,
		arg.TagsJson,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateReadItem = `-- name: UpdateReadItem :one
UPDATE read_items SET title = ?, title_locked = ?, tags_json = ?, note = ?, read_at = ?, updated_at = ? WHERE id = ? RETURNING id, url, title, title_locked, site, excerpt, content, summary, tags_json, note, source, status, error, attempts, read_at, created_at, fetched_at, updated_at, content_html, kind, meta_json
`

type UpdateReadItemParams struct {
	Title       string
	TitleLocked int64
	TagsJson    string
	Note        string
	ReadAt      *time.Time
	UpdatedAt   time.Time
	ID          int64
}

func (q *Queries) UpdateReadItem(ctx context.Context, arg UpdateReadItemParams) (ReadItem, error) {
	row := q.db.QueryRowContext(ctx, updateReadItem,
		arg.Title,
		arg.TitleLocked,
		arg.TagsJson,
		arg.Note,
		arg.ReadAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ReadItem
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.TitleLocked,
		&i.Site,
		&i.Excerpt,
		&i.Content,
		&i.Summary,
		&i.TagsJson,
		&i.Note,
		&i.Source,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.ReadAt,
		&i.CreatedAt,
		&i.FetchedAt,
		&i.UpdatedAt,
		&i.ContentHtml,
		&i.Kind,
		&i.MetaJson,
	)
	return i, err
}
