// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Agent struct {
	ID           string
	Name         string
	Kind         string
	Os           string
	Arch         string
	Hostname     string
	Version      string
	Capabilities string
	TokenHash    string
	CreatedAt    time.Time
	LastSeenAt   *time.Time
	RevokedAt    *time.Time
}

type AiAgent struct {
	ID               int64
	Name             string
	Avatar           string
	Color            string
	Kind             string
	Model            string
	Instructions     string
	RunnerAgentID    *string
	Access           string
	CliPermission    string
	RepoIds          string
	MaxParallel      int64
	MonthlyBudgetUsd *float64
	AutoBuild        int64
	BuildRetries     int64
	Enabled          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	HostIds          string
}

type AiAgentDecision struct {
	ID        int64
	RunID     int64
	Kind      string
	Title     string
	Detail    string
	Options   string
	Dangerous int64
	Status    string
	Answer    string
	CreatedAt time.Time
}

type AiAgentRun struct {
	ID         int64
	AgentID    int64
	IssueKey   string
	IssueTitle string
	Kind       string
	Status     string
	TaskID     *int64
	OpenPr     int64
	PrUrl      string
	Summary    string
	CreatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time
}

type AiAgentRunEvent struct {
	RunID int64
	Seq   int64
	At    time.Time
	Kind  string
	Text  string
	Tool  string
	Ok    *int64
}

type AiAttachment struct {
	ID             int64
	ConversationID *int64
	Name           string
	Mime           string
	Size           int64
	Kind           string
	CreatedAt      time.Time
}

type AiConversation struct {
	ID         int64
	Title      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	HostID     *string
	Permission string
	Model      string
	Effort     string
}

type AiMemory struct {
	ID        int64
	Text      string
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AiMessage struct {
	ID             int64
	ConversationID int64
	Seq            int64
	Role           string
	Content        string
	CreatedAt      time.Time
}

type AiModelSpec struct {
	ProviderID    int64
	ModelID       string
	ContextWindow *int64
	ToolCall      *int64
	Reasoning     *int64
}

type AiPendingAction struct {
	ID             int64
	ConversationID int64
	ToolUseID      string
	Action         string
	Input          string
	Status         string
	Result         *string
	Effect         *string
}

type AiProvider struct {
	ID                int64
	Name              string
	BaseUrl           string
	ApiKeyEnc         *string
	ModelsRefreshedAt *time.Time
	LastError         *string
	CreatedAt         time.Time
	ApiStyle          string
}

type AiProviderModel struct {
	ProviderID int64
	ModelID    string
}

type AiUsage struct {
	ID                int64
	ProviderID        *int64
	ProviderName      string
	Model             string
	Purpose           string
	InputTokens       int64
	OutputTokens      int64
	DurationMs        int64
	Cost              *float64
	CreatedAt         time.Time
	CachedInputTokens int64
	CacheWriteTokens  int64
	ReasoningTokens   int64
	Source            string
	Ref               string
	Status            string
	Error             string
	CostEstimated     int64
}

type AlertEvent struct {
	ID         int64
	RuleID     *int64
	HostID     string
	HostName   string
	Metric     string
	Severity   string
	Value      float64
	Message    string
	FiredAt    time.Time
	ResolvedAt *time.Time
}

type AlertRule struct {
	ID              int64
	HostID          *string
	Metric          string
	Op              string
	Threshold       float64
	DurationSeconds int64
	Severity        string
	Enabled         int64
	CreatedAt       time.Time
}

type ApiToken struct {
	ID         int64
	Name       string
	Prefix     string
	TokenHash  string
	Access     string
	Modules    string
	ExpiresAt  *time.Time
	CreatedAt  time.Time
	LastUsedAt *time.Time
	LastUsedIp string
	RevokedAt  *time.Time
}

type AuditLog struct {
	ID     int64
	At     time.Time
	Actor  string
	Action string
	Target string
	Detail string
	Result string
}

type Automation struct {
	ID               int64
	Name             string
	Enabled          int64
	Trigger          string
	Conditions       string
	Actions          string
	CooldownSeconds  int64
	Authorized       int64
	WebhookTokenHash *string
	WebhookTokenEnc  *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type AutomationRun struct {
	ID           int64
	AutomationID int64
	StartedAt    time.Time
	FinishedAt   *time.Time
	TriggerData  string
	Steps        string
	Status       string
}

type BoardList struct {
	ID         int64
	BoardID    int64
	Name       string
	Position   float64
	Status     *string
	Color      string
	WipLimit   int64
	Collapsed  int64
	ArchivedAt *time.Time
	CreatedAt  time.Time
}

type BoardRepo struct {
	BoardID       int64
	ConnectionID  int64
	FullName      string
	Kind          string
	HtmlUrl       string
	CloneUrl      string
	DefaultBranch string
	SyncIssues    int64
	LastSyncedAt  *time.Time
	LastError     string
}

type Brief struct {
	ID        int64
	Date      string
	Content   string
	Sections  string
	CreatedAt time.Time
	SentAt    *time.Time
}

type Calendar struct {
	ID           int64
	Name         string
	Kind         string
	Url          string
	Username     string
	Secret       string
	Color        string
	Enabled      int64
	LastSyncedAt *time.Time
	LastError    string
	CreatedAt    time.Time
}

type CalendarEvent struct {
	ID           int64
	CalendarID   int64
	Uid          string
	Title        string
	StartsAt     time.Time
	EndsAt       time.Time
	AllDay       int64
	Tzid         string
	Location     string
	Description  string
	Rrule        string
	Rdates       string
	Exdates      string
	RecurrenceID *time.Time
	Href         string
	Etag         string
}

type CodingRepo struct {
	ID            int64
	AgentID       string
	Path          string
	Name          string
	DefaultBranch string
	RemoteUrl     string
	GithubRepo    string
	CreatedAt     time.Time
	ConnectionID  *int64
	Owner         string
	Repo          string
	CloneUrl      string
	BuildConfig   string
}

type CodingTask struct {
	ID              int64
	RepoID          int64
	IssueKey        string
	Executor        string
	Prompt          string
	BaseBranch      string
	Branch          string
	BaseCommit      string
	Status          string
	ExitCode        *int64
	Error           string
	CommitSha       string
	PrUrl           string
	ChangedFiles    string
	TimeoutMinutes  int64
	CreatedAt       time.Time
	StartedAt       *time.Time
	FinishedAt      *time.Time
	UpdatedAt       time.Time
	AiAgentID       *int64
	Model           string
	Permission      string
	BuildStatus     string
	BuildAttempts   int64
	Artifacts       string
	BuildError      string
	AutoOpenPr      int64
	WaitingQuestion string
}

type CodingTaskEvent struct {
	ID     int64
	TaskID int64
	Seq    int64
	At     time.Time
	Kind   string
	Text   string
	Data   string
}

type DriveFileVersion struct {
	ID        int64
	ItemID    int64
	Size      int64
	Sha256    string
	CreatedAt time.Time
}

type DriveItem struct {
	ID         int64
	ParentID   *int64
	Name       string
	IsDir      int64
	Size       int64
	Mime       string
	Sha256     string
	Hidden     int64
	HiddenFrom *int64
	TrashedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	S3SyncedAt *time.Time
	S3Etag     *string
	S3Error    *string
	S3Key      *string
	S3Hash     *string
}

type DriveS3Deletion struct {
	Key       string
	CreatedAt time.Time
}

type DriveShare struct {
	ID           int64
	ItemID       int64
	Token        string
	CodeSealed   *string
	ExpiresAt    *time.Time
	MaxDownloads *int64
	Visits       int64
	Downloads    int64
	CreatedAt    time.Time
	LastAccessAt *time.Time
}

type DriveShareDownload struct {
	ID        int64
	ShareID   int64
	At        time.Time
	Ip        string
	UserAgent string
	ItemID    *int64
	ItemName  string
}

type FocusSession struct {
	ID             int64
	IssueKey       string
	StartedAt      time.Time
	EndedAt        *time.Time
	PlannedMinutes int64
	ActualSeconds  int64
	Completed      int64
	Note           string
	NotifiedAt     *time.Time
}

type GitConnection struct {
	ID               int64
	Kind             string
	Name             string
	BaseUrl          string
	Username         string
	TokenEnc         string
	UseGithubModule  int64
	WebhookSecretEnc string
	CreatedAt        time.Time
	LastCheckedAt    *time.Time
	LastError        string
}

type GithubCacheV2 struct {
	ConnectionID int64
	Repo         string
	Kind         string
	ObjectID     string
	Data         string
	UpdatedAt    time.Time
}

type GithubCiState struct {
	Key       string
	State     string
	UpdatedAt time.Time
}

type GithubEventSeen struct {
	ConnectionID int64
	Repo         string
	Event        string
	ObjectID     string
	State        string
	ExpiresAt    time.Time
}

type GithubEventState struct {
	ConnectionID int64
	Repo         string
	Resource     string
	ObjectID     string
	Data         string
}

type GithubIssue struct {
	ID        int64
	Repo      string
	Number    int64
	Title     string
	Url       string
	Author    string
	Assignees string
	Labels    string
	Relation  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GithubLink struct {
	ID        int64
	Repo      string
	Number    int64
	Kind      string
	Ref       string
	CreatedAt time.Time
}

type GithubNotifyWindow struct {
	ConnectionID int64
	Repo         string
	Event        string
	StartedAt    time.Time
	Sent         int64
	Suppressed   int64
}

type GithubPull struct {
	ID          int64
	Repo        string
	Number      int64
	Title       string
	Author      string
	Url         string
	HeadRef     string
	HeadSha     string
	BaseRef     string
	Draft       bool
	ReviewState string
	CheckState  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	SyncedAt    time.Time
	State       string
}

type GithubRun struct {
	ID            int64
	Repo          string
	WorkflowID    int64
	Name          string
	Branch        string
	Event         string
	Status        string
	Conclusion    string
	Url           string
	HeadSha       string
	DefaultBranch bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type GithubSyntheticRun struct {
	ID           int64
	ConnectionID int64
	Repo         string
	Sha          string
}

type HaFavorite struct {
	EntityID  string
	SortOrder int64
	Alias     string
}

type Habit struct {
	ID                    int64
	Name                  string
	Icon                  string
	Color                 string
	Unit                  string
	DailyTarget           float64
	RemindMode            string
	RemindIntervalMinutes int64
	RemindWindow          string
	RemindTimes           string
	HaEntityID            string
	ArchivedAt            *time.Time
	SortOrder             int64
	CreatedAt             time.Time
	LastRemindedAt        *time.Time
	QuietUntil            *time.Time
	Kind                  string
	RemindWhen            string
	ActiveHostIds         string
	RemindOnHost          int64
	Template              string
	SnoozedUntil          *time.Time
}

type HabitLog struct {
	ID           int64
	HabitID      int64
	At           time.Time
	Amount       float64
	Source       string
	Note         string
	WorkoutLogID *int64
}

type HabitSchedule struct {
	ID          int64
	WorkDays    string
	WakeTime    string
	SleepTime   string
	WorkStart   string
	WorkEnd     string
	Timezone    string
	IdleMinutes int64
}

type HostInfo struct {
	HostID           string
	Ownership        string
	Client           string
	Username         string
	PasswordEnc      string
	Note             string
	Tags             string
	SortOrder        int64
	CountryCode      string
	CountryCheckedAt *time.Time
	CountryIp        string
	Addresses        string
}

type HostMetrics1h struct {
	HostID   string
	At       time.Time
	Cpu      float64
	MemUsed  int64
	MemTotal int64
	DiskJson string
	NetRx    float64
	NetTx    float64
	Load1    float64
}

type HostMetrics1m struct {
	HostID   string
	At       time.Time
	Cpu      float64
	MemUsed  int64
	MemTotal int64
	DiskJson string
	NetRx    float64
	NetTx    float64
	Load1    float64
}

type HostPairingInfo struct {
	CodeHash   string
	PayloadEnc string
}

type HostTrafficDaily struct {
	HostID    string
	Day       string
	Rx        int64
	Tx        int64
	Estimated int64
}

type HostTrafficHourly struct {
	HostID    string
	Hour      string
	Rx        int64
	Tx        int64
	Estimated int64
}

type HostTrafficPlan struct {
	HostID       string
	StartDay     int64
	PeriodMonths int64
	LimitBytes   int64
	CountMode    string
	AlertPercent int64
	AlertedCycle string
	AlertedLevel int64
	UpdatedAt    time.Time
}

type Issue struct {
	ID             int64
	ProjectID      int64
	Number         int64
	Title          string
	Description    string
	Status         string
	Priority       int64
	DueDate        *string
	MilestoneID    *int64
	SortOrder      float64
	ExternalSource string
	ExternalID     string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
	CategoryID     *int64
	DueAt          *string
	DueRemind      string
	DueNotifiedAt  *string
	BoardID        *int64
	ListID         *int64
	ArchivedAt     *time.Time
	CoverFileID    *int64
	Color          string
	ExternalUrl    string
}

type IssueActivity struct {
	ID      int64
	IssueID int64
	At      time.Time
	Actor   string
	Kind    string
	Data    string
}

type IssueChecklist struct {
	ID       int64
	IssueID  int64
	Title    string
	Position float64
}

type IssueChecklistItem struct {
	ID          int64
	ChecklistID int64
	Text        string
	Done        int64
	Position    float64
	DoneAt      *string
}

type IssueComment struct {
	ID        int64
	IssueID   int64
	Body      string
	CreatedAt time.Time
	Author    string
}

type IssueLabel struct {
	IssueID int64
	LabelID int64
}

type IssueLink struct {
	ID        int64
	IssueID   int64
	Kind      string
	Title     string
	Url       string
	Ref       string
	CreatedAt time.Time
}

type IssueMember struct {
	IssueID    int64
	MemberKind string
	MemberID   string
}

type Label struct {
	ID        int64
	ProjectID *int64
	Name      string
	Color     string
}

type LinearIssue struct {
	LinearID        string
	IssueKey        string
	Identifier      string
	RemoteUpdatedAt time.Time
	LocalUpdatedAt  time.Time
	SyncedAt        time.Time
}

type LinearTeam struct {
	TeamID    string
	TeamKey   string
	TeamName  string
	ProjectID int64
	Cursor    *time.Time
	CreatedAt time.Time
}

type MailAccount struct {
	ID          int64
	Name        string
	Email       string
	Provider    string
	ImapHost    string
	ImapPort    int64
	Username    string
	PasswordEnc string
	Notify      int64
	UidValidity int64
	LastUid     int64
	LastSyncAt  *time.Time
	CreatedAt   time.Time
}

type MailMessage struct {
	ID             int64
	AccountID      int64
	Uid            int64
	MessageID      string
	FromName       string
	FromAddress    string
	Subject        string
	Snippet        string
	Date           time.Time
	Unread         int64
	Flagged        int64
	HasAttachments int64
	BodyJson       *string
}

type Milestone struct {
	ID        int64
	ProjectID int64
	Name      string
	DueDate   *string
	CreatedAt time.Time
}

type Monitor struct {
	ID                  int64
	Kind                string
	Name                string
	Target              string
	IntervalSeconds     int64
	ExpectedStatus      int64
	Keyword             string
	TimeoutMs           int64
	Enabled             int64
	LastStatus          string
	LastCheckedAt       *time.Time
	LastError           string
	ConsecutiveFailures int64
	ExpiresAt           *time.Time
	ExpiryNotified      string
	CreatedAt           time.Time
	ManualExpiresAt     *time.Time
	ExpirySource        string
}

type MonitorIcon struct {
	MonitorID int64
	Mime      string
	Data      []byte
	FetchedAt time.Time
}

type MonitorResult struct {
	ID         int64
	MonitorID  int64
	At         time.Time
	Ok         int64
	StatusCode *int64
	LatencyMs  int64
	Error      string
	Detail     string
}

type Note struct {
	ID            int64
	Title         string
	Body          string
	Pinned        int64
	ArchivedAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Hidden        int64
	SuggestedTags *string
	AiCheckedHash *string
	Kind          string
	Color         string
}

type NoteAttachment struct {
	ID        int64
	NoteID    int64
	Name      string
	Mime      string
	Size      int64
	Sha256    string
	CreatedAt time.Time
}

type NoteShare struct {
	NoteID       int64
	Token        string
	PasswordHash *string
	ExpiresAt    *time.Time
	Visits       int64
	LastVisitAt  *time.Time
	CreatedAt    time.Time
}

type NoteTag struct {
	NoteID int64
	Tag    string
}

type NoteTagColor struct {
	Tag   string
	Color string
}

type NotesFt struct {
	Title string
	Body  string
}

type Notification struct {
	ID        int64
	CreatedAt time.Time
	Kind      string
	Title     string
	Body      string
	Link      string
	Priority  string
	Source    string
	Data      string
	ReadAt    *time.Time
}

type NotificationRoute struct {
	ID          int64
	KindPattern string
	MinPriority string
	Channels    string
	Enabled     int64
	SortOrder   int64
}

type PairingCode struct {
	CodeHash  string
	Name      string
	Kind      string
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Project struct {
	ID           int64
	Key          string
	Name         string
	Description  string
	Color        string
	Icon         string
	ArchivedAt   *time.Time
	NextNumber   int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LayoutLocked int64
}

type ProjectBoard struct {
	ID         int64
	ProjectID  int64
	Name       string
	Icon       string
	Position   float64
	Starred    int64
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ProjectCategory struct {
	ID        int64
	ProjectID int64
	ParentID  *int64
	Name      string
	Position  float64
}

type QuotaAccount struct {
	ID        int64
	Kind      string
	Name      string
	HostID    string
	Home      string
	ApiKey    string
	KeyHash   string
	SortOrder int64
	CreatedAt time.Time
}

type QuotaReading struct {
	AccountID    int64
	Ok           int64
	Error        string
	ErrorCode    string
	Plan         string
	User         string
	Credits      string
	BalancesJson string
	WindowsJson  string
	ReadAt       *time.Time
	TriedAt      time.Time
}

type Reminder struct {
	ID           int64
	Title        string
	Body         string
	Link         string
	Rrule        string
	Dtstart      time.Time
	NextAt       *time.Time
	LastFiredAt  *time.Time
	SnoozedUntil *time.Time
	DoneAt       *time.Time
	Enabled      int64
	CreatedAt    time.Time
	Icon         string
}

type RouterTraffic struct {
	At      int64
	Seconds int64
	Rx      int64
	Tx      int64
}

type Script struct {
	ID             int64
	Name           string
	Description    string
	Shell          string
	Body           string
	DefaultHostIds string
	TimeoutSeconds int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ScriptRun struct {
	ID          int64
	ScriptID    int64
	HostID      string
	HostName    string
	StartedAt   time.Time
	FinishedAt  *time.Time
	ExitCode    *int64
	Stdout      string
	Stderr      string
	Error       string
	TriggeredBy string
}

type Session struct {
	ID            string
	UserID        int64
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ElevatedUntil *time.Time
	UserAgent     string
	Ip            string
	VaultUntil    *time.Time
}

type Setting struct {
	Key       string
	Value     string
	Encrypted int64
	UpdatedAt time.Time
}

type SshHost struct {
	ID        int64
	Name      string
	Address   string
	Port      int64
	Username  string
	Auth      string
	Secret    string
	HostKey   string
	CreatedAt time.Time
}

type StorageRemote struct {
	ID          int64
	Kind        string
	Name        string
	Config      string
	ShowInDrive int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Subscription struct {
	ID               int64
	Name             string
	Category         string
	Amount           float64
	Currency         string
	Cycle            string
	CycleDays        int64
	NextRenewal      string
	RemindDaysBefore string
	Reminded         string
	Url              string
	Note             string
	AutoRenew        int64
	ArchivedAt       *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CategoryID       *int64
	CycleCount       int64
	CycleUnit        string
	Account          string
}

type SubscriptionCategory struct {
	ID        int64
	Name      string
	Builtin   *string
	Position  int64
	CreatedAt time.Time
}

type SubscriptionEvent struct {
	ID             int64
	SubscriptionID int64
	At             time.Time
	Kind           string
	Detail         string
}

type UploadedFile struct {
	ID        int64
	Scope     string
	Name      string
	Mime      string
	Size      int64
	Sha256    string
	OwnerKind *string
	OwnerID   *int64
	CreatedAt time.Time
}

type User struct {
	ID             int64
	Username       string
	PasswordHash   string
	TotpSecret     string
	TotpEnabled    int64
	CreatedAt      time.Time
	SetupCompleted int64
}

type WebpushSubscription struct {
	ID          int64
	Endpoint    string
	P256dh      string
	Auth        string
	UserAgent   string
	CreatedAt   time.Time
	LastOkAt    *time.Time
	LastError   *string
	LastErrorAt *time.Time
}

type WorkoutLog struct {
	ID              int64
	Date            string
	PlanID          *int64
	Items           string
	DurationMinutes int64
	Note            string
	CreatedAt       time.Time
}

type WorkoutPlan struct {
	ID      int64
	Weekday int64
	Title   string
	Items   string
}
